<?php
// auto-generated by sfPropelAdmin
// date: 2008/07/03 12:49:40
?>
<?php echo form_tag('oycsitcon/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($ocregcon, 'getId') ?>
<?php echo javascript_include_tag('tools','observe','dFilter','ajax','obras/ofertas') ?>
<table width="100%">
  <tr>
    <th><strong><font color="<? print $color;?>" size="2" face="Verdana, Arial, Helvetica, sans-serif"> <? print $eti;?></font></strong></th>
  </tr>
</table>
<fieldset id="sf_fieldset_none" class="">
<legend><?php echo __('Datos del Contrato')?></legend>
<div class="form-row">
  <?php echo label_for('ocregcon[codcon]', __($labels['ocregcon{codcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{codcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{codcon}')): ?>
    <?php echo form_error('ocregcon{codcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getCodcon', array (
  'size' => 32,
  'readonly' => true,
  'control_name' => 'ocregcon[codcon]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregcon, 'getDescon', array (
  'size' => 80,
  'control_name' => 'ocregcon[descon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
  <?php echo label_for('ocregcon[desobr]', __($labels['ocregcon{desobr}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{desobr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{desobr}')): ?>
    <?php echo form_error('ocregcon{desobr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getDesobr', array (
  'disabled' => true,
  'control_name' => 'ocregcon[desobr]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
  <?php echo label_for('ocregcon[nompro]', __($labels['ocregcon{nompro}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{nompro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{nompro}')): ?>
    <?php echo form_error('ocregcon{nompro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getNompro', array (
  'disabled' => true,
  'control_name' => 'ocregcon[nompro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>

<br>

<?php tabMainJS("tp1","tabPane1", "tabPage1", 'Financiera Global');?>
<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
<table>
<tr>
<th>
  <?php echo label_for('ocregcon[totalc]', __($labels['ocregcon{totalc}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{totalc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{totalc}')): ?>
    <?php echo form_error('ocregcon{totalc}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getTotalc', array (
  'disabled' => true,
  'control_name' => 'ocregcon[totalc]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
<th>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</th>
<th>
  <?php echo label_for('ocregcon[totalv]', __($labels['ocregcon{totalv}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{totalv}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{totalv}')): ?>
    <?php echo form_error('ocregcon{totalv}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getTotalv', array (
  'disabled' => true,
  'control_name' => 'ocregcon[totalv]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
</tr>
</table>

<br>

<table>
<tr>
<th>
  <?php echo label_for('ocregcon[totalcv]', __($labels['ocregcon{totalcv}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{totalcv}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{totalcv}')): ?>
    <?php echo form_error('ocregcon{totalcv}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getTotalcv', array (
  'disabled' => true,
  'control_name' => 'ocregcon[totalcv]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
<th>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</th>
<th>
  <?php echo label_for('ocregcon[monper]', __($labels['ocregcon{monper}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{monper}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{monper}')): ?>
    <?php echo form_error('ocregcon{monper}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getMonper', array (
  'disabled' => true,
  'control_name' => 'ocregcon[monper]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
</tr>
</table>

<br>

<table>
<tr>
<th>
  <?php echo label_for('ocregcon[aumobr]', __($labels['ocregcon{aumobr}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{aumobr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{aumobr}')): ?>
    <?php echo form_error('ocregcon{aumobr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getAumobr', array (
  'disabled' => true,
  'control_name' => 'ocregcon[aumobr]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
<th>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</th>
<th>
  <?php echo label_for('ocregcon[monded]', __($labels['ocregcon{monded}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{monded}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{monded}')): ?>
    <?php echo form_error('ocregcon{monded}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getMonded', array (
  'disabled' => true,
  'control_name' => 'ocregcon[monded]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
</tr>
</table>

<br>

<table>
<tr>
<th>
  <?php echo label_for('ocregcon[disobr]', __($labels['ocregcon{disobr}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{disobr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{disobr}')): ?>
    <?php echo form_error('ocregcon{disobr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getDisobr', array (
  'disabled' => true,
  'control_name' => 'ocregcon[disobr]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
<th>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</th>
<th>
  <?php echo label_for('ocregcon[moneje]', __($labels['ocregcon{moneje}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{moneje}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{moneje}')): ?>
    <?php echo form_error('ocregcon{moneje}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getMoneje', array (
  'disabled' => true,
  'control_name' => 'ocregcon[moneje]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
</tr>
</table>

<br>

<table>
<tr>
<th>
  <?php echo label_for('ocregcon[obrext]', __($labels['ocregcon{obrext}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{obrext}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{obrext}')): ?>
    <?php echo form_error('ocregcon{obrext}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getObrext', array (
  'disabled' => true,
  'control_name' => 'ocregcon[obrext]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
<th>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</th>
<th>
  <?php echo label_for('ocregcon[poreje]', __($labels['ocregcon{poreje}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{poreje}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{poreje}')): ?>
    <?php echo form_error('ocregcon{poreje}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getPoreje', array (
  'disabled' => true,
  'control_name' => 'ocregcon[poreje]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</th>
</tr>
</table>
</div>
</fieldset>

<?php tabPageOpenClose("tp1", "tabPage2", 'Financiera Detallada');?>
<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
<?php echo grid_tag($obj);?>

<br>

  <?php echo label_for('ocregcon[totobreje]', __($labels['ocregcon{totobreje}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{totobreje}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{totobreje}')): ?>
    <?php echo form_error('ocregcon{totobreje}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getTotobreje', array (
  'readonly' => true,
  'control_name' => 'ocregcon[totobreje]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</fieldset>

<?php tabPageOpenClose("tp1", "tabPage3", 'Financiera Física');?>
<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
<?php echo grid_tag($obj2);?>

<br>

  <?php echo label_for('ocregcon[totobrejefis]', __($labels['ocregcon{totobrejefis}']), 'class="required" Style="width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('ocregcon{totobrejefis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregcon{totobrejefis}')): ?>
    <?php echo form_error('ocregcon{totobrejefis}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregcon, 'getTotobrejefis', array (
  'readonly' => true,
  'control_name' => 'ocregcon[totobrejefis]',
)); echo $value ? $value : '&nbsp;' ?>
<?php echo '&nbsp;&nbsp;'.'%'?>
    </div>
</div>
</fieldset>

<?php tabInit('tp1','0');?>

<?php include_partial('edit_actions', array('ocregcon' => $ocregcon)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>

<script language="JavaScript" type="text/javascript">
 var totales='<?php echo $totalizar?>';
  if (totales=='1')
  {
    totalizarsfd2();
  }
  else if (totales=='2')
  {
    totalizarsfd();
  }
  totalizarsf();

  function totalizarsfd()
  {
  	var acum=0;
  	var acum2=0;
  	var totreg=parseInt('<?php echo $fil1?>');
    var l=0;
    while (l<totreg)
    {
      var moneje="ax"+"_"+l+"_4";
      var mondif="ax"+"_"+l+"_5";
      var num1=toFloat(moneje);
      var num2=toFloat(mondif);

     if (num1>0)
     {
       acum= acum + num1;
     }

     if (num2>0)
     {
       acum2= acum2 + num2;
     }
   l++;
   }

   $('ocregcon_poreje').value=format(acum2.toFixed(2),'.',',','.');
   $('ocregcon_totobreje').value=format(acum.toFixed(2),'.',',','.');
   $('ocregcon_moneje').value=format(acum.toFixed(2),'.',',','.');

  }

  function totalizarsfd2()
  {
  	var acum=0;
  	var acum2=0;
  	var totreg=parseInt('<?php echo $fil1?>');
    var l=0;
    while (l<totreg)
    {
      var moneje="ax"+"_"+l+"_4";
      var num1=toFloat(moneje);

     if (num1>0)
     {
       acum= acum + num1;
     }
     l++;
   }

   $('ocregcon_totobreje').value=format(acum.toFixed(2),'.',',','.');
   $('ocregcon_moneje').value=format(acum.toFixed(2),'.',',','.');

  }

  function totalizarsf()
  {
  	var acum=0;
  	var totreg2=parseInt('<?php echo $fil2?>');
    var i=0;
    while (i<totreg2)
    {
      var monporeje="bx"+"_"+i+"_6";
      var num1=toFloat(monporeje);

     if (num1>0)
     {
       acum= acum + num1;
     }

   i++;
   }
  if (totreg2>0)
  {
   $('ocregcon_totobrejefis').value=format((acum/totreg2).toFixed(2),'.',',','.');
  }

  }
</script>
