<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/09 17:13:35
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'fordefprg/list?id='.$fordefprg->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'form' => 'sf_admin_edit_form',
  'class' => 'sf_admin_action_save',
)) ?></li>
    <li><?php echo button_to(__('create'), 'fordefprg/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
