<?php
// auto-generated by PropelCidesa
// date: 2008/12/08 12:48:59
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'PopUp', 'Grid', 'SubmitClick') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Precios',
array()) ?></h1>


<div id="sf_admin_header">
<?php include_partial('faartpvp/edit_header', array('faartpvp' => $faartpvp)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('faartpvp/edit_messages', array('faartpvp' => $faartpvp, 'labels' => $labels)) ?>
<?php include_partial('faartpvp/edit_form', array('faartpvp' => $faartpvp, 'labels' => $labels, 'obj' => $obj)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('faartpvp/edit_footer', array('faartpvp' => $faartpvp)) ?>
</div>

</div>
