<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/15 16:36:51
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoTesdeftipmov
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Javascript') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Tipos de Movimientos Bancarios',
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('tesdeftipmov/edit_header', array('tstipmov' => $tstipmov)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('tesdeftipmov/edit_messages', array('tstipmov' => $tstipmov, 'labels' => $labels)) ?>
<?php include_partial('tesdeftipmov/edit_form', array('tstipmov' => $tstipmov, 'mascaracontabilidad' => $mascaracontabilidad, 'loncta' => $loncta, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('tesdeftipmov/edit_footer', array('tstipmov' => $tstipmov)) ?>
</div>

</div>
