<?php
// auto-generated by PropelCidesa
// date: 2009/04/07 14:46:57
?>
<?php echo form_tag('facranpaginm/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fcvalinm, 'getId') ?>



<h2 class="h2" onclick="javascript: return $('divDatos Generales').toggle();"><?php echo __('Datos Generales') ?></h2>
<fieldset id="sf_fieldset_datos_generales" class="">

<div class="form-row" id="divDatos Generales">
<div id="divcodzon">
  <?php if($labels['fcvalinm{codzon}']!='.:') { ?>
  <?php echo label_for('fcvalinm[codzon]', __($labels['fcvalinm{codzon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{codzon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{codzon}')): ?>
    <?php echo form_error('fcvalinm{codzon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = object_input_tag($fcvalinm, 'getCodzon', array (
  'size' => 10,
  'control_name' => 'fcvalinm[codzon]',
  'maxlength' => 3,
)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{codzon}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
<div id="divdeszon">
  <?php if($labels['fcvalinm{deszon}']!='.:') { ?>
  <?php echo label_for('fcvalinm[deszon]', __($labels['fcvalinm{deszon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{deszon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{deszon}')): ?>
    <?php echo form_error('fcvalinm{deszon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = object_input_tag($fcvalinm, 'getDeszon', array (
  'size' => 40,
  'control_name' => 'fcvalinm[deszon]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{deszon}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
<div id="divanovig">
  <?php if($labels['fcvalinm{anovig}']!='.:') { ?>
  <?php echo label_for('fcvalinm[anovig]', __($labels['fcvalinm{anovig}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{anovig}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{anovig}')): ?>
    <?php echo form_error('fcvalinm{anovig}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = object_input_tag($fcvalinm, 'getAnovig', array (
  'size' => 4,
  'control_name' => 'fcvalinm[anovig]',
  'maxlength' => 4,
)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{anovig}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
<div id="divvalmtr">
  <?php if($labels['fcvalinm{valmtr}']!='.:') { ?>
  <?php echo label_for('fcvalinm[valmtr]', __($labels['fcvalinm{valmtr}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{valmtr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{valmtr}')): ?>
    <?php echo form_error('fcvalinm{valmtr}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = get_partial('valmtr', array('type' => 'edit', 'fcvalinm' => $fcvalinm,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{valmtr}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
<div id="divporvalfis">
  <?php if($labels['fcvalinm{porvalfis}']!='.:') { ?>
  <?php echo label_for('fcvalinm[porvalfis]', __($labels['fcvalinm{porvalfis}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{porvalfis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{porvalfis}')): ?>
    <?php echo form_error('fcvalinm{porvalfis}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = get_partial('porvalfis', array('type' => 'edit', 'fcvalinm' => $fcvalinm,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{porvalfis}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
<div id="divvalfis">
  <?php if($labels['fcvalinm{valfis}']!='.:') { ?>
  <?php echo label_for('fcvalinm[valfis]', __($labels['fcvalinm{valfis}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{valfis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{valfis}')): ?>
    <?php echo form_error('fcvalinm{valfis}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = object_input_tag($fcvalinm, array('getValfis',true), array (
  'size' => 10,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fcvalinm[valfis]',
  'readonly' => true,
)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{valfis}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
</div>
</fieldset>
<h2 class="h2" onclick="javascript: return $('divAsociación de Recaudos').toggle();"><?php echo __('Asociación de Recaudos') ?></h2>
<fieldset id="sf_fieldset_asociaci__n_de_recaudos" class="">

<div class="form-row" id="divAsociación de Recaudos">
<div id="divgrid">
  <?php if($labels['fcvalinm{grid}']!='.:') { ?>
  <?php echo label_for('fcvalinm[grid]', __($labels['fcvalinm{grid}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcvalinm{grid}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcvalinm{grid}')): ?>
    <?php echo form_error('fcvalinm{grid}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>



  <?php $value = get_partial('grid', array('type' => 'edit', 'fcvalinm' => $fcvalinm,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>


  <?php if($labels['fcvalinm{grid}']!='.:') { ?>



  </div>
  <?php  } ?>

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('fcvalinm' => $fcvalinm)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fcvalinm->getId()): ?>
<?php echo button_to(__('delete'), 'facranpaginm/delete?id='.$fcvalinm->getId().'&codzon='.$fcvalinm->getCodzon(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

