<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/21 10:44:21
?>
<!-- 
<ul class="sf_admin_actions">
  <li><
  ?php echo button_to(__('create'), 'nomconceptoscompensacion/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
 -->