<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/16 17:45:33
?>
<?php echo form_tag('almtipent/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($catipent, 'getId') ?>

<fieldset id="sf_fieldset_editable" class="">
<h2><?php echo __('Editable') ?></h2>


<div class="form-row">
  <?php echo label_for('catipent[codtipent]', __($labels['catipent{codtipent}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('catipent{codtipent}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catipent{codtipent}')): ?>
    <?php echo form_error('catipent{codtipent}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catipent, 'getCodtipent', array (
  'size' => 20,
  'control_name' => 'catipent[codtipent]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catipent[destipent]', __($labels['catipent{destipent}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('catipent{destipent}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catipent{destipent}')): ?>
    <?php echo form_error('catipent{destipent}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catipent, 'getDestipent', array (
  'size' => 50,
  'control_name' => 'catipent[destipent]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('catipent' => $catipent)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($catipent->getId()): ?>
<?php echo button_to(__('delete'), 'almtipent/delete?id='.$catipent->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
