<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/22 18:30:34
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'nomnomcalnom/list?id='.$npnomina->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>  
</ul>
