<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/30 18:33:23
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'almdespser/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
