<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/20 12:29:18
?>
<?php echo form_tag('almajuoc/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($caajuoc, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('caajuoc[ajuoc]', __($labels['caajuoc{ajuoc}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('caajuoc{ajuoc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caajuoc{ajuoc}')): ?>
    <?php echo form_error('caajuoc{ajuoc}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caajuoc, 'getAjuoc', array (
  'size' => 20,
  'control_name' => 'caajuoc[ajuoc]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('caajuoc[ordcom]', __($labels['caajuoc{ordcom}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('caajuoc{ordcom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caajuoc{ordcom}')): ?>
    <?php echo form_error('caajuoc{ordcom}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caajuoc, 'getOrdcom', array (
  'size' => 20,
  'control_name' => 'caajuoc[ordcom]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('caajuoc[fecaju]', __($labels['caajuoc{fecaju}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('caajuoc{fecaju}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caajuoc{fecaju}')): ?>
    <?php echo form_error('caajuoc{fecaju}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($caajuoc, 'getFecaju', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'caajuoc[fecaju]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('caajuoc[desaju]', __($labels['caajuoc{desaju}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('caajuoc{desaju}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caajuoc{desaju}')): ?>
    <?php echo form_error('caajuoc{desaju}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caajuoc, 'getDesaju', array (
  'size' => 80,
  'control_name' => 'caajuoc[desaju]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('caajuoc[monaju]', __($labels['caajuoc{monaju}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('caajuoc{monaju}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caajuoc{monaju}')): ?>
    <?php echo form_error('caajuoc{monaju}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caajuoc, 'getMonaju', array (
  'size' => 7,
  'control_name' => 'caajuoc[monaju]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<div class="grid01" id="grid01">
<fieldset>
<legend>Detalle del Ajuste</legend>
<table border="0" class="sf_admin_list">
<thead>
	<tr>
	    <th><?php echo CaartaocPeer::getColumName(CaartaocPeer::AJUOC) ?></th>
	    <th><?php echo CaartaocPeer::getColumName(CaartaocPeer::CODART )  ?></th>
	    <th><?php echo CaartaocPeer::getColumName(CaartaocPeer::CANAJU) ?></th>
	    <th><?php echo CaartaocPeer::getColumName(CaartaocPeer::CANORD) ?></th>
	    <th><?php echo CaartaocPeer::getColumName(CaartaocPeer::MONTOT) ?></th>
	</tr>
</thead>
<tbody>
	<?php $i = 1; foreach ($pagercaartaoc->getResults() as $caartaoc): $odd = fmod(++$i, 2) ?>
	<tr class="sf_admin_row_<?php echo $odd ?>">
	    <td><?php echo $caartaoc->getAjuoc() ?></td>
	    <td><?php echo $caartaoc->getCodart()  ?></td>
	    <td><?php echo $caartaoc->getCanaju() ?></td>
	    <td><?php echo $caartaoc->getCanord() ?></td>
	    <td><?php echo $caartaoc->getMontot() ?></td>
	</tr>
	<?php endforeach; ?>
</tbody>	
  </table>
</fieldset>
</div>


<?php include_partial('edit_actions', array('caajuoc' => $caajuoc)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($caajuoc->getId()): ?>
<?php echo button_to(__('delete'), 'almajuoc/delete?id='.$caajuoc->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
