<?php
// auto-generated by sfPropelAdmin
// date: 2008/07/23 17:24:45
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'oycdescon/list?id='.$ocregcon->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'form' => 'sf_admin_edit_form',
  'class' => 'sf_admin_action_save',
)) ?></li>
    <li><?php echo button_to(__('create'), 'oycdescon/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
