<?php
// auto-generated by PropelCidesa
// date: 2008/12/26 09:15:27
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Emisión de Presupuesto',
array()) ?></h1>


<div id="sf_admin_header">
<?php include_partial('fapresup/edit_header', array('fapresup' => $fapresup)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('fapresup/edit_messages', array('fapresup' => $fapresup, 'labels' => $labels)) ?>
<?php include_partial('fapresup/edit_form', array('fapresup' => $fapresup, 'labels' => $labels, 'moneda' => $moneda, 'numreg' => $numreg)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('fapresup/edit_footer', array('fapresup' => $fapresup)) ?>
</div>

</div>
