<?php
// auto-generated by PropelCidesa
// date: 2008/06/23 15:51:43
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'oycoferpre/edit?id='.$ocoferpre->getId().'&contratista='.$ocoferpre->getCodpro().'&obra='.$ocoferpre->getCodobr()) ?></li>
</ul>
</td>
