<?php
// auto-generated by sfPropelAdmin
// date: 2008/02/14 11:49:27
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Registro Histórico de Anticipos Otorgados',
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('presnomreghisantpre/edit_header', array('npantpre' => $npantpre)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('presnomreghisantpre/edit_messages', array('npantpre' => $npantpre, 'labels' => $labels)) ?>
<?php include_partial('presnomreghisantpre/edit_form', array('npantpre' => $npantpre, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('presnomreghisantpre/edit_footer', array('npantpre' => $npantpre)) ?>
</div>

</div>
