<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/01 10:54:11
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'asignarconceptosnomina/list?id='.$npnomina->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'form' => 'sf_admin_edit_form',
  'class' => 'sf_admin_action_save',
)) ?></li>
  </ul>


