<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/29 14:16:50
?>
<?php echo form_tag('nomdefconfon/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($npconfon, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<fieldset id="sf_fieldset_none" class="">
<legend>Tipos de N&oacute;mina</legend>
<div class="form-row">
 <strong>C&oacute;digo</strong>
  <?php $value = object_input_tag($npconfon, 'getCodnom', array (
  'size' => 20,
  'control_name' => 'npconfon[codnom]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;
<?php echo button_to('...','#')?>
&nbsp;&nbsp;&nbsp;
<?php echo $nombre ?>
    </div>
</div>
</fieldset>

<fieldset id="sf_fieldset_none" class="">
<legend>Conceptos Deducci&oacute;n y Aporte</legend>
<div class="form-row">
 <strong>Deducci&oacute;n</strong>
  <?php $value = object_input_tag($npconfon, 'getCodcon', array (
  'size' => 20,
  'control_name' => 'npconfon[codcon]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;
<?php echo button_to('...','#')?>
&nbsp;&nbsp;&nbsp;
<?php echo $nombrec ?>
</div>

<div class="form-row">
 <strong>Aporte</strong>
 <?php echo input_tag('aporte', '', 'size=5 maxlength=3') ?>
&nbsp;&nbsp;&nbsp;
<?php echo button_to('...','#')?>
&nbsp;&nbsp;&nbsp;    
</div>
</fieldset>

<fieldset id="sf_fieldset_none" class="">
<legend>Conceptos Deducci&oacute;n y Aporte</legend>
<div class="form-row">
 <strong>Ajuste Deducci&oacute;n</strong>
  <?php $value = object_input_tag($npconfon, 'getCodcon', array (
  'size' => 20,
  'control_name' => 'npconfon[codcon]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;
<?php echo button_to('...','#')?>
&nbsp;&nbsp;&nbsp;
</div>

<div class="form-row">
 <strong>Ajuste por Aporte</strong>
 <?php echo input_tag('aporte', '', 'size=5 maxlength=3') ?>
&nbsp;&nbsp;&nbsp;
<?php echo button_to('...','#')?>
&nbsp;&nbsp;&nbsp;    
</div>
</fieldset>

<div>
<fieldset>
<legend>Conceptos para el C&aacute;lculo</legend>
<table border="0" class="sf_admin_list">
<thead>
	<tr>
	    <th><?php echo 'Marque' ?></th>	
	    <th><?php echo NpconfonPeer::getColumName(NpconfonPeer::CODCON) ?></th>
	    <!--<th><
	    ?
	    php echo NpdefcptPeer::getColumName(NpdefcptPeer::NOMCON)  ?></th>-->
	    </tr>
</thead>
<tbody>
	<?php $i = 1; foreach ($pagerNpconfon->getResults() as $Npconfon): $odd = fmod(++$i, 2) ?>
	<tr class="sf_admin_row_<?php echo $odd ?>">
	    <td><?php echo checkbox_tag($Npconfon->getId(),'1',false) ?></td>
	    <td><?php echo $Npconfon->getCodcon()  ?></td>
	   <!--  <td><
	   ?php echo $Npdefcpt->getNomcon() ?></td> -->
	    </tr>
	<?php endforeach; ?>	
</tbody>

<tfoot>
<tr><th colspan="5">
<div class="float-right">
<?php if ($pagerNpconfon->haveToPaginate()): ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/first.png', array('align' => 'absmiddle', 'alt' => __('First'), 'title' => __('First'))), 'nomdefconfon/list?page=1') ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/previous.png', array('align' => 'absmiddle', 'alt' => __('Previous'), 'title' => __('Previous'))), 'nomdefconfon/list?page='.$pagerNpconfon->getPreviousPage()) ?>

  <?php foreach ($pagerNpconfon->getLinks() as $page): ?>
    <?php echo link_to_unless($page == $pagerNpconfon->getPage(), $page, 'nomdefconfon/list?page='.$page) ?>
  <?php endforeach; ?>

	<?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/next.png', array('align' => 'absmiddle', 'alt' => __('Next'), 'title' => __('Next'))), 'nomdefconfon/edit?page='.$pagerNpconfon->getNextPage()) ?>
	<?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/last.png', array('align' => 'absmiddle', 'alt' => __('Last'), 'title' => __('Last'))), 'nomdefconfon/edit?page='.$pagerNpconfon->getLastPage()) ?>
<?php endif; ?>
</div>
<?php echo format_number_choice('[0] no result|[1] 1 result|(1,+Inf] %1% results', array('%1%' => $pagerNpconfon->getNbResults()), $pagerNpconfon->getNbResults()) ?>
</th></tr>
</tfoot>

</table>
</fieldset>
</div>
<div class="form-row">
<strong>Buscar</strong>
<?php echo input_tag('buscar', '', 'size=80 maxlength=80') ?>
</div>
</fieldset>

<?php include_partial('edit_actions', array('npconfon' => $npconfon)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($npconfon->getId()): ?>
<?php echo button_to(__('delete'), 'nomdefconfon/delete?id='.$npconfon->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
