<?php
// auto-generated by PropelCidesa
// date: 2008/12/05 12:41:00
?>
    <td><?php echo link_to(($cainvfis->getFecinv() !== null && $cainvfis->getFecinv() !== '') ? format_date($cainvfis->getFecinv(), "dd/MM/yyyy") : '' ? ($cainvfis->getFecinv() !== null && $cainvfis->getFecinv() !== '') ? format_date($cainvfis->getFecinv(), "dd/MM/yyyy") : '' : __('-'), 'almtrainv/edit?id='.$cainvfis->getId())  ?></td>
<td><?php echo $cainvfis->getCodalm() ?></td>
      <td><?php echo $cainvfis->getDesalm() ?></td>
      <td><?php echo $cainvfis->getCodubi() ?></td>
      <td><?php echo $cainvfis->getDesubi() ?></td>

