var ReportesContabilidad='http://'+window.location.host+'/reportes/reportes/contabilidad/';
var ReportesPresupuesto='http://'+window.location.host+'/reportes/reportes/presupuesto/';

var TREE_ITEMSPRE = [
  ['SIGA', null,
    ['Contabilidad Presupuestaria', null,
      ['Definiciones espec&iacute;ficas',null,
        ['Niveles Presupuestarios','PreNivPre.php'],
        ['Títulos Presupuestarios','PreTitPre.php'],
        ['Asignaci&oacute;n Inicial', 'PreAsiIni.php'],
        ['Asignar Partidas', 'PreAsiPar.php'],
        ['Artíulos de Ley', 'PreArtLey.php'],
        ['Documentos',null,
          ['Precompromisos','PreDocPre.php'],
          ['Compromisos','PreDocCom.php'],
          ['Causados', 'PreDocCau.php'],
          ['Pagos', 'PreDocPag.php'],
          ['Ajustes', 'PreDocAju.php'],
        ],
            ],

      ['Ejecución Presupuestaria',null,
        ['Ejecución Global','PreEjeGlo.php'],
        ['Precomprometer','PrePreCom.php'],
        ['Comprometer', 'PreCompro.php'],
        ['Causar', 'PreCausar.php'],
        ['Pagar', 'PrePagar.php'],
        ['Solicitud de Traslados', 'PreSolTrasla.php'],
        ['Traslados', 'PreTrasla.php'],
        ['Adiciones/Disminuciones', 'PreAdiDis.php'],
        ['Ajustes Ejecución', 'PreAjuste.php'],
            ],
      ['Reportes',null,
          ['Definiciones Especificas',null,
            ['Catálogo de Partidas', ReportesPresupuesto+'precatpar.php'],
            ['Documentos Precompromiso', ReportesPresupuesto+'PreCatPrc.php'],
            ['Documentos Compromiso', ReportesPresupuesto+'PreCatCom.php'],
            ['Documentos Causado', ReportesPresupuesto+'PreCatCau.php'],
            ['Documentos Pago', ReportesPresupuesto+'PreCatPag.php'],
          ],
          ['Movimientos',null,
            ['Precompromisos', ReportesPresupuesto+'PrePrc.php'],
            ['Compromisos', ReportesPresupuesto+'PreCom.php'],
            ['Causados', ReportesPresupuesto+'PreCau.php'],
            ['Pagados', ReportesPresupuesto+'PrePag.php'],
            ['Traslados', ReportesPresupuesto+'PreTra.php'],
            ['Ajustes', ReportesPresupuesto+'PreAju.php'],
            ['Adiciones/Disminuciones', ReportesPresupuesto+'PreRAdiDis.php'],
          ],
          ['Ejecución Presupuestaria',null,
            ['Asignación Inicial', ReportesPresupuesto+'PreRAsiIni.php'],
            ['Asignación Inicial por Partidas', ReportesPresupuesto+'prerasiinipar.php'],
            ['Ejecución Presupuestaria', ReportesPresupuesto+'PreDisPer.php'],
            ['Ejecución Presupuestaria Coordinada', ReportesPresupuesto+'PREDISPERCOO_DISCOM.php'],
            ['Ejecución Presupuestaria por Partida', ReportesPresupuesto+'PreDisPar.php'],
            ['Disponibilidad Financiera', ReportesPresupuesto+'PreDisFin.php'],
            ['Disponibilidad Negativa', ReportesPresupuesto+'PreDisNeg.php'],
          ]
            ],
    ],
  ]
];

var TREE_ITEMSCON = [
  ['SIGA', null,
    ['Contabilidad Financiera', null,
      ['Definiciones espec&iacute;ficas de la Institución','ConFinIns.php'],
      ['Tipos de Cuentas - Cuentas Contables','ConFinTipCueCon.php'],
      ['Catálogo de Cuentas', 'ConFinCue.php'],
      ['Comprobantes', 'ConFinCom.php'],
      ['Actualizar Comprobantes', 'ConFinActCom.php'],
      ['Cierre del Periodo', 'ConFinCiePer.php'],
      ['Cierre del Ejercicio', 'ConFinCie.php'],
    ['Mantenimiento', null,
      ['Eliminar Comprobantes Anulados','ConFinElicom.php'],
    ],
    ['Reportes', null,
      ['Catalogo de Cuentas', ReportesContabilidad+'ConCatCue.php'],
      ['Diario de Comprobantes', ReportesContabilidad+'ConDiaCom.php'],
      ['Resumen de Comprobantes', ReportesContabilidad+'ConResCom.php'],
      ['Resumen Diario', ReportesContabilidad+'ConResDia.php'],
      ['Balance de Comprobación', ReportesContabilidad+'ConBalCom.php'],
      ['Balance General', ReportesContabilidad+'ConBalGen.php'],
      ['Estado de Resultados', ReportesContabilidad+'ConEdoRes.php'],
      ['Mayor General', ReportesContabilidad+'ConMayGen.php'],
      ['Mayor Analítico', ReportesContabilidad+'ConMayAna.php'],
      ['Comprobante Individual', ReportesContabilidad+'Comprobante.php'],
      ['Flujo de Caja', ReportesContabilidad+'conrflucaj.php'],
    ],
      ],
  ]
];



 var TREE_ITEMSCOM_ALM = [
  ['SIGA', null,
    ['Compras y Almacen', null,
      ['Proveedores', null,
        ['Definición de Grupos de Recaudos', 'proveedores/AlmTipRecPro.htm'],
        ['Definición de Recaudos', 'proveedores/AlmRegRec.htm'],
        ['Registro de Proveedores', 'proveedores/AlmRegPro.htm'],
        ['Definición de Condiciones de Pago', 'proveedores/AlmConPag.htm'],
        ['Definición de Formas de Entrega', 'proveedores/AlmForEnt.htm'],
        ['Definición de Razones de Compra', 'proveedores/AlmRazCom.htm'],
        ['Definición de Rangos de Cotizaciones', 'proveedores/AlmDefCot.htm'],
      ],
      ['Artículos', null,
        ['Definición de Artículos', 'articulos/AlmDefArt.htm'],
        ['Definición de Ubicaciones', 'articulos/AlmDefUbi.htm'],
        ['Ramos de Artículos', 'articulos/AlmRamArt.htm'],
        ['Registro de Artículos y/o Servicios', 'articulos/AlmRegArt.htm'],
        ['Registro de Recargos', 'articulos/AlmRegRgo.htm'],
        ['Asociación de Retenciones a Servicios', 'articulos/AlmRetSer.htm'],
      ],
      ['Compras', null,
        ['Ordenes de Compra y/o Servicio', 'compras/AlmOrdCom.htm'],
        ['Registro de Contratos', 'compras/AlmContrato.htm'],
        ['Ajuste a Ordenes de Compra', 'compras/AlmAjuOC.htm'],
        ['Cotizaciones', '#'],
        ['Asignación de Prioridad a Cotizaciones', 'compras/AlmPriori.htm'],

      ],
      ['Almacen',null,
        ['Definiciones Generales', 'almacen/AlmDefAlm.htm'],
        ['Requisiciones', 'almacen/AlmReq.htm'],
        ['Recepción de Productos Terminados', 'almacen/AlmOrdRecTer.htm'],
        ['Requisiciones de Servicios', 'almacen/AlmReqSer.htm'],
        ['Requisiciones por Departamento (Solicitud de Egresos)', 'almacen/AlmSolEgr.htm'],
        ['Despachos', 'almacen/AlmDesp.htm'],
        ['Despacho de Servicios', 'almacen/AlmDespSer.htm'],
        ['Despachos con Pistola', 'almacen/AlmDespPist.htm'],
        ['Recepción de Artículo', 'almacen/AlmOrdRec.htm'],
        ['Inventario Físico', 'almacen/AlmInvFis.htm'],
        ['Traspaso de Artículos', 'almacen/AlmTraAlm.htm'],
        ['Unidades para Despacho', 'almacen/per_01/per_01_01.htm'],

      ],

      ['Reportes', null,
        ['Generales',null,
          ['Catálogo de Artículos', '#'],
          ['Catálogo de Ramos', '#'],
          ['Catálogo de Proveedores', '#'],
          ['Catálogo de Unidades', '#'],
          ['Catálogo de Recaudos', '#'],
          ['Catálogo de Recargos', '#'],
          ['Ficha del Proveedor', '#'],
        ],
        ['Movimientos',null,
          ['Requisiciones', '#'],
          ['Recepciones', '#'],
          ['Despachos', '#'],
          ['Ordenes de Compra y/o Servicio', '#'],
          ['Recepciones y Diferencias', '#'],
          ['Despachos y Diferencias', '#'],
          ['Resumen de Movimientos', '#'],

        ],
        ['Formas Preimpresas',null,
          ['Etiquetas de Articulos', '#'],
          ['Requisiciones', '#'],
          ['Solicitud de Autorización de Egreso', '#'],
          ['Recepciones', '#'],
          ['Despachos', '#'],
          ['Ordenes de Compra y/o Servicio', '#'],
          ['Constancia de Inscripción Provisional De Proveedores', '#'],
          ['Etiquetas de Barras', '#'],
        ],
        ['Almacén', null,
          ['Valorización de Inventario', '#'],
          ['Relación Inventario Almacén', '#'],
          ['Hoja de Conteo Físico', '#'],
          ['Inventario Físico Valorado', '#'],
          ['Stock Máximo', '#'],
          ['Stock Mínimo', '#'],
          ['Punto de Reorden', '#'],
        ],
      ],
      ['Mantenimiento', null,
        ['Clasificador de Partidas Presupuestarias', '#'],
        ['Traspaso de Inventario Fisico a Lógico', '#'],
        ['Importar Productos', '#'],
        ['Actualizar Precios y Existencias', '#'],
        ['Cambiar Password de Usuario', '#'],
      ],
    ],
  ],
];

var TREE_ITEMSNOM = [
  ['SIGA', null,
    ['Nomina', null,
      ['Reportes', null,
        ['Definiciones Especificas',null,
          ['Tipos Nóminas', '#'],
          ['Conceptos', '#'],
          ['Conceptos por Nómina', '#'],
          ['Niveles Organizacionales', '#'],
          ['Cargos', '#'],
          ['Bancos', '#'],
          ['Categorias Presupuestarias', '#'],
          ['Municipios', '#'],
        ],
        ['Personal',null,
          ['Datos Personales', '#'],
          ['Asignación de Cargos', '#'],
        ],
        ['N&oacute;mina',null,
          ['Listado de Nomina Definitiva por Categoría', '#'],
          ['Listado de Nomina Definitiva por Categoría y Tipo de Gasto', '#'],
          ['Listado de Nomina Definitiva por Nivel', '#'],
          ['Listado de Nómina para la Firma por Categoría', '#'],
          ['Listado de Nómina para la Firma por Categoría y Tipo de Gasto', '#'],
          ['Listado de Nómina para la Firma por Nivel', '#'],
          ['Recibos de Pago', '#'],
          ['Relación de Conceptos', '#'],
          ['Relación de Nómina/Presupuesto', '#'],
          ['Relación de Nómina/Presupuesto por Tipo de Gasto', '#'],
          ['Disponibilidad Presupuestaria por Nómina', '#'],
          ['Recibo Tipo A', '#'],
          ['Relación Depósito Banco', '#'],
          ['Relación Cuentas Bancarias Nómina', '#'],
          ['Variaciones de Nóminas por Períodos', '#'],
          ['Relación Categorias/Conceptos', '#'],
          ['Desglose de Nómina', '#'],
          ['Histórico de Conceptos', '#'],
          ['Histórico de Nómina/Presupuesto', '#'],
          ['Cálculo de Conceptos', '#'],
          ['Listado Por Conceptos', '#'],
          ['Listado Por Conceptos Historicos', '#'],
        ],
        ['Prestaciones', null,
          ['Antiguedad Prestaciones Sociales Nuevo Régimen', '#'],
          ['Antiguedad Prestaciones Sociales Antiguo Régimen', '#'],
          ['Anticipos sobre Prestaciones Sociales', '#'],
          ['Compensación Bono Transferencia', '#'],
          ['Intereses sobre Prestaciones Sociales Nuevo Régimen', '#'],
          ['Intereses sobre Prestaciones Sociales Viejo Régimen', '#'],
          ['Liquidación de Cuentas', '#'],
        ],
        ['Vacaciones', null,
          ['Solicitud de Vacaciones', '#'],
          ['Histórico de Vacaciones Disfrutadas por Empleado', '#'],
          ['Relación de Vacaciones Disfrutadas por Empleado en Lote', '#'],
          ['Relación de Vacaciones Procesadas', '#'],
        ],
      ],
    ],
  ]
];