<?php
// auto-generated by PropelCidesa
// date: 2009/02/06 20:02:24
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Ajustes',
array()) ?></h1>


<div id="sf_admin_header">
<?php include_partial('faajuste/edit_header', array('faajuste' => $faajuste, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('faajuste/edit_messages', array('faajuste' => $faajuste, 'labels' => $labels)) ?>
<?php include_partial('faajuste/edit_form', array('faajuste' => $faajuste, 'labels' => $labels, 'obj' => $obj)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('faajuste/edit_footer', array('faajuste' => $faajuste, 'labels' => $labels)) ?>
</div>

</div>
