<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/18 15:10:57
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'almregart/list?id='.$caregart->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
  'form' => 'sf_admin_edit_form'
)) ?></li>
  <li><?php echo submit_tag(__('save and add'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
