<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/09 12:35:50
?>
<?php echo form_tag('facpicsollic/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php use_helper('Grid'); ?>
<?php use_helper('Javascript') ?>
<?php use_helper('PopUp') ?>
<?php echo javascript_include_tag('dFilter') ?>
<?php echo javascript_include_tag('ajax') ?>
<?php echo javascript_include_tag('tools') ?>

<?php echo object_input_hidden_tag($fcsollic, 'getId') ?>
<?php use_helper('tabs') ?>
<fieldset><legend><strong>Solicitud de Licencia</strong></legend>

<div class="form-row"><?php echo label_for('fcsollic[numsol]', __($labels['fcsollic{numsol}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{numsol}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{numsol}')): ?> <?php echo form_error('fcsollic{numsol}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNumsol', array (
  'size' => 20,
  'control_name' => 'fcsollic[numsol]',
  )); echo $value ? $value : '&nbsp;' ?><?php echo button_to_popup('...','generales/catalogo?clase=Fcsollic&frame=sf_admin_edit_form&obj1=fcsollic_numsol')?></div>

<br>

<?php echo label_for('fcsollic[fecsol]', __($labels['fcsollic{fecsol}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{fecsol}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{fecsol}')): ?> <?php echo form_error('fcsollic{fecsol}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getFecsol', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[fecsol]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>
</fieldset>
<fieldset><legend><strong>Datos del Contribuyente</strong></legend>

<div class="form-row"><?php echo label_for('fcsollic[rifcon]', __($labels['fcsollic{rifcon}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{rifcon}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{rifcon}')): ?> <?php echo form_error('fcsollic{rifcon}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getRifcon', array (
  'size' => 20,
  'control_name' => 'fcsollic[rifcon]',
  )); echo $value ? $value : '&nbsp;' ?><?php echo button_to_popup('...','generales/catalogo?clase=Fcconrep&frame=sf_admin_edit_form&obj1=fcsollic_rifcon&obj2=fcsollic_nomcon&obj3=fcsollic_dircon')?>
</div>

<br>

<?php echo label_for('fcsollic[nomcon]', __($labels['fcsollic{nomcon}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nomcon}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nomcon}')): ?> <?php echo form_error('fcsollic{nomcon}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNomcon', array (
  'size' => 80,
  'control_name' => 'fcsollic[nomcon]',
)); echo $value ? $value : '&nbsp;' ?></div>

<br>

<?php echo label_for('fcsollic[dircon]', __($labels['fcsollic{dircon}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{dircon}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{dircon}')): ?> <?php echo form_error('fcsollic{dircon}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDircon', array (
'size' => 80,
  'control_name' => 'fcsollic[dircon]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

</fieldset>

<fieldset><legend><strong>Datos del Representante Legal</strong></legend>
<div class="form-row"><?php echo label_for('fcsollic[nacconrep]', __($labels['fcsollic{nacconrep}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nacconrep}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nacconrep}')): ?> <?php echo form_error('fcsollic{nacconrep}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

<?php if($fcsollic->getNacconrep()=='V') $val = true; else $val=false; ?>
<?php echo "Venezolano ".radiobutton_tag('fcsollic[nacconrep]', 'V', $val, 'disabled=true') ?>&nbsp;
<?php echo "Extranjero ".radiobutton_tag('fcsollic[nacconrep]', 'E', !$val, 'disabled=true') ?>

<?php /*$value = object_input_tag($fcsollic, 'getNacconrep', array (
'disabled' => true,
'control_name' => 'fcsollic[nacconrep]',
)); echo $value ? $value : '&nbsp;' */?>

</div>

<br>

<?php echo label_for('fcsollic[rifrep]', __($labels['fcsollic{rifrep}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{rifrep}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{rifrep}')): ?> <?php echo form_error('fcsollic{rifrep}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getRifrep', array (
'size' => 20,
'control_name' => 'fcsollic[rifrep]',
)); echo $value ? $value : '&nbsp;' ?><?php echo button_to_popup('...','generales/catalogo?clase=Fcconrep&frame=sf_admin_edit_form&obj1=fcsollic_rifrep&obj2=fcsollic_nomconrep&obj3=fcsollic_dirconrep')?>
</div>

<br>

<?php echo label_for('fcsollic[nomconrep]', __($labels['fcsollic{nomconrep}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nomconrep}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nomconrep}')): ?> <?php echo form_error('fcsollic{nomconrep}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNomconrep', array (
  'disabled' => true,
  'size' => 80,
  'control_name' => 'fcsollic[nomconrep]',
)); echo $value ? $value : '&nbsp;' ?></div>

<br>

<?php echo label_for('fcsollic[dirconrep]', __($labels['fcsollic{dirconrep}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{dirconrep}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{dirconrep}')): ?> <?php echo form_error('fcsollic{dirconrep}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDirconrep', array (
  'disabled' => true,
  'size' => 80,
  'control_name' => 'fcsollic[dirconrep]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>




</fieldset>
<?php tabMainJS("tp1","tabPane1", "tabPage1", 'Datos Establecimiento');?>
<fieldset>






<div class="form-row"><?php echo label_for('fcsollic[nomneg]', __($labels['fcsollic{nomneg}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nomneg}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nomneg}')): ?> <?php echo form_error('fcsollic{nomneg}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNomneg', array (
  'size' => 80,
  'control_name' => 'fcsollic[nomneg]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[dirpri]', __($labels['fcsollic{dirpri}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{dirpri}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{dirpri}')): ?> <?php echo form_error('fcsollic{dirpri}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDirpri', array (
  'size' => 80,
  'control_name' => 'fcsollic[dirpri]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[tipinm]', __($labels['fcsollic{tipinm}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{tipinm}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{tipinm}')): ?> <?php echo form_error('fcsollic{tipinm}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getTipinm', array (
  'size' => 20,
  'control_name' => 'fcsollic[tipinm]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[catcon]', __($labels['fcsollic{catcon}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{catcon}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{catcon}')): ?> <?php echo form_error('fcsollic{catcon}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getCatcon', array (
  'size' => 30,
  'control_name' => 'fcsollic[catcon]',
  )); echo $value ? $value : '&nbsp;' ?> <?php echo button_to_popup('...','generales/catalogo?clase=Fcreginm&frame=sf_admin_edit_form&obj1=fcsollic_catcon&obj2=fcsollic_nomcatrasto')?>
</div>
</div>
<div class="form-row"><?php echo label_for('fcsollic[nomcatrasto]', __($labels['fcsollic{nomcatrasto}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nomcatrasto}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nomcatrasto}')): ?> <?php echo form_error('fcsollic{nomcatrasto}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNomcatrasto', array (
  'disabled' => true,
  'control_name' => 'fcsollic[nomcatrasto]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[tipest]', __($labels['fcsollic{tipest}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{tipest}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{tipest}')): ?> <?php echo form_error('fcsollic{tipest}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getTipest', array (
  'size' => 20,
  'control_name' => 'fcsollic[tipest]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[codrut]', __($labels['fcsollic{codrut}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{codrut}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{codrut}')): ?> <?php echo form_error('fcsollic{codrut}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getCodrut', array (
  'size' => 20,
  'control_name' => 'fcsollic[codrut]',
  )); echo $value ? $value : '&nbsp;' ?><?php echo button_to_popup('...','generales/catalogo?clase=Fcrutas&frame=sf_admin_edit_form&obj1=fcsollic_codrut&obj2=fcsollic_nomruta')?>
</div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[nomruta]', __($labels['fcsollic{nomruta}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{nomruta}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{nomruta}')): ?> <?php echo form_error('fcsollic{nomruta}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getNomruta', array (
'disabled' => true,
'control_name' => 'fcsollic[nomruta]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>


</fieldset>



<?php tabPageOpenClose("tp1", "tabPage2", 'Distancias Cercanas');?>

<fieldset>

<div class="form-row"><?php echo label_for('fcsollic[disbar]', __($labels['fcsollic{disbar}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{disbar}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{disbar}')): ?> <?php echo form_error('fcsollic{disbar}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDisbar', array (
  'size' => 7,
  'control_name' => 'fcsollic[disbar]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[disins]', __($labels['fcsollic{disins}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{disins}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{disins}')): ?> <?php echo form_error('fcsollic{disins}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDisins', array (
  'size' => 7,
  'control_name' => 'fcsollic[disins]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[discli]', __($labels['fcsollic{discli}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{discli}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{discli}')): ?> <?php echo form_error('fcsollic{discli}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDiscli', array (
  'size' => 7,
  'control_name' => 'fcsollic[discli]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[disfun]', __($labels['fcsollic{disfun}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{disfun}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{disfun}')): ?> <?php echo form_error('fcsollic{disfun}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDisfun', array (
  'size' => 7,
  'control_name' => 'fcsollic[disfun]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[disdis]', __($labels['fcsollic{disdis}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{disdis}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{disdis}')): ?> <?php echo form_error('fcsollic{disdis}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDisdis', array (
  'size' => 7,
  'control_name' => 'fcsollic[disdis]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[disest]', __($labels['fcsollic{disest}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{disest}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{disest}')): ?> <?php echo form_error('fcsollic{disest}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getDisest', array (
  'size' => 7,
  'control_name' => 'fcsollic[disest]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>


</fieldset>



<?php tabPageOpenClose("tp1", "tabPage3", 'Horarios de Trabajo');?>

<fieldset>


<div class="form-row"><?php echo label_for('fcsollic[horini]', __($labels['fcsollic{horini}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{horini}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{horini}')): ?> <?php echo form_error('fcsollic{horini}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getHorini', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[horini]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[horcie]', __($labels['fcsollic{horcie}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{horcie}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{horcie}')): ?> <?php echo form_error('fcsollic{horcie}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getHorcie', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[horcie]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>


</fieldset>



<?php tabPageOpenClose("tp1", "tabPage4", 'Ejercicio Económico');?>

<fieldset>


<div class="form-row"><?php echo label_for('fcsollic[fecini]', __($labels['fcsollic{fecini}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{fecini}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{fecini}')): ?> <?php echo form_error('fcsollic{fecini}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getFecini', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[fecini]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[fecfin]', __($labels['fcsollic{fecfin}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{fecfin}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{fecfin}')): ?> <?php echo form_error('fcsollic{fecfin}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getFecfin', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[fecfin]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>



</fieldset>



<?php tabPageOpenClose("tp1", "tabPage5", 'Recepción Solicitud');?>

<fieldset>


<div class="form-row"><?php echo label_for('fcsollic[capsoc]', __($labels['fcsollic{capsoc}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{capsoc}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{capsoc}')): ?> <?php echo form_error('fcsollic{capsoc}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getCapsoc', array (
  'size' => 7,
  'control_name' => 'fcsollic[capsoc]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[funres]', __($labels['fcsollic{funres}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{funres}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{funres}')): ?> <?php echo form_error('fcsollic{funres}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fcsollic, 'getFunres', array (
  'size' => 60,
  'control_name' => 'fcsollic[funres]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fcsollic[fecres]', __($labels['fcsollic{fecres}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fcsollic{fecres}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fcsollic{fecres}')): ?> <?php echo form_error('fcsollic{fecres}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_date_tag($fcsollic, 'getFecres', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcsollic[fecres]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

</fieldset>


<?php tabPageOpenClose("tp1", "tabPage5", 'Act. Comer.');?>

<fieldset>


<form name="form1" id="form1">
<?
	echo grid_tag($obj);
?>
</form>
</fieldset>
<?php tabInit();?> <?php include_partial('edit_actions', array('fcsollic' => $fcsollic)) ?>

</form>

<ul class="sf_admin_actions">
	<li class="float-left"><?php if ($fcsollic->getId()): ?> <?php echo button_to(__('delete'), 'facpicsollic/delete?id='.$fcsollic->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?></li>
</ul>