set search_path to "SIMA002";

///// IMPORTANTE
///// VERIFICAR QUE LA TABLA FORDEFEGRGEN TENGA REGISTRO///
/////

update FORDEFEGRGEN set corequ = 5;

UPDATE FORDEFEGRGEN SET CORSEC = 15;

UPDATE FORDEFEGRGEN SET COREST = 24;
