<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/16 09:30:03
?>
<?php echo form_tag('almregrec/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($carecaud, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('carecaud[codrec]', __($labels['carecaud{codrec}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{codrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{codrec}')): ?>
    <?php echo form_error('carecaud{codrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($carecaud, 'getCodrec', array (
  'size' => 20,
  'control_name' => 'carecaud[codrec]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('carecaud[desrec]', __($labels['carecaud{desrec}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{desrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{desrec}')): ?>
    <?php echo form_error('carecaud{desrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($carecaud, 'getDesrec', array (
  'size' => 80,
  'control_name' => 'carecaud[desrec]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('carecaud[limrec]', __($labels['carecaud{limrec}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{limrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{limrec}')): ?>
    <?php echo form_error('carecaud{limrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

	<?php if($carecaud->getLimrec()=='S') $e=true; else $e=false; ?>
	Si
	<?php echo radiobutton_tag('estado', 'S', $e) ?>
	No
	<?php echo radiobutton_tag('estado', 'N', !$e) ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('carecaud[canutr]', __($labels['carecaud{canutr}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{canutr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{canutr}')): ?>
    <?php echo form_error('carecaud{canutr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($carecaud, 'getCanutr', array (
  'size' => 7,
  'control_name' => 'carecaud[canutr]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('carecaud[codtiprec]', __($labels['carecaud{codtiprec}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{codtiprec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{codtiprec}')): ?>
    <?php echo form_error('carecaud{codtiprec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($carecaud, 'getCodtiprec', array (
  'size' => 20,
  'control_name' => 'carecaud[codtiprec]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('carecaud[observ]', __($labels['carecaud{observ}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('carecaud{observ}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('carecaud{observ}')): ?>
    <?php echo form_error('carecaud{observ}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($carecaud, 'getObserv', array (
  'size' => 80,
  'control_name' => 'carecaud[observ]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('carecaud' => $carecaud)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($carecaud->getId()): ?>
<?php echo button_to(__('delete'), 'almregrec/delete?id='.$carecaud->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
