<?php
// auto-generated by PropelCidesa
// date: 2008/10/12 18:10:33
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'oycadjobr/list?id='.$ocadjobr->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
      <li><?php echo button_to(__('create'), 'oycadjobr/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
