
var Compras = '/compras_dev.php/';
var Tesoreria= '/tesoreria_dev.php/';
var Nomina='/nomina_dev.php/';
var Ingresos='/ingresos_dev.php/';
var Formulacion='/formulacion_dev.php/';
var Obra_cont='/obra_cont_dev.php/';
var Inv_coloc='/inv_coloc_dev.php/';
var Cred_cobr='/cred_cobr_dev.php/';

var ReportesCompras='http://'+window.location.host+'/vb-libre/reportes/compras/';
var ReportesTesoreria='http://'+window.location.host+'/vb-libre/reportes/tesoreria/';
var ReportesNomina='http://'+window.location.host+'/vb-libre/reportes/nomina/';
var ReportesFormulacion='http://'+window.location.host+'/vb-libre/reportes/formulaciondemo/';
var servidor='http://'+window.location.host;

var TREE_ITEMSCOM_ALM = [
	['SIGA', null,
		['Compras y Almac&eacute;n', null,
			['Proveedores', null,
				['Definici&oacute;n de Grupos de Recaudos', Compras+'almtiprecpro'],
				['Definici&oacute;n de Recaudos', Compras+'almregrec'],
				['Registro de Proveedores', Compras+'almregpro'],
				['Definici&oacute;n de Condiciones de Pago', Compras+'almconpag'],
				['Definici&oacute;n de Formas de Entrega', Compras+'almforent'],
				['Definici&oacute;n de Razones de Compra', Compras+'almrazcom'],
				['Definici&oacute;n de Rangos de Cotizaciones', Compras+'almdefcot'],
				['Definici&oacute;n de Motivos de Faltantes', Compras+'almmotfal'],
				['Definici&oacute;n de Tipo de Entrada', Compras+'almtipent'],
				['Definici&oacute;n de Tipo de Salida', Compras+'almtipsal'],				
			],
			['Art&iacute;culos', null,
				['Definici&oacute;n de Art&iacute;culos', Compras+'almdefart'],
				['Definici&oacute;n de Ubicaciones', Compras+'almdefubi'],
				['Ramos de Art&iacute;culos', Compras+'almramart'],
				['Registro de Art&iacute;culos y+o Servicios', Compras+'almregart'],
				['Registro de Recargos', Compras+'almregrgo'],
				['Asociaci&oacute;n de Retenciones a Servicios', Compras+'almretser'],
				['Registro de Productos Terminados', Compras+'faexiart'],
				['Proyectos', Compras+'almtippro'],
			],
			['Compras', null,
				['Ordenes de Compra y+o Servicio', Compras+'almordcom'],
				['Registro de Contratos', Compras+'almcontrato'],
				['Ajuste a Ordenes de Compra', Compras+'almajuoc'],
				['Cotizaciones', Compras+'almcotiza'],
				['Asignaci&oacute;n de Prioridad a Cotizaciones', Compras+'almpriori'],
			],
			['Almacen',null,
				['Definiciones Generales', Compras+'almdefalm'],
				['Requisiciones', Compras+'AlmReq'],
				['Recepci&oacute;n de Productos Terminados', Compras+'almordrecter'],
				['Requisiciones de Servicios', Compras+'almreqser'],
				['Requisiciones por Departamento (Solicitud de Egresos)', Compras+'almsolegr'],
				['Despachos', Compras+'almdesp'],
				['Prestacion de Servicios', Compras+'almdespser'],								
				['Inventario F&iacute;sico', Compras+'alminvfis'],
				['Traspaso de Art&iacute;culos', Compras+'almtraalm'],
				['Recepcion de Ordenes de Compras', Compras+'almordrec'],
				['Salida de Almacen', Compras+'almsalalm'],
			],    
			['Reportes',null,
				['Generales',null,
					['Catálogo de Artículos', ReportesCompras+'carcatart.php'],
					['Catálogo de Ramos', ReportesCompras+'carramart.php'],
					['Catálogo de Proveedores', ReportesCompras+'carprovee.php'],
					['Catálogo de Unidades', ReportesCompras+'cardefalm.php'],
					['Catálogo de Recaudos', ReportesCompras+'carrecaud.php'],
					['Catálogo de Recargos', ReportesCompras+'carrecarg.php'],
					['Ficha del Proveedor', ReportesCompras+'carficpro.php'],
				],
				['Movimientos',null,
					['Requisiciones', ReportesCompras+'carreqart.php'],
					['Recepciones', ReportesCompras+'carrcpart.php'],
					['Despachos', ReportesCompras+'cardphart.php'],
					['Ordenes de Compra y/o Servicio', ReportesCompras+'cardetord.php'],
					['Recepciones y Diferencias', ReportesCompras+'carrcpord.php'],
					['Despachos y Diferencias', ReportesCompras+'carreqdph.php'],
					['Resumen de Movimientos', ReportesCompras+'carmovart.php'],
				],
				['Formas Preimpresas',null,
					['Etiquetas de Articulos', ReportesCompras+'caretique.php'],
					['Requisiciones', ReportesCompras+'carreqpre.php'],
					['Solicitud de Autorización de Egreso', ReportesCompras+'carsolegr.php'],
					['Recepciones', ReportesCompras+'carrcppre.php'],
					['Despachos', ReportesCompras+'cardphpre.php'],
					['Ordenes de Compra', ReportesCompras+'carordpre.php'],
					['Ordenes de Servicio', ReportesCompras+'carordser.php'],
					['Constancia de Inscripción Provisional De Proveedores', ReportesCompras+'carconinspro.php'],
				],
				['Almacén', null,
					['Relación Inventario Almacén', ReportesCompras+'carrelinvalm.php'],
					['Hoja de Conteo Físico', ReportesCompras+'carconfis.php'],
					['Inventario Físico Valorado', ReportesCompras+'carinvfis.php'],
					['Stock Máximo', ReportesCompras+'carstomax.php'],
					['Stock Mínimo', ReportesCompras+'carstomin.php'],
					['Punto de Reorden', ReportesCompras+'carptoreo.php'],
				],			
			],	                                                                                        
			['Mantenimiento', null,
				['Clasificador de Partidas Presupuestarias', Compras+'nommanclapre'],
				['Traspaso de Inventario Fisico a Logico', Compras+'almtrainv'],					
				['Importar Productos', Compras+'importarproducto'],					
				['Actualizar Precios y Existencias', Compras+'actualizarproducto'],					
			],
		],
	],
];

var TREE_ITEMS_TER = [
	['SIGA', null,
		['Tesorer&iacute;a', null,
			['Definiciones Espec&iacute;ficas', null,
				['Empresa', Tesoreria+'pagdefemp'],
				['Tipos de Cuentas Bancarias', Tesoreria+'tesdeftipcue'],
				['Tipos de Movimientos Bancarios', Tesoreria+'tesdeftipmov'],
				['Tipos de Rendimiento', Tesoreria+'tesdeftipren'],
				['Tipos de Monedas', Tesoreria+'tesdeftipmon'],
				['Tipos de Retenciones', Tesoreria+'pagtipret'],
				['Tipos de Financiamiento', Tesoreria+'pretipfin'],
				['Bancos', Tesoreria+'tesdefcueban'],
				['Tipos de Beneficiario', Tesoreria+'pagtipben'],				    
				['Beneficiarios', Tesoreria+'pagbenfic'],
				['Asociacion Conceptos+Tipos de Retenciones', Tesoreria+'pagretcon'],
				['Definici&oacute;n de Ubicaci&oacute;n', Tesoreria+'tesdesubi'],
				['Definici&oacute;n del Iva para Agentes de Retenci&oacute;n', Tesoreria+'pagretiva'],
				['Definici&oacute;n de Cuentas Contables para Rendici&oacute;n de Gastos', Tesoreria+'tesdefrengas'],
				['Definici&oacute;n de Reportes de Comprobantes de Retenci&oacute;n', Tesoreria+'pagrepret'],											
			],

			['Ordenamiento de Pago', null,
				['Ordenes de Pago', Tesoreria+'pagemiord'],
				['Fondos a Terceros', Tesoreria+'pagemiret'],
				['Enterar Retenci&oacute;n de ISLR', Tesoreria+'tesretislr'],
			],
			['Bancos', null,
				['Emision de Cheques', Tesoreria+'tesmovemiche'],
				['Movimientos seg&uacute;n Libros', Tesoreria+'tesmovseglib'],
				['Movimientos seg&uacute;n Libros A&ntilde;os Anteriores', Tesoreria+'tesmovseglib'],
				['Movimientos seg&uacute;n Bancos', Tesoreria+'tesmovsegbanant'],
				['Movimientos seg&uacute;n Bancos A&ntilde;os Anteriores', Tesoreria+'tesmovsegbanant'],
				['Transferencias Bancarias', Tesoreria+'tesmovtraban'],
				['Conciliaci&oacute;n', Tesoreria+'tesmovconban'],
				['Cierre de Per&iacute;odo', Tesoreria+'tesmovcieban'],
			],
			['Caja', null,
				['Cheques en Custodia', Tesoreria+'teschecus'],
			],
			['Reportes', null,
				['Generales',  null,
				 	['Tipos de Cuentas Bancarias', ReportesTesoreria+'tsrtipcue.php'],
					['Tipos de Movimientos Bancarios', ReportesTesoreria+'TSRTIPMOV.php'],
					['Tipos de Retenciones', ReportesTesoreria+'OPRTIPRET.php'],
					['Beneficiarios', ReportesTesoreria+'OPRBENEFI.php'],
				 ],
				['Ordenamiento de Pago', null,
				 	['Orden de Pago Preimpresa', ReportesTesoreria+'OPRORDPRE_NEW.php'],
					['Orden de Pago Preimpresa para Nómina', ReportesTesoreria+'OPRORDPRE_NOMINA.php'],
					['Orden de Pago Tipo Anulación Preimpresa', ReportesTesoreria+'OPRORDPREANU.php'],
					['Ordenes de Pagos con Retenciones', ReportesTesoreria+'OPRORDRET.php'],
					['Consulta de Ordenes por Ticket', ReportesTesoreria+'OPRORDPAGSTATUS.php'],
					['Relación Anexa', ReportesTesoreria+'OPRRELANEX.php'],
					['Relación Anexa de Anulación', ReportesTesoreria+'OPRRELANEX_ANU.php'],
					['Relación Anexa Ordenes Permanentes', ReportesTesoreria+'TSRRELANEOPP.php'],
					['Relación de Ordenes de Pago por Código Presupuestario',ReportesTesoreria+'OPRORDEMITIDASPARTIDAS.php'],
					['Listado de Ordenes de Pago', ReportesTesoreria+'OPRORDPAG.php'],
					['Listado de Ordenes de Pago Efectivas', ReportesTesoreria+'OPRORDPAGEFEC.php'],
					['Listado de Ordenes de Pago Efectivas por Beneficiario y status', ReportesTesoreria+'OPRORDPAGBEN_STA.php'],
					['Listado de Ordenes de Pago Efectivas (por Status con fecha de envío)', ReportesTesoreria+'OPRORDPAGEFEC_STA_FEC.php'],
					['Listado de Ordenes de Pago Anuladas', ReportesTesoreria+'OPRORDPAGANU.php'],
					['Listado de Ordenes de Pago Detallada', ReportesTesoreria+'OPRDETORD.php'],
					['Listado de Ordenes de Pago de Tipo Anulación', ReportesTesoreria+'OPRDETORDANU.php'],
					['Listado de Ordenes de Pago Anulada y Tipo Anulación', ReportesTesoreria+'OPRDETORD_ANULACION_DEFINITIVA.php'],
					['Listado de Ordenes de Pago Enviadas a Contraloría', ReportesTesoreria+'OPRORDENVCONT.php'],
					['Histórico de Ordenes de Pago Enviadas a Finanzas', ReportesTesoreria+'OPRORDENVFIN_SINTMP.php'],
					['Último listado de Envio a Finanzas', ReportesTesoreria+'OPRORDENVFIN.php'],
					['Histórico de Ordenes de Pago Enviadas al Despacho', ReportesTesoreria+'OPRORDENVDES_SINTMP.php'],
					['Último listado de Envio al Despacho', ReportesTesoreria+'OPRORDPAGDES_VIS.php'],
					['Autorización de Pago FIDES', ReportesTesoreria+'OPRAUTPAG.php'],
					['Autorización de Pago FIDES (Retención)', ReportesTesoreria+'OPRAUTPAG_RETENC.php'],
					['Oficio Autorización de Pago FIDES', ReportesTesoreria+'OPROFIAUTPAG.php'],
					['Retenciones Pagadas y Pendientes por Pagar', ReportesTesoreria+'TSFONTER.php'],
				 ],
				 ['Bancos', null,
				  	['Bancos', ReportesTesoreria+'TSRDEFBAN.php'],
					['Disponibilidad Bancaria', ReportesTesoreria+'TSRDISBAN.php'],
					['Relación de Cuentas Bancarias', ReportesTesoreria+'TSRRELBAN.php'],
					['Movimientos según Libros por Banco', ReportesTesoreria+'TSRMOVLIBBAN.php'],
					['Movimientos según Libros por Banco(Cheques Anulados)', ReportesTesoreria+'TSRMOVLIBBANCHQ.php'],
					['Movimientos según Bancos', ReportesTesoreria+'TSRMOVBAN.php'],
					['Movimientos según Bancos por Banco', ReportesTesoreria+'TSRMOVBANBAN.php'],
					['Detalle de Conciliación', ReportesTesoreria+'TSRRESCON.php'],
					['Conciliación Bancaria', ReportesTesoreria+'TSRCONCIL.php'],
					['Transferencias Bancarias', ReportesTesoreria+'TSRTRABAN.php'],
					['Oficio para Autorización a Transferencias Bancarias (R)', ReportesTesoreria+'OPRtransferencia.php'],
					['Oficio para Abono a Ordenes de Pago Permanentes (R)', ReportesTesoreria+'OPRABOORDPAGPER.php'],
					['Saldo de Cuentas Bancarias', ReportesTesoreria+'TSRSALCTABAN.php'],
				  ],
				  ['Caja', null,
					['Relación de Ordenes de Pago Entregadas', ReportesTesoreria+'TSRCHEENT.php'],
					['Ordenes de Pago por Crédito', ReportesTesoreria+'OPRORDPAGEFEC_CRED.php'],
					['Movimiento de Pagado por Cuenta y Fechas', ReportesTesoreria+'TSRRELORDPAG.php'],
					['Listado para solicitar pago I.S.L.R', ReportesTesoreria+'TSRISLR.php'],
				 ],
				 ['Control de Ordenes de Pago de Tesoreria', null,
					['Relación de Ordenes de Pago en Caja por Categoría Programática', ReportesTesoreria+'TSRRELORDCAJ_CAT.php'],
					['Relación de Ordenes de Pago en Caja por Cat Prog con Dirección Beneficiario', ReportesTesoreria+'TSRRELORDCAJ_CAT_DIR.php'],
					['Relación de Ordenes de Pago en Caja por Cat Prog con Dir. Beneficiarios jurídicos', ReportesTesoreria+'TSRRELORDCAJ_CAT_DIR_JUR.php'],
					['Resúmen  de Ordenes de Pago Pendientes por Abono', ReportesTesoreria+'TSRRESORDPAGPENABO.php'],
					['Relación de Ordenes de Pago Pendientes por Abono Detallada', ReportesTesoreria+'TSRORDPAGPENABO.php'],
					['Resúmen de Ordenes de Pago Permanentes (TODAS)', ReportesTesoreria+'TSRRESORDPAGPER.php'],
					['Relación  de Ordenes de Pago Permanentes Detallada (TODAS)', ReportesTesoreria+'TSRORDPAGPER.php'],
					['Ordenes de Pago Canceladas por Beneficiario', ReportesTesoreria+'OPROPCANBEN.php'],
					['Ordenes de Pago en Custodia por Beneficiario', ReportesTesoreria+'OPROPCUSBEN.php'],
					['Ordenes de Pago Canceladas por Sector', ReportesTesoreria+'OPROPCANSEC.php'],
					['Ordenes de Pago en Custodia por Sector', ReportesTesoreria+'OPROPCUSSEC.php'],
					['Ordenes de Pago Canceladas por Contratos entre Fechas', ReportesTesoreria+'OPROPCONCANFEC.php'],
					['Ordenes de Pago en Custodia por Contratos entre Fechas', ReportesTesoreria+'OPROPCONCUSFEC.php'],
					['Ordenes de Pago Permanentes Canceladas', ReportesTesoreria+'TSROPPFECPAG.php'],
				],
				['Fondos en Avance', null,
				 	['Ficha Beneficiario', ReportesTesoreria+'TSRBENFONAVA.php'],
					['Relación de Apartados', ReportesTesoreria+'TSRAPAFONAVA.php'],
					['Cheque Preimpreso', ReportesTesoreria+'tsrvoucher1.php'],
				],
				['Impuestos', null,
				 	['Comprobante de retención IVA', ReportesTesoreria+'OPRCOMPRET_IVA.php'],
					['Comprobante de retención ISLR', ReportesTesoreria+'OPRCOMPRET_ISLR.php'],
					['Comprobante de retención LTF', ReportesTesoreria+'OPRCOMPRET_LTF.php'],
					['Libro de Compras', ReportesTesoreria+'TSRLIBCOM.php'],
					['Listado de Retenciones Enteradas', ReportesTesoreria+'OPRRELRETENT.php'],
					['Listado de Ordenes de Pago Enteradas', ReportesTesoreria+'OPRORDPAGENT.php'],				
				],			
			],
			['Mantenimiento', null,
				['Eliminar Movimiento seg&uacute;n Libros Anulados', 'mantenimiento+man_01.htm'],
				['Actualizar Monto de Retenciones por Orden', Tesoreria+'pagmodret'],
			],
		],
	]
];

var TREE_ITEMS_NOM = [
	['SIGA', null,
		['Nomina y Personal', null,
			['Definiciones espec&iacute;ficas', null,
				['Institucion', Nomina+'NomDefEspGen'],
				['Tipos Nominas', Nomina+'NomDefEspTipNom'],
				['Conceptos', Nomina+'NomDefEspCon'],
				['Niveles Organizacionales', Nomina+'NomDefEspNivOrg'],
				['Cargos', Nomina+'NomDefEspCar'],
				['Definicion de Conceptos Variables', Nomina+'NomDefEspMovPer'],
				['Variables', Nomina+'NomDefEspVar'],
				['Bancos', Nomina+'NomDefEspBan'],
				['Profesiones', Nomina+'NomDefEspProFes'],
				['Perfiles', Nomina+'NomDefEspPerFil'],
				['Tipos de Parientes', Nomina+'NomDefEspPar'],
				['Guarderias', Nomina+'NomDefEspGuarde'],
				['Tipos de Gastos', Nomina+'NomDefTipGas'],
				['Motivos de Faltas y/o Permisos', Nomina+'NomDefEspMotFalPre'],
				['Definicion de Condicion Contractual', Nomina+'NomDefEspGruLab'],
				['Conceptos para Reportes', Nomina+'NomDefEspConSue'],
				['Conceptos para el Salario Integral', Nomina+'NomConceptosSalarioIntegral'],
				['Conceptos para el Sueldo', Nomina+'NomConceptosSueldo'],
				['Conceptos para las Primas', Nomina+'NomConceptosPrimas'],
				['Conceptos de Compensacion por Nomina', Nomina+'NomConceptosCompensacion'],
				['Conceptos de Ahorro Habitacional', Nomina+'NomDefConAho'],
				['Conceptos para el Fondo de Jubilacion y Pensiones', Nomina+'NomDefConFon'],
				['Definicion de Jornadas Laborales', Nomina+'NomJorLabLot'],
				['Jornadas Laborales por Empleado', Nomina+'NomJorLabInd'],
				['Definicion de Concepto de Cesta Tickets', Nomina+'NomDefEspCesTic'],
				['Tipos de Retiros', Nomina+'NomDefTipRet'],
				['Definicion de Conceptos para Dias Adicionales', Nomina+'NomDefDiaAdicNom'],
				['Conceptos para el ISLR', Nomina+'NomDefEspISLR'],
				['Definicion de Retenciones y Aportes', null,
					['Retenciones y Aportes', Nomina+'NomDefAportes'],
					['Conceptos para Aportes', Nomina+'NomDefConAportes'],
					['Conceptos para Retenciones', Nomina+'NomDefConRetencion'],
				],
				['Division Territorial', null,
					['Estados', Nomina+'NomDefEspPai'],
				],	
			],
			['Personal', null,
				['Datos Personales', Nomina+'NomHojInt'],
				['Tipo de Cargos', Nomina+'NomTipCar'],
				['Tipo de Dedicacion', Nomina+'NomTipDed'],
				['Tabla de Sueldos por Grado y Paso', Nomina+'NomComOCP'],
				['Asignacion de Cargos y Conceptos a Empleados', Nomina+'NomAsiCarConNom'],
				['Asignacion de Cargos a Empleados en lote', Nomina+'NomAsiCarEmpLot'],
				['Cambio de Cargos a Empleados', Nomina+'CambioDeCargos'],
			],
			['Archivo de elegibles',Nomina+'NomHojInt'],
			['Faltas y/o Permisos', null,
				['Permisos', Nomina+'NomFalPerPer'],
				['Salidas', Nomina+'NomFalPerSal'],
				['Llegadas', Nomina+'NomFalPerLle'],
				['Registro de Dias Extras', Nomina+'NomDiaExt'],
				['Registro de Faltas y/o Permisos Por Nomina en Lote', Nomina+'NomFalPerLot'],
				['Registro de Dias Extras Por Nomina en Lote', Nomina+'NomDiaExtLabLot'],
			],
			['Vacaciones', null,
				['Parametros para el Registro y Control de Vacaciones', Nomina+'VacDefGen'],
				['Definicion de Bono Vacacional y Jornada Laboral', Nomina+'VacDiasBonoVac'],
				['Tabla para los Dias de Disfrute', Nomina+'VacDiaDis'],
				['Tabla para los Dias Feriados', Nomina+'VacDiaFer'],
				['Registro de Vacaciones Disfrutadas', Nomina+'VacHistorico'],
				['Registro de Vacaciones Disfrutadas en Lote', Nomina+'VacHistorico_Lote'],
				['Registro de Solicitud de Vacaciones', Nomina+'VacSALIDAS'],
				['Registro y Control de Vacaciones', Nomina+'VacRegSalVac'],
				['Liquidacion de Vacaciones Por Egreso', Nomina+'VacLiquidacion'],
			],
			['Prestaciones', null,
				['Definicion de Parametros para las Prestaciones Sociales',null,
				     ['Tipos de Contratos Colectivos', Nomina+'PresNomTipCon'],
				     ['Registro de Tipos de Asignaciones', Nomina+'presNomAsiConPre'],
				     ['Definicion Presupuestaria de Liquidacion', Nomina+'presNomDefPre'],
				],
				['Registros Utiles para el Calculo de Prestaciones Sociales',null,
				     ['Asignacion de Trabajadores para Prestaciones  Por Contrato Colectivo', Nomina+'presNomAsiTrabCont'],
				     ['Registro de Tasas de Interes Periodicas', Nomina+'presNomIntFecRef'],
				     ['Registro de Salario Integral por Contrato', Nomina+'presNomRegSalInt'],
				     ['Registro de Salario Integral por Contrato Individual', Nomina+'presNomRegSalIntInd'],
				],
				['Registro Historico de Anticipos Otorgados', Nomina+'PresNomRegHisAntPre'],
				['Solicitud de Anticipo Sobre Prestaciones', Nomina+'PresNomAntPre'],
				['Calculo de Prestaciones Sociales', Nomina+'presNomCalIntPre'],
				['Liquidacion Final de Prestaciones', Nomina+'PresNomLiquidacion'],
				['Importar Datos Prestaciones Sociales', Nomina+'ImportarPrestaciones'],
			],
			['Asignaciones Generales para el Calculo de Nomina', null,
				['Asignacion de Conceptos por Categoria Presupuestaria Especiales', Nomina+'AsignarConceptosCategorias'],
				['Asignacion de Conceptos a Nomina', Nomina+'AsignarConceptosNomina'],
				['Asignacion de Cargos a Nomina', Nomina+'NomDefEspAsiCarTipNomLot'],
				['Asignacion de Conceptos a Empleados', Nomina+'NomNomAsiConNom'],
				['Asignacion de Cuentas Bancarias por Empleado', Nomina+'EmpleadosBanco'],
				['Activar/Desactivar Conceptos', Nomina+'ActivarConceptos'],
				['Asignacion de Categorias por Empleados', Nomina+'AsignarCategoriasConceptosxEmpleado'],
				['Asignacion de Modalidad de Pago de Cesta Ticket a Empleados por Nomina', Nomina+'ModalidadCestaTicketEmpleados'],
			],
			['Movimientos de Nomina', null,
				['Movimientos Por Concepto', Nomina+'NomNomMovNomCon'],
				['Movimientos Por Concepto y Cargos', Nomina+'NomNomMovNomConCar'],
				['Movimientos Por Empleado', Nomina+'NomNomMovNomEmp'],
				['Modificar Monto/cantidad a Conceptos Segun Formula', Nomina+'ModificarMontoConcepto'],
			],
			['Nominas Especiales', null,
				['Definicion', Nomina+'NomEspDefinicion'],
				['Conceptos', Nomina+'NomEspConceptos'],
				['Calculo', Nomina+'NomEspCalculo'],
			],
			['Calculos de Nomina', null,
				['Calculo de Nomina', Nomina+'NomNomCalNom'],
				['Calculo de Nomina por Empleados', Nomina+'NomNomCalNomInd'],
				['Cierre de Nomina', Nomina+'NomNomCieNom'],
			],
			['Prestamos', null,
				['Tipos de Prestamos', Nomina+'NomDefEspTipPre'],
				['Prestamos', Nomina+'NomPerPrestamos'],
				['Movimientos de Prestamos', Nomina+'NomPerHisPre'],
			],
			['Reportes',null,
				['Definiciones Especificas', null,
					['Tipos Nomina', ReportesNomina+'nprnomina.php'],
					['Conceptos', ReportesNomina+'nprdefcpt.php'],
					['Conceptos por Nomina', ReportesNomina+'nprconnom.php'],
					['Niveles Organizacionales', ReportesNomina+'nprnivorg.php'],
					['Cargos', ReportesNomina+'nprcargos.php'],
					['Bancos', ReportesNomina+'nprbancos.php'],
					['Categorias Presupuestarias', ReportesNomina+'nprcatpre.php'],
					['Municipios', ReportesNomina+'nprmunicipios.php'],
				],
				['Personal', null,
					['Datos Personales', ReportesNomina+'nprhojint.php'],
					['Asignaci&oacute;n de Cargos', ReportesNomina+'nprasicaremp.php'],
					['Ingresos y Egresos del Personal por Per&iacute;odos', ReportesNomina+'npringegr.php'],
				],
				['Prestaciones', null,
					['Antiguedad Prestaciones Sociales Nuevo Regimen', ReportesNomina+'npcalpresoc_rn.php'],
					['Antiguedad Prestaciones Sociales Antiguo Regimen', ReportesNomina+'npcalpresoc_rv.php'],
					['Anticipos sobre Prestaciones Sociales', ReportesNomina+'nprcalantpresoc.php'],
					['Compensaci&oacute;n Bono Transferencia', ReportesNomina+'nprbonotransf.php'],
					['Intereses sobre Prestaciones Sociales Nuevo Regimen', ReportesNomina+'nprintpresoc_rn.php'],
					['Liquidaci&oacute;n de Cuentas', ReportesNomina+'nprprestliquidacion.php'],
				],
				['Vacaciones', null,
					['Solicitud de Vacaciones', ReportesNomina+'npvac_solicitud.php'],
					['Historico de Vacaciones disfrutadas por Empleado', ReportesNomina+'npvac_historico.php'],
					['Relaci&oacute;n de Vacaciones disfrutadas por Empleado en lote', ReportesNomina+'npvac_relacionhistoricos.php'],
					['Relaci&oacute;n de Vacaciones Procesadas', ReportesNomina+'npvac_relacionsalidas.php'],
				],
				['Listados de Nomina', null,
					['Listados de N&oacute;mina Definitiva por Categoria', ReportesNomina+'nprnomdefcat.php'],
					['Listados de N&oacute;mina Definitiva por Nivel', ReportesNomina+'nprnomdefniv.php'],
					['Listado de N&oacute;mina para la firma por Categor&iacute;a', ReportesNomina+'nprnomfircat.php'],
					['Consolidado de Nómina', ReportesNomina+'nprconsolidado.php'],
				],
				['Recibos de Pago', null,
					['Recibos de Pago', ReportesNomina+'nprrecpag.php'],
				],
				['Listado de Conceptos', null,
					['Listados por Conceptos *', ReportesNomina+'nprlistconc.php'],
					['Relaci&oacute;n Categoria - Conceptos', ReportesNomina+'nprconniv.php'],
				],
				['Relaciones Presupuestarias', null,
					['Relaci&oacute;n N&oacute;mina/Presupuesto', ReportesNomina+'nprnompre.php'],
					['Disponibilidad Presupuestaria por N&oacute;mina', ReportesNomina+'disponibilidadpresupnomina.php'],
				],
				['Relaciones de Pago', null,
					['Relaci&oacute;n Cuentas Bancarias/ N&oacute;mina', ReportesNomina+'nprrelbanc.php'],
				],
				['Diskettes', null,
					['Relaci&oacute;n Deposito/Banco', ReportesNomina+'nprrelbancdisc.php'],
				],
				['Historicos', null,
					['Historico Listado por Conceptos', ReportesNomina+'nprhistlistconc.php'],
				],
			],
			['Mantenimiento', null,
				['Importar Asignaci&oacute;n de Cargos', Nomina+'ImportarAsignarCargos'],
				['Importar Hoja Integral', Nomina+'ImportarHojaIntegral'],
				['Importar Valores de Conceptos', Nomina+'ImportarValoresConceptos'],
				['Clasificador de Partidas Presupuestarias', Nomina+'nommanclapre'],
			],
		],
	],
];

var TREE_ITEMSCOM_FOR = [
	['SIGA', null,
		['Formulaci&oacute;n de Presupuesto', null,
			['Definiciones Generales', null,
				['Areas Estrategicas', null,
					['Equilibrios', Formulacion+'fordefequ'],
					['Sub Objetivos', Formulacion+'fordefsubobj'],
					['Sub Sub Objetivos', Formulacion+'fordefsubsubobj'],
					['Unidades de Medidas', Formulacion+'fordefunimed'],
					['Definiciones de Estatus', Formulacion+'fordefstatus'],
					['Organismos P&uacute;blicos', Formulacion+'fordeforgpub'],
				],
			],
			['Ingresos', null,
				['Clasificador Presupuestario (Recursos)', Formulacion+'pretiting'],
				['Formulaci&oacute;n', null,
					['Formulaci&oacute;n Presupuesto de Ingresos Directa', Formulacion+'fortitingivss'],
				],				
			],
			
			['Egreso', null,
				['Definiciones Especificas', null,
					['Registro de Directrices', Formulacion+'fordefdirectriz'],
					['Proyectos y Acciones Centralizadas IVSS', Formulacion+'fordefproyectoivss'],
					['Acciones Espec&iacute;ficas IVSS', Formulacion+'fordefaccespivss'],
					['Acciones POA IVSS', Formulacion+'fordefaccpoaivss'],
					['Asociaci&oacute;n de Acciones POA a Acciones Especificas - Proyectos', Formulacion+'fordefpryaccsubaccivss'],
					['Actividades por Sub Acciones - Acciones Especificas - Proyectos IVSS', Formulacion+'fordefpryaccactivss'],
					['Unidades Ejecutoras IVSS', Formulacion+'fordefcatpreivss'],
				],
				['Formulaci&oacute;n', null,
					['Seguimientos Metas Formuladas en el POA', Formulacion+'forsegpoaivss'],
				],
			],
			['Reportes',null,
				['Generales',null,
					['Identificacion del Ente', ReportesFormulacion+'forrideent.php'],
					['Marco Macro-Econ&oacute;mico', ReportesFormulacion+'forrpretarmed.php'],
					['Precios y/o Tarifas Medias', ReportesFormulacion+'forrideent.php'],
					['Recursos Humanos del Ente Clasificados por Tipo de Cargos', ReportesFormulacion+'forrrhclatipcar.php'],
					['Clasificaci&oacute;n del Personal del Ente por Escala de Sueldos', ReportesFormulacion+'forrclaperescsue.php'],
					['Escala del Personal Pensionado', ReportesFormulacion+'forrescperpen.php'],
					['Escala del Personal Jubilado', ReportesFormulacion+'forrescperjub.php'],
					['Proyectos y Acciones Centralizadas de los Entes', ReportesFormulacion+'proyaccentes.php'],
					['Presupuesto de Gastos por Subespecifica', ReportesFormulacion+'presubesp.php'],
				],	
			],	                                                                                        
		],
	],
];

var TREE_ITEMS_ING = [
	['SIGA', null,
		['Ingresos', null,
			['Definiciones Generales', null,
				['Asignacion Inicial', Ingresos+'ingasiini'],
			],
		],
	],
];


var TREE_ITEMS_MAIN = [
	['SIGA', null,
		['Contabilidad Presupuestaria', servidor+'/sistemafull/aplicaciones/presupuesto/index.php'],
		['Contabilidad Financiera', servidor+'/sistemafull/aplicaciones/contabilidad/index.php'],
		['Compras Y Almacen', 'principal/menu/m/compras'],
		['Ingresos', 'principal/menu/m/ingresos'],
		['Tesorer&iacute;a', 'principal/menu/m/tesoreria'],
		['Nomina', 'principal/menu/m/nomina'],
		['Formulacicn', 'principal/menu/m/formulacion'],
		['Obras y Contratos', 'principal/menu/m/obra_cont'],
		['Inversi&oacute;n y Colocaci&oacute;n', 'principal/menu/m/inv_coloc'],
		['Cr&eacute;dito y Cobranza', 'principal/menu/m/cred_cobr'],
      ]
	];

