var Compras = '/compras_dev.php/';
var Tesoreria= '/tesoreria_dev.php/';
var Nomina='/nomina_dev.php/';
var Ingresos='/ingresos_dev.php/';
var Formulacion='/formulacion_dev.php/';
var Obras='/obras_dev.php/';
var Inv_coloc='/inv_coloc_dev.php/';
/*var Cred_cobr='/cred_cobr_dev.php/';*/
var Cred_cobr='/financiamiento.php/';
var Bienes = '/bienes_dev.php/';
var Hacienda = '/hacienda_dev.php/';
/*var Financiamiento = '/financiamiento_dev.php/';*/
var Documentos = '/documentos_dev.php/';
var Aciudadano = '/ciudadanos_dev.php/';



var ReportesCompras='http://'+window.location.host+'/reportes/reportes/compras/';
var ReportesTesoreria='http://'+window.location.host+'/reportes/reportes/tesoreria/';
var ReportesNomina='http://'+window.location.host+'/reportes/reportes/nomina/';
var ReportesFormulacion='http://'+window.location.host+'/reportes/reportes/formulaciondemo/';
var ReportesContabilidad='http://'+window.location.host+'/reportes/reportes/contabilidad/';
var ReportesPresupuesto='http://'+window.location.host+'/reportes/reportes/presupuesto/';
var ReportesDocumentos='http://'+window.location.host+'/reportes/reportes/documentos/';
var ReportesBienes='http://'+window.location.host+'/reportes/reportes/bienes/';
var ReportesAciudadano='http://'+window.location.host+'/reportes/reportes/ciudadanos/';


var Presupuesto='/contabilidadpresupuesto/aplicaciones/presupuesto/';
var Contabilidad='/contabilidadpresupuesto/aplicaciones/contabilidad/';

var servidor='http://'+window.location.host;


var TREE_ITEMSCOM_PRE = [
  ['SIGA', null,
    ['Contabilidad Presupuestaria', null,
      ['Definiciones espec&iacute;ficas',null,
        ['Niveles Presupuestarios',Presupuesto + 'PreNivPre.php'],
        ['T&iacute;tulos Presupuestarios',Presupuesto + 'PreTitPre.php'],
        ['Asignaci&oacute;n Inicial', Presupuesto + 'PreAsiIni.php'],
        ['Asignar Partidas', Presupuesto + 'PreAsiPar.php'],
        ['Art&iacute;culos de Ley', Presupuesto + 'PreArtLey.php'],
        ['Documentos',null,
          ['Precompromisos',Presupuesto + 'PreDocPre.php'],
          ['Compromisos',Presupuesto + 'PreDocCom.php'],
          ['Causados', Presupuesto + 'PreDocCau.php'],
          ['Pagos', Presupuesto + 'PreDocPag.php'],
          ['Ajustes', Presupuesto + 'PreDocAju.php'],
        ],
      ],
      ['Ejecuci&oacute;n Presupuestaria',null,
        ['Ejecuci&oacute;n Global',Presupuesto + 'PreEjeGlo.php'],
        ['Precomprometer',Presupuesto + 'PrePreCom.php'],
        ['Comprometer', Presupuesto + 'PreCompro.php'],
        ['Causar', Presupuesto + 'PreCausar.php'],
        ['Pagar', Presupuesto + 'PrePagar.php'],
        ['Solicitud de Traslados', Presupuesto + 'PreSolTrasla.php'],
        /*['Aprobación de Solicitud de Traslado', Presupuesto + 'PreAprTrasla.php'],*/
        ['Traslados', Presupuesto + 'PreTrasla.php'],

        ['Solicitud de Creditos Adicionales/Disminuciones', Presupuesto + 'PreSolAdiDis.php'],
        ['Creditos Adicionales/Disminuciones', Presupuesto + 'PreAdiDis.php'],

        ['Ajustes Ejecuci&oacute;n', Presupuesto + 'PreAjuste.php'],
       ],
      ['Matenimiento',null,
          ['Cierre del Periodo', Presupuesto + 'precieper.php'],
          ['Cerrar Etapa de Definicion', Presupuesto + 'preetadef.php'],
      ],
      ['Reportes',null,
          ['Definiciones Especificas',null,
            ['Cat&aacute;logo de Partidas', ReportesPresupuesto+'precatpar.php'],
            ['Documentos Precompromiso', ReportesPresupuesto+'PreCatPrc.php'],
            ['Documentos Compromiso', ReportesPresupuesto+'PreCatCom.php'],
            ['Documentos Causado', ReportesPresupuesto+'PreCatCau.php'],
            ['Documentos Pago', ReportesPresupuesto+'PreCatPag.php'],
          ],
          ['Movimientos',null,
            ['Precompromisos', ReportesPresupuesto+'PrePrc.php'],
            ['Compromisos', ReportesPresupuesto+'PreCom.php'],
            ['Causados', ReportesPresupuesto+'PreCau.php'],
            ['Pagados', ReportesPresupuesto+'PrePag.php'],
            ['Traslados', ReportesPresupuesto+'PreTra.php'],
            ['Ajustes', ReportesPresupuesto+'PreAju.php'],
            ['Adiciones/Disminuciones', ReportesPresupuesto+'PreRAdiDis.php'],
          ],
          ['Ejecuci&oacute;n Presupuestaria',null,
            ['Asignaci&oacute;n Inicial', ReportesPresupuesto+'PreRAsiIni.php'],
            ['Asignaci&oacute;n Inicial por Partidas', ReportesPresupuesto+'prerasiinipar.php'],
            ['Ejecuci&oacute;n Presupuestaria', ReportesPresupuesto+'PreDisPer.php'],
            ['Ejecuci&oacute;n Presupuestaria Coordinada', ReportesPresupuesto+'PREDISPERCOO_DISCOM.php'],
            ['Ejecuci&oacute;n Presupuestaria por Partida', ReportesPresupuesto+'PreDisPar.php'],
            ['Disponibilidad Financiera', ReportesPresupuesto+'PreDisFin.php'],
            ['Disponibilidad Negativa', ReportesPresupuesto+'PreDisNeg.php'],
          ]
            ],
    ],
  ],
];


var TREE_ITEMSCOM_CON = [
  ['SIGA', null,
    ['Contabilidad Financiera', null,
      ['Definiciones espec&iacute;ficas de la Instituci&oacute;n',Contabilidad + 'ConFinIns.php'],
      ['Tipos de Cuentas - Cuentas Contables',Contabilidad + 'ConFinTipCueCon.php'],
      ['Cat&aacute;logo de Cuentas', Contabilidad + 'ConFinCue.php'],
      ['Comprobantes', Contabilidad + 'ConFinCom.php'],
      ['Actualizar Comprobantes', Contabilidad + 'ConFinActCom.php'],
      ['Cierre del Periodo', Contabilidad + 'ConFinCiePer.php'],
      ['Cierre del Ejercicio', Contabilidad + 'ConFinCie.php'],
    ['Mantenimiento', null,
      ['Eliminar Comprobantes Anulados',Contabilidad + 'ConFinElicom.php'],
      ['Cerrar Etapa de Definicion', Contabilidad + 'confinciedef.php'],
    ],
    ['Reportes', null,
      ['Catalogo de Cuentas', ReportesContabilidad+'ConCatCue.php'],
      ['Diario de Comprobantes', ReportesContabilidad+'ConDiaCom.php'],
      ['Resumen de Comprobantes', ReportesContabilidad+'ConResCom.php'],
      ['Resumen Diario', ReportesContabilidad+'ConResDia.php'],
      ['Balance de Comprobaci&oacute;n', ReportesContabilidad+'ConBalCom.php'],
      ['Balance General', ReportesContabilidad+'ConBalGen.php'],
      ['Estado de Resultados', ReportesContabilidad+'ConEdoRes.php'],
      ['Mayor General', ReportesContabilidad+'ConMayGen.php'],
      ['Mayor Anal&iacute;tico', ReportesContabilidad+'ConMayAna.php'],
      ['Comprobante Individual', ReportesContabilidad+'Comprobante.php'],
      ['Flujo de Caja', ReportesContabilidad+'conrflucaj.php'],
    ],
      ],
  ]
];

var TREE_ITEMSCOM_ALM = [
  ['SIGA', null,
    ['Compras y Almac&eacute;n', null,
      ['Proveedores', null,
        ['Definici&oacute;n de Grupos de Recaudos', Compras+'almtiprecpro'],
        ['Definici&oacute;n de Recaudos', Compras+'almregrec'],
        ['Registro de Proveedores', Compras+'almregpro'],
        ['Definici&oacute;n de Condiciones de Pago', Compras+'almconpag'],
        ['Definici&oacute;n de Formas de Entrega', Compras+'almforent'],
        ['Definici&oacute;n de Razones de Compra', Compras+'almrazcom'],
        ['Definici&oacute;n de Rangos de Cotizaciones', Compras+'almdefcot'],
        ['Definici&oacute;n de Motivos de Faltantes', Compras+'almmotfal'],
        ['Definici&oacute;n de Tipo de Entrada', Compras+'almtipent'],
        ['Definici&oacute;n de Tipo de Salida', Compras+'almtipsal'],
        ['Definici&oacute;n de Tipo de Proyecto', Compras+'almtippro'],
      ],
      ['Art&iacute;culos', null,
        ['Definici&oacute;n de Art&iacute;culos', Compras+'almdefart'],
        ['Definici&oacute;n de Ubicaciones', Compras+'almdefubi'],
        ['Ramos de Art&iacute;culos', Compras+'almramart'],
        ['Registro de Art&iacute;culos y+o Servicios', Compras+'almregart'],
        ['Registro de Recargos', Compras+'almregrgo'],
        ['Asociaci&oacute;n de Retenciones a Servicios', Compras+'almretser'],
      ],
      ['Compras', null,
        ['Ordenes de Compra y+o Servicio', Compras+'almordcom'],
        ['Ajuste a Ordenes de Compra', Compras+'almajuoc'],
        ['Cotizaciones', Compras+'almcotiza'],
        ['Asignaci&oacute;n de Prioridad a Cotizaciones', Compras+'almpriori'],
      ],
      ['Almacen',null,
        ['Definiciones Generales', Compras+'almdefalm'],
        ['Requisiciones', Compras+'almreq'],
        ['Requisiciones de Servicios', Compras+'almreqser'],
        ['Requisiciones por Departamento (Solicitud de Egresos)', Compras+'almsolegr'],
        ['Despachos', Compras+'almdesp'],
        ['Prestacion de Servicios', Compras+'almdespser'],
        ['Inventario F&iacute;sico', Compras+'alminvfis'],
        ['Traspaso de Art&iacute;culos', Compras+'almtraalm'],
        ['Recepcion de Ordenes de Compras', Compras+'almordrec'],
        ['Entradas de Almacen', Compras+'almentalm'],
        ['Salida de Almacen', Compras+'almsalalm'],
      ],
      ['SNC', null,
        ['Catalogo SNC', Compras+'almdefcatsnc'],
        ['Tipos de Empresas Proveedoras', Compras+'almtipemp'],
        ['Medios de Comunicacion', Compras+'almmedcom'],
        ['Procedimientos de Ejecucion de Compras', Compras+'almprocom'],
        ['Programar Compras de Articulos', Compras+'almprocomart'],
      ],
      ['Reportes',null,
        ['Generales',null,
          ['Cat&aacute;logo de Art&iacute;culos', ReportesCompras+'carcatart.php'],
          ['Cat&aacute;logo de Ramos', ReportesCompras+'carramart.php'],
          ['Cat&aacute;logo de Proveedores', ReportesCompras+'carprovee.php'],
          ['Cat&aacute;logo de Unidades', ReportesCompras+'cardefalm.php'],
          ['Cat&aacute;logo de Recaudos', ReportesCompras+'carrecaud.php'],
          ['Cat&aacute;logo de Recargos', ReportesCompras+'carrecarg.php'],
          ['Ficha del Proveedor', ReportesCompras+'carficpro.php'],
        ],
        ['Movimientos',null,
          ['Requisiciones', ReportesCompras+'carreqart.php'],
          ['Recepciones', ReportesCompras+'carrcpart.php'],
          ['Despachos', ReportesCompras+'cardphart.php'],
          ['Ordenes de Compra y/o Servicio', ReportesCompras+'cardetord.php'],
          ['Recepciones y Diferencias', ReportesCompras+'carrcpord.php'],
          ['Despachos y Diferencias', ReportesCompras+'carreqdph.php'],
          ['Resumen de Movimientos', ReportesCompras+'carmovart.php'],
        ],
        ['Formas Preimpresas',null,
          ['Etiquetas de Articulos', ReportesCompras+'caretique.php'],
          ['Requisiciones', ReportesCompras+'carreqpre.php'],
          ['Solicitud de Autorizaci&oacute;n de Egreso', ReportesCompras+'carsolegr.php'],
          ['Recepciones', ReportesCompras+'carrcppre.php'],
          ['Despachos', ReportesCompras+'cardphpre.php'],
          ['Ordenes de Compra', ReportesCompras+'carordpre.php'],
          ['Ordenes de Servicio', ReportesCompras+'carordser.php'],
          ['Constancia de Inscripci&oacute;n Provisional De Proveedores', ReportesCompras+'carconinspro.php'],
        ],
        ['Almac&eacute;n',null,
          ['Relaci&oacute;n Inventario Almac&eacute;n', ReportesCompras+'carrelinvalm.php'],
          ['Hoja de Conteo F&aacutesico', ReportesCompras+'carconfis.php'],
          ['Inventario F&iacute;sico Valorado', ReportesCompras+'carinvfis.php'],
          ['Stock M&aacute;ximo', ReportesCompras+'carstomax.php'],
          ['Stock M&aacute;nimo', ReportesCompras+'carstomin.php'],
          ['Punto de Reorden', ReportesCompras+'carptoreo.php'],
        ],
      ],
      ['Mantenimiento', null,
        ['Clasificador de Partidas Presupuestarias', Compras+'nommanclapre'],
      //  ['Traspaso de Inventario Fisico a Logico', Compras+'almtrainv'],
      //  ['Importar Productos', Compras+'importarproducto'],
       // ['Actualizar Precios y Existencias', Compras+'actualizarproducto'],
      ],
    ],
  ],
];

var TREE_ITEMS_TER = [
  ['SIGA', null,
    ['Tesorer&iacute;a', null,
      ['Definiciones Espec&iacute;ficas', null,
        ['Empresa', Tesoreria+'pagdefemp'],
        ['Tipos de Cuentas Bancarias', Tesoreria+'tesdeftipcue'],
        ['Tipos de Movimientos Bancarios', Tesoreria+'tesdeftipmov'],
        ['Tipos de Rendimiento', Tesoreria+'tesdeftipren'],
        ['Tipos de Monedas', Tesoreria+'tesdeftipmon'],
        ['Tipos de Retenciones', Tesoreria+'pagtipret'],
        ['Tipos de Financiamiento', Tesoreria+'pretipfin'],
        ['Bancos', Tesoreria+'tesdefcueban'],
        ['Tipos de Beneficiario', Tesoreria+'pagtipben'],
        ['Beneficiarios', Tesoreria+'pagbenfic'],
        ['Asociacion Conceptos+Tipos de Retenciones', Tesoreria+'pagretcon'],
        ['Definici&oacute;n de Ubicaci&oacute;n', Tesoreria+'tesdesubi'],
        ['Definici&oacute;n del Iva para Agentes de Retenci&oacute;n', Tesoreria+'pagretiva'],
        ['Definici&oacute;n de Cuentas Contables para Rendici&oacute;n de Gastos', Tesoreria+'tesdefrengas'],
        ['Definici&oacute;n de Reportes de Comprobantes de Retenci&oacute;n', Tesoreria+'pagrepret'],
      ],

      ['Ordenamiento de Pago', null,
        ['Ordenes de Pago', Tesoreria+'pagemiord'],
        ['Fondos a Terceros', Tesoreria+'pagemiret'],
        ['Enterar Retenci&oacute;n de ISLR', Tesoreria+'tesretislr'],
      ],
      ['Bancos', null,
        ['Emision de Cheques', Tesoreria+'tesmovemiche'],
        ['Movimientos seg&uacute;n Libros', Tesoreria+'tesmovseglib'],
        ['Movimientos seg&uacute;n Libros A&ntilde;os Anteriores', Tesoreria+'tesmovseglibant'],
        ['Movimientos seg&uacute;n Bancos', Tesoreria+'tesmovsegban'],
        ['Movimientos seg&uacute;n Bancos A&ntilde;os Anteriores', Tesoreria+'tesmovsegbanant'],
        ['Actualizaci&oacute;n en Lotes de los Bancos', Tesoreria+'tesmoslib'],
        ['Transferencias Bancarias', Tesoreria+'tesmovtraban'],
        ['Conciliaci&oacute;n', Tesoreria+'tesmovconban'],
        ['Cierre de Per&iacute;odo', Tesoreria+'tesmovcieban'],
      ],
      ['Caja', null,
        ['Cheques en Custodia', Tesoreria+'teschecus'],
      ],
    ['Reportes', null,
        ['Generales',  null,
          ['Cat&aacute;logo de Tipos de Cuentas Bancarias', ReportesTesoreria+'tsrtipcue.php'],
          ['Cat&aacute;logo de Tipos de Movimientos Bancarios', ReportesTesoreria+'TSRTIPMOV.php'],
          ['Cat&aacute;logo de Tipos de Monedas', ReportesTesoreria+'TSRDESMON.php'],
          ['Cat&aacute;logo de Tipos de Retenciones', ReportesTesoreria+'OPRTIPRET.php'],
          ['Cat&aacute;logo de Tipos de Financiamiento', ReportesTesoreria+'PRECATTIPFIN.php'],
          ['Cat&aacute;logo de Tipos de Ubicaciones', ReportesTesoreria+'OPRDESUBI.php'],
          ['Cat&aacute;logo de Tipos de Beneficiarios', ReportesTesoreria+'OPRTIPBEN.php'],
          ['Cat&aacute;logo de Beneficiarios', ReportesTesoreria+'OPRBENEFI.php'],
          ['Cat&aacute;logo de Bancos', ReportesTesoreria+'TRSDEFBAN.php'],
         ],
        ['Ordenamiento de Pago', null,
          ['Orden de Pago Preimpresa', ReportesTesoreria+'OPRORDPRE_NEW.php'],
          ['Ordenes de Pagos con Retenciones', ReportesTesoreria+'OPRORDRET.php'],
          ['Relaci&oacute;n Anexa', ReportesTesoreria+'OPRRELANEX.php'],
          ['Listado de Ordenes de Pago', ReportesTesoreria+'OPRORDPAG.php'],
          ['Listado de Ordenes de Pago por Fecha', ReportesTesoreria+'OPRORDPAGEFEC.php'],
          ['Listado de Ordenes de Pago por Beneficiario', ReportesTesoreria+'OPRORDPAGBEN.php'],
          ['Listado de Ordenes de Pago con Retenciones', ReportesTesoreria+'OPRORDRET.php'],
          ['Desglose de Ordenes de Retenciones por Beneficiario', ReportesTesoreria+'OPRORDRETBEN.php'],
          ['Retenciones Pagadas y Pendientes por Pagar', ReportesTesoreria+'TSFONTER.php'],
         ],
         ['Bancos', null,
          ['Disponibilidad Bancaria', ReportesTesoreria+'TSRDISBAN.php'],
          ['Relaci&oacute;n de Cuentas Bancarias', ReportesTesoreria+'TSRRELBAN.php'],
          ['Movimientos seg&uacute;n Libros', ReportesTesoreria+'TSRMOVLIB.php'],
          ['Movimientos seg&uacute;n Libros por Banco', ReportesTesoreria+'TSRMOVLIBBAN.php'],
          ['Movimientos seg&uacute;n Bancos', ReportesTesoreria+'TSRMOVBAN.php'],
          ['Movimientos seg&uacute;n Bancos por Banco', ReportesTesoreria+'TSRMOVBANBAN.php'],
          ['Transferencias Bancarias', ReportesTesoreria+'TSRTRABAN.php'],
          ['Oficio para Autorizaci&oacute;n a Transferencias Bancarias (R)', ReportesTesoreria+'OPRtransferencia.php'],
          ['Conciliaci&oacute;n Bancaria', ReportesTesoreria+'TSRCONCIL.php'],
          ['Detalle de Conciliaci&oacute;n', ReportesTesoreria+'TSRRESCON.php'],
         ],
        ['Caja', null,
          ['Cheque Preimpreso', ReportesTesoreria+'tsrvoucher1.php'],
        ],
        ['Impuestos', null,
          ['Comprobante de retenci&oacute;n IVA', ReportesTesoreria+'OPRCOMPRET_IVA.php'],
          ['Comprobante de retenci&oacute;n ISLR', ReportesTesoreria+'OPRCOMPRET_ISLR.php'],
          ['Comprobante de retenci&oacute;n LTF', ReportesTesoreria+'OPRCOMPRET_LTF.php'],
          ['Libro de Compras', ReportesTesoreria+'TSRLIBCOM.php'],
        ],
      ],
      ['Mantenimiento', null,
        ['Actualizar Monto de Retenciones por Orden', Tesoreria+'pagmodret'],
      ],
    ],
  ]
];

var TREE_ITEMS_NOM = [
  ['SIGA', null,
    ['Recurso Humano', null,
      ['Definiciones espec&iacute;ficas', null,
        ['Institucion', Nomina+'nomdefespgen'],
        ['Tipos Nominas', Nomina+'nomdefesptipnom'],
        ['Conceptos', Nomina+'nomdefespcon'],
        ['Niveles Organizacionales', Nomina+'nomdefespnivorg'],
        ['Cargos', Nomina+'nomdefespcar'],
      ['Definicion de Conceptos Variables', Nomina+'nomdefespmovper'],
        ['Variables', Nomina+'nomdefespvar'],
        ['Bancos', Nomina+'nomdefespban'],
        ['Profesiones', Nomina+'nomdefespprofes'],
        ['Perfiles', Nomina+'nomdefespperfil'],
        ['Tipos de Parientes', Nomina+'nomdefesppar'],
        ['Guarderias', Nomina+'nomdefespguarde'],
        ['Tipos de Gastos', Nomina+'nomdeftipgas'],
        ['Motivos de Faltas y/o Permisos', Nomina+'nomdefespmotfalpre'],
        ['Situacion del Empleado', Nomina+'nomdefespsitemp'],
        ['Definicion de Condicion Contractual', Nomina+'nomdefespgrulab'],
//        ['Conceptos para Reportes', Nomina+'nomdefespconsue'],
        ['Conceptos para el Salario Integral', Nomina+'nomconceptossalariointegral'],
        ['Conceptos para el Sueldo', Nomina+'nomconceptossueldo'],
        ['Conceptos para las Primas', Nomina+'nomconceptosprimas'],
        ['Conceptos de Compensacion por Nomina', Nomina+'nomconceptoscompensacion'],
        ['Conceptos de Ahorro Habitacional', Nomina+'nomdefconaho'],
        ['Conceptos para el Fondo de Jubilacion y Pensiones', Nomina+'nomdefconfon'],
//    ['Definicion de Jornadas Laborales', Nomina+'nomjorlablot'],
        ['Jornadas Laborales por Empleado', Nomina+'nomjorlabind'],
//        ['Definicion de Concepto de Cesta Tickets', Nomina+'nomdefespcestic'],
        ['Tipos de Retiros', Nomina+'nomdeftipret'],
        ['Definicion de Conceptos para Dias Adicionales', Nomina+'nomdefdiaadicnom'],
        ['Conceptos para el ISLR', Nomina+'nomdefespislr'],
        ['Definicion de Retenciones y Aportes', null,
          ['Retenciones y Aportes', Nomina+'nomdefaportes'],
          ['Conceptos para Aportes', Nomina+'nomdefconaportes'],
          ['Conceptos para Retenciones', Nomina+'nomdefconretencion'],
        ],
        ['Division Territorial', null,
          ['Estados', Nomina+'nomdefesppai'],
          ['Municipio', Nomina+'nomdefespest'],
          ['Parroquia', Nomina+'nomdefespciu'],
        ],
      ],
      ['Personal', null,
        ['Datos Personales', Nomina+'nomhojint'],
        ['Tipo de Cargos', Nomina+'nomtipcar'],
        ['Tipo de Dedicacion', Nomina+'nomtipded'],
      ['Tabla de Sueldos por Grado y Paso', Nomina+'nomcomocp'],
        ['Asignacion de Cargos y Conceptos a Empleados', Nomina+'nomasicarconnom'],
 //       ['Asignacion de Cargos a Empleados en lote', Nomina+'nomasicaremplot'],
//        ['Cambio de Cargos a Empleados', Nomina+'cambiodecargos'],
      ],
//      ['Archivo de elegibles',Nomina+'nomhojint'],
      ['Faltas y/o Permisos', null,
        ['Permisos', Nomina+'nomfalperper'],
        ['Salidas', Nomina+'nomfalpersal'],
        ['Llegadas', Nomina+'nomfalperlle'],
        ['Registro de Dias Extras', Nomina+'nomdiaext'],
        ['Registro de Faltas y/o Permisos Por Nomina en Lote', Nomina+'nomfalperlot'],
        ['Registro de Dias Extras Por Nomina en Lote', Nomina+'nomdiaextlablot'],
      ],
      ['Vacaciones', null,
    ['Parametros para el Registro y Control de Vacaciones', Nomina+'vacdefgen'],
        ['Definicion de Bono Vacacional y Jornada Laboral', Nomina+'vacdiasbonovac'],
        ['Tabla para los Dias de Disfrute', Nomina+'vacdiadis'],
        ['Tabla para los Dias Feriados', Nomina+'vacdiafer'],
        ['Registro de Vacaciones Disfrutadas', Nomina+'vachistorico'],
        ['Registro de Vacaciones Disfrutadas en Lote', Nomina+'vachistorico_lote'],
        ['Registro de Solicitud de Vacaciones', Nomina+'vacsalidas'],
//        ['Registro y Control de Vacaciones', Nomina+'vacregsalVac'],
    ['Liquidacion de Vacaciones Por Egreso', Nomina+'vacliquidacion'],
      ],
      ['Prestaciones', null,
        ['Definicion de Parametros para las Prestaciones Sociales',null,
             ['Tipos de Contratos Colectivos', Nomina+'presnomtipcon'],
             ['Registro de Tipos de Asignaciones', Nomina+'presnomasiconpre'],
         ['Definicion Presupuestaria de Liquidacion', Nomina+'presnomdefpre'],
        ],
        ['Registros Utiles para el Calculo de Prestaciones Sociales',null,
             ['Asignacion de Trabajadores para Prestaciones  Por Contrato Colectivo', Nomina+'presnomasitrabcont'],
             ['Registro de Tasas de Interes Periodicas', Nomina+'presnomintfecref'],
         ['Registro de Salario Integral por Contrato', Nomina+'presnomregsalint'],
         ['Registro de Salario Integral por Contrato Individual', Nomina+'presnomregsalintind'],
        ],
        ['Registro Historico de Anticipos Otorgados', Nomina+'presnomreghisantpre'],
        ['Solicitud de Anticipo Sobre Prestaciones', Nomina+'presnomantpre'],
        ['Calculo de Prestaciones Sociales', Nomina+'presnomcalintpre'],
      ['Liquidacion Final de Prestaciones', Nomina+'presnomliquidacion'],
//        ['Importar Datos Prestaciones Sociales', Nomina+'importarprestaciones'],
      ],
      ['Asignaciones Generales para el Calculo de Nomina', null,
    ['Asignacion de Conceptos por Categoria Presupuestaria Especiales', Nomina+'asignarconceptoscategoria'],
        ['Asignacion de Conceptos a Nomina', Nomina+'asignarconceptosnomina'],
        ['Asignacion de Cargos a Nomina', Nomina+'nomdefespasicartipnomlot'],
        ['Asignacion de Conceptos a Empleados', Nomina+'nomnomasiconnom'],
        ['Asignacion de Cuentas Bancarias por Empleado', Nomina+'empleadosbanco'],
  //      ['Activar/Desactivar Conceptos', Nomina+'activarconceptos'],
        ['Asignacion de Categorias por Empleados', Nomina+'asignarcategoriasconceptosxempleado'],
    ['Asignacion de Modalidad de Pago de Cesta Ticket a Empleados por Nomina', Nomina+'modalidadcestaticketempleados'],
      ],
      ['Movimientos de Nomina', null,
        ['Movimientos Por Concepto', Nomina+'nomnommovnomcon'],
        ['Movimientos Por Concepto y Cargos', Nomina+'nomnommovnomconcar'],
        ['Movimientos Por Empleado', Nomina+'nomnommovnomemp'],
//        ['Modificar Monto/cantidad a Conceptos Segun Formula', Nomina+'modificarmontoconcepto'],
      ],
      ['Nominas Especiales', null,
        ['Definicion', Nomina+'nomespdefinicion'],
        ['Conceptos', Nomina+'nomespconceptos'],
    ['Calculo', Nomina+'nomespcalculo'],
      ],
      ['Calculos de Nomina', null,
       ['Calculo de Conceptos(Formulacion)', Nomina+'nomcalcon'],
        ['Calculo de Nomina', Nomina+'nomnomcalnom'],
        ['Calculo de Nomina por Empleados', Nomina+'nomnomcalnomind'],
        ['Cierre de Nomina', Nomina+'nomnomcienom'],
      ],
      ['Prestamos', null,
        ['Tipos de Prestamos', Nomina+'nomdefesptippre'],
        ['Prestamos', Nomina+'nomperprestamos'],
    ['Movimientos de Prestamos', Nomina+'nomperhispre'],
      ],
      ['Reportes',null,
        ['Definiciones Especificas', null,
          ['Tipos Nomina', ReportesNomina+'nprnomina.php'],
          ['Conceptos', ReportesNomina+'nprdefcpt.php'],
          ['Conceptos por Nomina', ReportesNomina+'nprconnom.php'],
          ['Niveles Organizacionales', ReportesNomina+'nprnivorg.php'],
          ['Cargos', ReportesNomina+'nprcargos.php'],
          ['Bancos', ReportesNomina+'nprbancos.php'],
          ['Categorias Presupuestarias', ReportesNomina+'nprcatpre.php'],
          ['Municipios', ReportesNomina+'nprmunicipios.php'],
        ],
        ['Personal', null,
          ['Datos Personales', ReportesNomina+'nprhojint.php'],
          ['Asignaci&oacute;n de Cargos', ReportesNomina+'nprasicaremp.php'],
          ['Ingresos y Egresos del Personal por Per&iacute;odos', ReportesNomina+'npringegr.php'],
        ],
        ['Prestaciones', null,
          ['Antiguedad Prestaciones Sociales Nuevo Regimen', ReportesNomina+'npcalpresoc_rn.php'],
          ['Antiguedad Prestaciones Sociales Antiguo Regimen', ReportesNomina+'npcalpresoc_rv.php'],
          ['Anticipos sobre Prestaciones Sociales', ReportesNomina+'nprcalantpresoc.php'],
          ['Compensaci&oacute;n Bono Transferencia', ReportesNomina+'nprbonotransf.php'],
          ['Intereses sobre Prestaciones Sociales Nuevo Regimen', ReportesNomina+'nprintpresoc_rn.php'],
          ['Liquidaci&oacute;n de Cuentas', ReportesNomina+'nprprestliquidacion.php'],
        ],
        ['Vacaciones', null,
          ['Solicitud de Vacaciones', ReportesNomina+'npvac_solicitud.php'],
          ['Historico de Vacaciones disfrutadas por Empleado', ReportesNomina+'npvac_historico.php'],
          ['Relaci&oacute;n de Vacaciones disfrutadas por Empleado en lote', ReportesNomina+'npvac_relacionhistoricos.php'],
          ['Relaci&oacute;n de Vacaciones Procesadas', ReportesNomina+'npvac_relacionsalidas.php'],
        ],
        ['Listados de Nomina', null,
          ['Listados de N&oacute;mina Definitiva', ReportesNomina+'nprnomdef.php'],
          ['Listados de N&oacute;mina Definitiva por Categoria', ReportesNomina+'nprnomdefcat.php'],
          ['Listados de N&oacute;mina Definitiva por Nivel', ReportesNomina+'nprnomdefniv.php'],
          ['Listado de N&oacute;mina para la firma por Categor&iacute;a', ReportesNomina+'nprnomfircat.php'],
          ['Consolidado de N&oacute;mina', ReportesNomina+'nprconsolidado.php'],
        ],
        ['Recibos de Pago', null,
          ['Recibos de Pago', ReportesNomina+'nprrecpag.php'],
        ],
        ['Listado de Conceptos', null,
          ['Listados por Conceptos *', ReportesNomina+'nprlistconc.php'],
          ['Relaci&oacute;n Categoria - Conceptos', ReportesNomina+'nprconniv.php'],
          ['Relaci&oacute;n Nomina - Conceptos', ReportesNomina+'nprrelcon.php'],
        ],
        ['Relaciones de Retenciones y Aportes', null,
          ['Retenciones y Aportes', ReportesNomina+'npraportesretenciones.php'],
        ],
        ['Relaciones Presupuestarias', null,
          ['Relaci&oacute;n N&oacute;mina/Presupuesto', ReportesNomina+'nprnompre.php'],
          ['Disponibilidad Presupuestaria por N&oacute;mina', ReportesNomina+'disponibilidadpresupnomina.php'],
        ],
        ['Relaciones de Pago', null,
          ['Relaci&oacute;n Cuentas Bancarias/ N&oacute;mina', ReportesNomina+'nprrelbanc.php'],
        ],
        ['Diskettes', null,
          ['Relaci&oacute;n Deposito/Banco', ReportesNomina+'nprrelbancdisc.php'],
        ],
        ['Historicos', null,
          ['Historico Listado por Conceptos', ReportesNomina+'nprhistlistconc.php'],
        ],
      ],
      //['Mantenimiento', null,
//        ['Importar Asignaci&oacute;n de Cargos', Nomina+'importarasignarcargos'],
//        ['Importar Hoja Integral', Nomina+'importarhojaintegral'],
        //['Importar Valores de Conceptos', Nomina+'importarvaloresconceptos'],
        //['Clasificador de Partidas Presupuestarias', Nomina+'nommanclapre'],
      //],
    ],
  ],
];

var TREE_ITEMSCOM_FOR = [
  ['SIGA', null,
    ['Formulaci&oacute;n de Presupuesto', null,
      ['Definiciones Generales', null,
        ['Definici&oacute;n de Empresa', Formulacion+'fordefemp'],
        ['Niveles Presupuestarios', Presupuesto + 'PreNivPreFor.php'],
        ['Definiciones Generales', Formulacion+'fordefgen'],
        ['Ubicaci&oacute;n Geografica', null,
          ['Estados', Formulacion+'fordefest'],
          ['Municipios', Formulacion+'fordefmun'],
          ['Parroquias', Formulacion+'fordefpar'],
        ],
        ['Areas Estrategicas', null,
          ['Directrices', Formulacion+'fordefequ'],
          ['Estrategias', Formulacion+'fordefsubobj'],
          ['Pol&iacute;ticas', Formulacion+'fordefsubsubobj'],
        ],
        ['Unidades de Medidas', Formulacion+'fordefunimed'],
        ['Definiciones de Estatus', Formulacion+'fordefstatus'],
        ['Definici&oacute;n de Situaciones Presupuestarias', Formulacion+'fordefsitpre'],
        ['Definici&oacute;n de Objetivos Estrategicos Nueva Etapa', Formulacion+'fordefobjnvaeta'],
        ['Organismos P&uacute;blicos', Formulacion+'fordeforgpub'],
        ['Tipos de Contribuciones / Conexiones a Organismos P&uacute;blicos', Formulacion+'fordeftipcnx'],
        ['Sectores', Formulacion+'fordefsec'],
        ['Subsectores', Formulacion+'fordefsubsec'],
      ],
      ['Ingresos', null,
        ['Definiciones Especificas', null,
          ['Clasificador Presupuestario (Recursos)', Formulacion+'pretiting'],
          ['Tipos de Financiamiento', Formulacion+'pretitfin'],
        ],
        ['Formulaci&oacute;n', null,
          ['Formulaci&oacute;n Presupuesto de Ingresos Directa', Formulacion+'fortiting'],
          ['Totales por Fuente de Ingresos Ordinarios y Extraordinario', Formulacion+'fortotfueinggen'],
        ],
      ],
      ['Egresos', null,
        ['Definiciones Especificas', null,
          ['Tipos de Cr&eacute;dito Presupuestario (Funcionamiento - Inversion)', Formulacion+'pretiptit'],
          ['Clasificador Presupuestario (Gastos)', Formulacion+'pretitgas'],
          ['Registro de Programas', Formulacion+'fordefprg'],
          ['Proyectos y Acciones Centralizadas', Formulacion+'fordefproyecto'],
          ['Acciones Espec&iacute;ficas', Formulacion+'fordefaccesp'],
          ['Metas a Proyectos y Acciones Especificas', Formulacion+'fordefpryaccmet'],
          ['Unidades Ejecutoras', Formulacion+'fordefcatpre'],
        ],
        ['Formulaci&oacute;n', null,
          ['Formulaci&oacute;n POA', Formulacion+'forpoa'],
          ['Formulaci&oacute;n POA por Unidad Ejecutora', Formulacion+'forpoa_uae'],
          ['Crea Asignaci&oacute;n Inicial', Formulacion+'forcreasiini'],
          ['Seguimiento de Metas Formuladas en el POA', Formulacion+'forsegpoa'],
        ],
      ],
     ['Mantenimiento', null,
        ['Migrar Proyectos y Acciones Espec&iacute;ficas', Formulacion+'formancreproacc'],
     ],
    ],
  ],
];

var TREE_ITEMS_ING = [
  ['SIGA', null,
    ['Ingresos', null,
      ['Definiciones', null,
        ['Definiciones Especificas', null,
          ['Niveles', Ingresos+'ingnivpre'],
          ['Titulos', Ingresos+'ingtitpre'],
//          ['Asignaci&oacute;n Inicial', Ingresos+'ingasiini'],
          ['Contribuyentes', Ingresos+'ingdatcon'],
          ['Tipos de Ingresos', Ingresos+'ingdeftiping'],
        ],
        ['Registro de Ingresos', Ingresos+'ingreging'],
//        ['Ejecuci&oacute;n Global', Ingresos+'ingejeglo'],
        ['Reclasificaci&oacute;n de Ingresos', Ingresos+'ingreclaing'],
//        ['Ajuste de Ingresos', Ingresos+'ingajustenew'],
        ['Traslados', Ingresos+'ingtrasla'],
//        ['Adiciones Disminuciones', Ingresos+'ingadidis'],
      ],
    ],
  ],
];


var TREE_ITEMSCOM_OBR = [
  ['SIGA', null,
    ['Obras y Contrato', null,
      ['Definiciones Generales', null,
        ['Registro de Informaci&oacute;n del Sistema', null,
          ['Recaudos', Obras+'oycdefrec'],
          ['Retenciones', Obras+'oycdefret'],
          ['Unidades', Obras+'oycdefuni'],
          ['Divisi&oacute;nTerritorial', null,
             ['Pais', Obras+'oycdefdivpai'],
             ['Estado', Obras+'oycdefdivest'],
             ['Ciudad', Obras+'oycdefdivciu'],
       ['Municipio', Obras+'oycdefdivmun'],
       ['Parroquia', Obras+'oycdefdivpar'],
        ['Sector', Obras+'oycdefdivsec'],
          ],
        ],
        ['Contratista y Otras Organizaciones', null,
          ['Definiciones de Organismos',  Obras+'oycdeforg'],
          ['Tipos de Organismos', Obras+'oycdeftiporg'],
          ['Cargos', Obras+'oycdefcar'],
          ['Profesiones', Obras+'oycdefpro'],
          ['Empleados', Obras+'oycdefper'],
          ['Equipos', Obras+'oycdefequ'],
          ['Especialidades', Obras+'oycdefesp'],
        ],
      ],
      ['Atenci&oacute;n al Ciudadano', null,
         ['Datos del Solicitante', Obras+'oycdatsol'],
         ['Registrar Solicitud', Obras+'oycregsol'],
         ['Responder', Obras+'oycressol'],
         ['Solicitudes', null,
           ['Tipos de Solicitudes', Obras+'oycdeftipsol'],
           ['Tipos de Solicitantes', Obras+'oycdeftipste'],
         ],

      ],
      ['Obras', null,
      ['Partidas', Obras+'oycdefpar'],
          ['Tipos de Obras', Obras+'oycdeftipobr'],
          ['Detalles de Obras', null,
        ['Formulaci&oacute;n de Presupuesto', Obras+'oycforotrcrepre'],
            ['Situaci&oacute;n de Obras', Obras+'oycsitobr'],
            ['Registro de Obras', Obras+'oycdesobr'],
          ],
        ['Inspecciones', null,
          ['Registro de Inspecciones',  Obras+'oycinscon'],
        ],
        ['Actas', null,
          ['Tipos de Actas', Obras+'oycdeftipact'],
          ['Registro de Actas', Obras+'oycregact'],
        ],
        ['Valuaciones', null,
          ['Registro de Valuaciones', Obras+'oycval'],
          ['Tipos de Valuaci&oacute;n', Obras+'oycdeftipval'],
        ],


        ['Contratos', null,
          ['Definiciones de Contratistas', Obras+'oycregpro'],
          ['Tipos de Profesionales', Obras+'oycdeftippro'],
          ['Tarifas por Tipo de Profesionales', Obras+'oyctartip'],
      ['Registro de Contratos', Obras+'oycdescon'],
      ['Situaci&oacute;n del Contrato',  Obras+'oycsitcon'],
        ],
      ],
    ],
  ],
];

var TREE_ITEMSCOM_BIE = [
  ['SIGA', null,
    ['Bienes Nacionales', null,
      ['Definiciones',null,
        ['Definici&oacute;n de Empresa', Bienes+'biedefemp'],
        ['Definici&oacute;n de Ubicaci&oacute;n', Bienes+'biedefubi'],
        ['Definici&oacute;n de Proveedores', Compras+'almregpro'],
        ['Definici&oacute;n de Activos', Bienes+'biecatact'],
        ['Definici&oacute;n de Disposici&oacute;n', Bienes+'biedefdis'],
        ['Definici&oacute;n de Motivos de Disposici&oacute;n', Bienes+'biedefmotdis'],
        ['Definici&oacute;n de Partidas', Bienes+'biedefpar'],
        ['Definici&oacute;n de Clasificaci&oacute;n Funcional', Bienes+'biedefclafun'],
        ['Definici&oacute;n de Cobertura Para Seguros', Bienes+'biecobseg'],
      ],
      ['Registro de Activos',null,
        ['Registro Muebles', Bienes+'bieregactmued'],
        ['Registro Inmuebles', Bienes+'bieregactinmd'],
      ],
      ['Disposici&oacute;n de Activos',null,
        ['Disposici&oacute;n de Muebles', Bienes+'biedisactmuenew'],
        ['Disposici&oacute;n de Inmuebles', Bienes+'biedisactinm'],
      ],
      ['Registro de Seguros',null,
        ['Seguros de Muebles', Bienes+'bieregsegmue'],
        ['Seguros de Inmuebles', Bienes+'bieregseginm'],
      ],
      ['Contabilidad de Activos',null,
        ['Tabla de IPC', Bienes+'bieipcact'],
        ['Definici&oacute;n Contable',null,
          ['Definici&oacute;n Contable de Muebles', Bienes+'biedefconm'],
          ['Definici&oacute;n Contable de Muebles por Lotes', Bienes+'biedefconlotm'],
          ['Definici&oacute;n Contable de Inmuebles', Bienes+'biedefconi'],
          ['Definici&oacute;n Contable de Inmuebles por Lotes', Bienes+'biedefconloti'],
        ],
        ['Revalorizaci&oacute;n', Bienes+'bieajuinf'],
      ],
      ['Reportes',null,
        ['Generales', null,
         ['Cat&aacute;logo de Activos', ReportesBienes+'BNRDEFACT.php'],
         ['Cat&aacute;logo de Ubicaciones', ReportesBienes+'BNRUBICA.php'],
         ['Cat&aacute;logo de Disposici&oacute;n', ReportesBienes+'BNRDEFFIS.php'],
         ['Cat&aacute;logo de Clasificaci&oacute;n Funcional', ReportesBienes+'BieDefClaFun.php'],
        ],
        ['Listados', null,
          ['Listado de Bienes Muebles', ReportesBienes+'BNRLISBIEMUE.php'],
          ['Listado de Bienes Inmuebles', ReportesBienes+'BNRLISBIEINM.php'],
          ['Listado de Bienes Inmuebles', ReportesBienes+'BNRLISBIEINM.php'],
          ['Listado de Bienes Muebles(Ubicaci&oacute;n)', ReportesBienes+'BNRLISMUE.php'],
          ['Listado de Bienes Inmuebles(Ubicaci&oacute;n)', ReportesBienes+'BNRLISINM.php'],
          ['Listado de IPC', ReportesBienes+'BNRIPCACT.php'],
        ],
        ['Disposici&oacute;n Activos', null,
          ['Disposici&oacute;n Activos Muebles', ReportesBienes+'BNRDISBIEMUE.php'],
          ['Disposici&oacute;n Activos Inmuebles', ReportesBienes+'BNRDISBIEINM.php'],
        ],
        ['Seguro Activos', null,
          ['Seguro  Activos Muebles', ReportesBienes+'BNRSEGBIEMUE.php'],
          ['Seguro  Activos Inmuebles', ReportesBienes+'BNRSEGBIEINM.php'],
        ],
        ['Revalorizaci&oacute;n', null,
          ['Revalorizaci&oacute;n de Bienes Muebles', ReportesBienes+'BNRLISBIEMUEREV.php'],
          ['Revalorizaci&oacute;n de Bienes Inmuebles', ReportesBienes+'BNRLISBIEINMREV.php'],
        ],
        ['Etiquetas', null,
          ['Bienes Muebles', ReportesBienes+'BNRETQMUE.php'],
          ['Bienes Inmuebles', ReportesBienes+'BNRETQINM.php'],
        ],
      ],
      ['Mantenimiento',null,
        ['Cierre de Mes', Bienes+'bieciemesdan'],
      ],



    ],
   ],
];


var TREE_ITEMSCOM_HAC = [
  ['SIGA', null,
    ['Hacienda Municipal', null,
      ['Definiciones Espec&iacute;ficas',null,
        ['Definiciones de la Alcald&iacute;a', Hacienda+'facdefespins'],
        ['Cat&aacute;logo de Fuentes de Ingresos', Hacienda+'facfueing'],
        ['Cat&aacute;logo de Presupuesto de Ingresos', Hacienda+'fctiting'],
        ['Definici&oacute;n de Recaudos', Compras+'almregrec'],
        ['Definici&oacute;n de Tasas de Inter&eacute;s Bancarios', Hacienda+'facdefesptasban'],
        ['Definiciones para las Fuentes de Ingreso',null,
          ['Actividades Economicas',null,
            ['Rango en Bs. para el pago de Impuestos', Hacienda+'facranpagimp'],
            ['Actividades Comerciales', Hacienda+'facdefactcom'],
          ],
          ['Inmuebles',null,
            ['Uso de Inmuebles', Hacienda+'facusoinm'],
            ['Caracteristicas de Inmuebles', Hacienda+'faccarinm'],
            ['Situaciones Juridicas de Inmuebles', Hacienda+'facsitjurinm'],
            ['Catastro',null,
              ['Codigo Catastral Fiscal', Hacienda+'faccodcatfis'],
              ['Catastro con Fines Fiscales', Hacienda+'faccatfinfis'],
//              ['Cuadro para Calculo del Impuesto', Hacienda+'facranpaginm'],
            ],
          ],
        ],
        ['Tipos de Pagos', Hacienda+'facdefesptippag'],
        ['Tipos de Solvencias', Hacienda+'facdefsol'],
        ['Rutas', Hacienda+'facdefrut'],
        ['Definiciones de la Alcald&iacute;a', Hacienda+'facdefespins'],
      ],
      ['Atenci&oacute;n al Contribuyente',null,
        ['Registro de Cajeros', Hacienda+'fcajero'],
        ['Registro de Contribuyente', Hacienda+'facdatcon'],
        ['Licencia de Actividades Economicas',null,
          ['Solicitud', Hacienda+'facpicsollic'],
//          ['Otorgamiento', Hacienda+'Facpiclic'],
        ],
        ['Inmuebles Urbanos', Hacienda+'facinmreg'],
        ['Estado de Cuenta Integral', Hacienda+'facestcueint'],
//        ['Estado de Cuenta por Referencia', Hacienda+'facestcueintref'],
//        ['Solvencias', Hacienda+'facsolvencia'],
        ['Reparos Fiscales', Hacienda+'facrepfisliq'],
      ],
      ['Declaraci&oacute;n/Liquidaci&oacute;n',null,
        ['Actividades Econ&oacute;micas', Hacienda+'facpicliq'],
//        ['Inmuebles Urbanos', Hacienda+'facinmdec'],
        ['Otros Ingresos', Hacienda+'facotringreg'],
      ],
      ['Recaudaci&oacute;n',null,
        ['Convenios de Pago', Hacienda+'facconvenio'],
        ['Pagos', Hacienda+'facrecpag'],
        ['Abonos', Hacienda+'facabonos'],
        ['Deudas', Hacienda+'facrecdeu'],
//        ['Actualizacion de Deudas', Hacienda+'facactdeuret'],
        ['Generar Comprobante Contable', Hacienda+'facingresos'],
      ],
    ],
   ],
];

var TREE_ITEMSCOM_DOCFINAN = [
  ['SIGA', null,
    ['Documentos Financieros', null,
      ['Definiciones',null,
        ['Usuarios', Documentos+'docusu'],
        ['Unidades', Documentos+'docuni'],
        ['Asignaci&oacute;n de Tablas', Documentos+'doctab'],
        ['Ruta de Documentos', Documentos+'docrut'],
      ],
      ['Documentos',null,
        ['Pendientes', Documentos+'docpen/pendientes'],
      ],
      ['Reportes',null,
        ['Documentos', ReportesDocumentos+'repdoc.php'],
        ['Seguimiento de Documentos', ReportesDocumentos+'repseg.php'],
        ['Usuarios', ReportesDocumentos+'repusu.php'],
        ['Unidades', ReportesDocumentos+'repuni.php'],
        ['Asignaci&oacute;n de Tablas', ReportesDocumentos+'repasitab.php'],
        ['Rutas', ReportesDocumentos+'reprutdoc.php'],
      ],
    ],
   ],
];

var TREE_ITEMSCOM_ACIUDADANO = [
  ['SIGA', null,
    ['Atencion al Ciudadano', null,
      ['Definiciones',null,
        ['Tipos de Ayudas', Aciudadano+'acitipayu'],
        ['Asignar Recaudos a Tipos de Ayudas', Aciudadano+'acirecayu'],
        ['Recaudos', Aciudadano+'acirecaud'],
        ['Unidades', Aciudadano+'aciunidad'],
      ],
      ['Solicitudes',null,
        ['Solicitantes', Aciudadano+'acisolici'],
        ['Ayudas', Aciudadano+'aciayudas'],
        ['Reclamos', Aciudadano+'acireclam'],
        ['Denuncias', Aciudadano+'acidenunc'],
        ['Audiencias', Aciudadano+'aciaudien'],
        ['Estatus de Ayuda', Aciudadano+'acistasol'],
      ],
      ['Atencion',null,
        ['Ayudas', Aciudadano+'aciateayu'],
        ['Reclamos', Aciudadano+'aciaterec'],
        ['Denuncias', Aciudadano+'aciateden'],
        ['Audiencias', Aciudadano+'aciateaud'],
      ],
      ['Reportes',null,
        ['Ayudas', ReportesAciudadano+'ayudas.php'],
        ['Reclamos', ReportesAciudadano+'reclamos.php'],
        ['Denuncias', ReportesAciudadano+'denuncias.php'],
      ],
    ],
   ],
];

var TREE_ITEMS_MAIN = [
  ['SIGA', null,
  //  ['Atencion al Ciudadano', 'principal/menu/m/ciudadanos'],
    ['Bienes Nacionales', 'principal/menu/m/bienes'],
//    ['Contabilidad Presupuestaria', servidor+'/contabilidadpresupuesto/aplicaciones/presupuesto/index.php'],
//    ['Contabilidad Financiera', servidor+'/contabilidadpresupuesto/aplicaciones/contabilidad/index.php'],
   ['Contabilidad Presupuestaria', 'principal/menu/m/presupuesto'],
   ['Contabilidad Financiera', 'principal/menu/m/contabilidad'],
   ['Compras Y Almacen', 'principal/menu/m/compras'],
   ['Control de Documentos', 'principal/menu/m/documentos/'],
   // ['Financiamiento', '/financiamiento/autenticacion_dev.php/principal/menu/m/financiamiento/'],
    ['Formulaci&oacute;n', 'principal/menu/m/formulacion'],
   // ['Hacienda Municipal', 'principal/menu/m/hacienda'],
    ['Ingresos', 'principal/menu/m/ingresos'],
//    ['Inversi&oacute;n y Colocaci&oacute;n', 'principal/menu/m/inv_coloc'],
    ['Recursos Humanos', 'principal/menu/m/nomina'],
   ['Obras y Contratos', 'principal/menu/m/obras'],
    ['Tesorer&iacute;a', 'principal/menu/m/tesoreria'],
      ]
  ];
