<?php
// auto-generated by PropelCidesa
// date: 2008/12/10 15:58:36
?>
    <td><?php echo link_to($faciudad->getNomciu() ? $faciudad->getNomciu() : __('-'), 'faciudad/edit?id='.$faciudad->getId().'&edo='.$faciudad->getFaestadoId()) ?></td>
    <td><?php echo $faciudad->getNomedo() ?></td>
      <td><?php echo $faciudad->getNompai() ?></td>
