<?php
// auto-generated by PropelCidesa
// date: 2008/12/10 14:35:09
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Ciudades',
array()) ?></h1>


<div id="sf_admin_header">
<?php include_partial('faciudad/edit_header', array('faciudad' => $faciudad)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('faciudad/edit_messages', array('faciudad' => $faciudad, 'labels' => $labels)) ?>
<?php include_partial('faciudad/edit_form', array('faciudad' => $faciudad, 'labels' => $labels, 'paises' => $paises, 'estados' => $estados)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('faciudad/edit_footer', array('faciudad' => $faciudad)) ?>
</div>

</div>
