<?php
// auto-generated by sfPropelAdmin
// date: 2008/01/07 16:05:23
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'nomdefconaho/edit?id='.$npconaho->getId().'&nomina='.$npconaho->getCodnom()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'nomdefconaho/delete?id='.$npconaho->getId().'&nomina='.$npconaho->getCodnom(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
</ul>
</td>
