<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/20 21:30:53
?>
<?php echo form_tag('nomdefespperfil/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($npperfil, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">
<legend>Perfiles</legend>
<div class="form-row">
  <?php echo label_for('npperfil[codperfil]', __($labels['npperfil{codperfil}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npperfil{codperfil}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npperfil{codperfil}')): ?>
    <?php echo form_error('npperfil{codperfil}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npperfil, 'getCodperfil', array (
  'size' => 20,
  'control_name' => 'npperfil[codperfil]',
  'maxlength' => 4,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npperfil[desperfil]', __($labels['npperfil{desperfil}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npperfil{desperfil}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npperfil{desperfil}')): ?>
    <?php echo form_error('npperfil{desperfil}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npperfil, 'getDesperfil', array (
  'size' => 80,
  'control_name' => 'npperfil[desperfil]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('npperfil' => $npperfil)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($npperfil->getId()): ?>
<?php echo button_to(__('delete'), 'nomdefespperfil/delete?id='.$npperfil->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
