<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/11 11:19:15
?>
<?php echo form_tag('facdatcon/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fcconrep, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
<table border="0">
  <tr>
    <th><?php echo label_for('fcconrep[rifcon]', __($labels['fcconrep{rifcon}']), 'class="required" ' ) ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{rifcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{rifcon}')): ?>
    <?php echo form_error('fcconrep{rifcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getRifcon', array (
  'size' => 20,
  'control_name' => 'fcconrep[rifcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th><?php echo label_for('fcconrep[nitcon]', __($labels['fcconrep{nitcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{nitcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{nitcon}')): ?>
    <?php echo form_error('fcconrep{nitcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getNitcon', array (
  'size' => 20,
  'control_name' => 'fcconrep[nitcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
  </tr>
</table>  
</div>

<div class="form-row">
  <?php echo label_for('fcconrep[nomcon]', __($labels['fcconrep{nomcon}']), 'class="required" style="width: 150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{nomcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{nomcon}')): ?>
    <?php echo form_error('fcconrep{nomcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getNomcon', array (
  'size' => 80,
  'control_name' => 'fcconrep[nomcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>


<div class="form-row">
<table border="0">
  <tr>
    <th><fieldset id="sf_fieldset_none" class="">
<legend>Nacionalidad</legend>
<div class="form-row">
<?
if ($fcconrep->getNaccon()=='V')	{
  ?><?php echo radiobutton_tag('fcconrep[naccon]', 'V', true)        ."Venezolano(a)".'&nbsp;&nbsp;';
		  echo radiobutton_tag('fcconrep[naccon]', 'E', false)."   Extranjero(a)";?>
		<?

}else{
	echo radiobutton_tag('fcconrep[naccon]', 'V', false)        ."Venezolano(a)".'&nbsp;&nbsp;';
	echo radiobutton_tag('fcconrep[naccon]', 'E', true)."   Extranjero(a)";

} ?> </div></fieldset></th>
<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th><fieldset id="sf_fieldset_none" class="">
<legend>Tipo</legend>
<div class="form-row">
<?
if ($fcconrep->getTipcon()=='N')	{
  ?><?php echo radiobutton_tag('fcconrep[tipcon]', 'N', true)        ."Natural".'&nbsp;&nbsp;';
		  echo radiobutton_tag('fcconrep[tipcon]', 'J', false)."   Jurídica";?>
		<?

}else{
	echo radiobutton_tag('fcconrep[tipcon]', 'N', false)        ."Natural".'&nbsp;&nbsp;';
	echo radiobutton_tag('fcconrep[tipcon]', 'J', true)."   Jurídica";

} ?></div></fieldset></th>
  </tr>
</table> 
</div>
</fieldset>


<?php tabMainJS("tp1","tabPane1", "tabPage1", 'Datos Personales');?>
<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
  <?php echo label_for('fcconrep[dircon]', __($labels['fcconrep{dircon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{dircon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{dircon}')): ?>
    <?php echo form_error('fcconrep{dircon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getDircon', array (
  'size' => 80,
  'control_name' => 'fcconrep[dircon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcconrep[codpar]', __($labels['fcconrep{codpar}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{codpar}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{codpar}')): ?>
    <?php echo form_error('fcconrep{codpar}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>
  <?php echo select_tag('fcconrep[codpar]', options_for_select($partidas,$fcconrep->getCodpar(), 'include_custom=Seleccione Uno')); ?>  
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcconrep[ciucon]', __($labels['fcconrep{ciucon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{ciucon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{ciucon}')): ?>
    <?php echo form_error('fcconrep{ciucon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getCiucon', array (
  'size' => 60,
  'control_name' => 'fcconrep[ciucon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
<table border=0 >
<tr>
	<th><?php echo label_for('fcconrep[cpocon]', __($labels['fcconrep{cpocon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{cpocon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{cpocon}')): ?>
    <?php echo form_error('fcconrep{cpocon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getCpocon', array (
  'size' => 20,
  'control_name' => 'fcconrep[cpocon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
	<th> <?php echo label_for('fcconrep[apocon]', __($labels['fcconrep{apocon}']), 'class="required" style="width: 150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{apocon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{apocon}')): ?>
    <?php echo form_error('fcconrep{apocon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getApocon', array (
  'size' => 20,
  'control_name' => 'fcconrep[apocon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
</tr>
</table>  
</div>
</fieldset>
<br>
<fieldset id="sf_fieldset_none" class="">
<div class="form-row">
<table border=0 >
<tr>
	<th><?php echo label_for('fcconrep[telcon]', __($labels['fcconrep{telcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{telcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{telcon}')): ?>
    <?php echo form_error('fcconrep{telcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getTelcon', array (
  'size' => 30,
  'control_name' => 'fcconrep[telcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
	<th><?php echo label_for('fcconrep[emacon]', __($labels['fcconrep{emacon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{emacon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{emacon}')): ?>
    <?php echo form_error('fcconrep{emacon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getEmacon', array (
  'size' => 50,
  'control_name' => 'fcconrep[emacon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
</tr>
</table>  
</div>

<div class="form-row">
<table border=0 >
<tr>
	<th><?php echo label_for('fcconrep[faxcon]', __($labels['fcconrep{faxcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{faxcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{faxcon}')): ?>
    <?php echo form_error('fcconrep{faxcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getFaxcon', array (
  'size' => 20,
  'control_name' => 'fcconrep[faxcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
<th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
	<th><?php echo label_for('fcconrep[urlcon]', __($labels['fcconrep{urlcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcconrep{urlcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcconrep{urlcon}')): ?>
    <?php echo form_error('fcconrep{urlcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcconrep, 'getUrlcon', array (
  'size' => 50,
  'control_name' => 'fcconrep[urlcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div></th>
</tr>
</table>  
</div>
</fieldset>

<?php tabPageOpenClose("tp1", "tabPage2", 'Recaudos Consignados');?>

<form name="form1" id="form1">
<?
echo grid_tag($obj);
?>
</form>

<?php tabInit("tp1", "0");?>

<?php include_partial('edit_actions', array('fcconrep' => $fcconrep)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fcconrep->getId()): ?>
<?php echo button_to(__('delete'), 'facdatcon/delete?id='.$fcconrep->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
