<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/16 17:33:55
?>
<?php echo form_tag('vacliquidacion/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($nphojint, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('nphojint[codemp]', __($labels['nphojint{codemp}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('nphojint{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('nphojint{codemp}')): ?>
    <?php echo form_error('nphojint{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($nphojint, 'getCodemp', array (
  'size' => 20,
  'control_name' => 'nphojint[codemp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('nphojint[nomemp]', __($labels['nphojint{nomemp}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('nphojint{nomemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('nphojint{nomemp}')): ?>
    <?php echo form_error('nphojint{nomemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($nphojint, 'getNomemp', array (
  'size' => 80,
  'control_name' => 'nphojint[nomemp]',
  'maxlength' => 100,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('nphojint[feccal]', __($labels['nphojint{feccal}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('nphojint{feccal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('nphojint{feccal}')): ?>
    <?php echo form_error('nphojint{feccal}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($nphojint, 'getFeccal', array (
  'disabled' => true,
  'control_name' => 'nphojint[feccal]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('nphojint[fecret]', __($labels['nphojint{fecret}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('nphojint{fecret}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('nphojint{fecret}')): ?>
    <?php echo form_error('nphojint{fecret}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($nphojint, 'getFecret', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'nphojint[fecret]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('nphojint[codnom]', __($labels['nphojint{codnom}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('nphojint{codnom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('nphojint{codnom}')): ?>
    <?php echo form_error('nphojint{codnom}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($nphojint, 'getCodnom', array (
  'disabled' => true,
  'control_name' => 'nphojint[codnom]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>



<div class="grid01" id="grid01">
<fieldset><legend>Detalles del Servicio</legend>
<table border="0" class="sf_admin_list">
<?
$titulo=array(0 => 'Codigo del Servicio', 1 => 'Descripcion', 2 => 'Cod.Unidad', 3 => 'Fecha Realizado', 4 => 'Nombre Empleado', 5 => 'Observacion');
if ( count($rs)>0){
	$i=0;
	foreach ($rs as $k=>$fila) {
		$i++;
		if($i==1){?>
	<thead>
		<tr>
		<? foreach ($fila as $key => $value){?>
			<th><?=$titulo[$key]?></th>
			<? }?>
		</tr>
	</thead>
	<? }?>
	<tr>
	<? foreach ($fila as $key => $value){?>
		<td><?=$value?></td>
		<? }?>
	</tr>
	<? }
}
?>
</table>
</fieldset>
</div>s



</fieldset>

<?php include_partial('edit_actions', array('nphojint' => $nphojint)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($nphojint->getId()): ?>
<?php echo button_to(__('delete'), 'vacliquidacion/delete?id='.$nphojint->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
