<?php
// auto-generated by PropelCidesa
// date: 2008/12/16 09:07:38
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Precios',
array()) ?></h1>


<div id="sf_admin_header">
<?php include_partial('faactpre/edit_header', array('faartpvp' => $faartpvp)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('faactpre/edit_messages', array('faartpvp' => $faartpvp, 'labels' => $labels)) ?>
<?php include_partial('faactpre/edit_form', array('faartpvp' => $faartpvp, 'labels' => $labels, 'obj' => $obj, 'longitud' => $longitud, 'mascaraarticulo' => $mascaraarticulo)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('faactpre/edit_footer', array('faartpvp' => $faartpvp)) ?>
</div>

</div>
