<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/15 22:36:40
?>
<?php echo form_tag('pagretcon/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($opretcon, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">


<fieldset>
<legend>Datos del Concepto</legend>
<div class="form-row">
  <?php echo label_for('opretcon[codcon]', __($labels['opretcon{codcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opretcon{codcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opretcon{codcon}')): ?>
    <?php echo form_error('opretcon{codcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opretcon, 'getCodcon', array (
  'size' => 6,
  'control_name' => 'opretcon[codcon]',
  'maxlength' => '3,',
)); echo $value ? $value : '&nbsp;' ?>&nbsp;
<?php echo button_to('...','#')?>&nbsp;</n>
<?php echo label_for('des1','Descripcion','')?>&nbsp;
<?php echo input_tag('descon',$descon,'size=35,disabled=true'); ?>
    </div>
</div>
</fieldset>

<fieldset>
<legend>Datos de la Nomina</legend>
<div class="form-row">
  <?php echo label_for('opretcon[codnom]', __($labels['opretcon{codnom}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opretcon{codnom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opretcon{codnom}')): ?>
    <?php echo form_error('opretcon{codnom}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opretcon, 'getCodnom', array (
  'size' => 6,
  'control_name' => 'opretcon[codnom]',
  'maxlength' => '3,',
)); echo $value ? $value : '&nbsp;' ?>&nbsp;
<?php echo button_to('...','#')?>&nbsp;
<?php echo label_for('des2','Descripcion','')?>&nbsp;
<?php echo input_tag('desnom',$desnom,'size=35,disabled=true'); ?>
    </div>
</div>
</fieldset>

<fieldset>
<legend>Datos del Tipo de Retencion</legend>
<div class="form-row">
  <?php echo label_for('opretcon[codtip]', __($labels['opretcon{codtip}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opretcon{codtip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opretcon{codtip}')): ?>
    <?php echo form_error('opretcon{codtip}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opretcon, 'getCodtip', array (
  'size' => 6,
  'control_name' => 'opretcon[codtip]',
  'maxlength' => '3,',
)); echo $value ? $value : '&nbsp;' ?>&nbsp;
<?php echo button_to('...','#')?>&nbsp;
<?php echo label_for('des3','Descripcion','')?>&nbsp;
<?php echo input_tag('desret',$desret,'size=35,disabled=true'); ?>
    </div>
</div>
</fieldset>


</fieldset>

<?php include_partial('edit_actions', array('opretcon' => $opretcon)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($opretcon->getId()): ?>
<?php echo button_to(__('delete'), 'pagretcon/delete?id='.$opretcon->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
