<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/07 11:41:49
?>
<?php echo form_tag('facranpagimp/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fcdefpgi, 'getId') ?>



<form name="form1" id="form1">
<?
echo grid_tag($obj);
?>
</form>



<?php include_partial('edit_actions', array('fcdefpgi' => $fcdefpgi)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fcdefpgi->getId()): ?>
<?php echo button_to(__('delete'), 'facranpagimp/delete?id='.$fcdefpgi->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
