<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/24 23:51:35
?>
<?php echo form_tag('vachistorico_lote/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($npvacdisfrute, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
<?php echo label_for('npvacdisfrute[perini]', __($labels['npvacdisfrute{perini}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npvacdisfrute{perini}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npvacdisfrute{perini}')): ?>
    <?php echo form_error('npvacdisfrute{perini}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npvacdisfrute, 'getPerini', array (
  'size' => 20,
  'control_name' => 'npvacdisfrute[perini]',
)); echo $value ? $value : '&nbsp;' ?> &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; 
<strong>Periodo Hasta:</strong>
<?php $value = object_input_tag($npvacdisfrute, 'getPerfin', array (
'size' => 20,
'control_name' => 'npvacdisfrute[perfin]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>


<div class="form-row">
<?php echo label_for('npvacdisfrute[codemp]', __($labels['npvacdisfrute{codemp}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npvacdisfrute{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npvacdisfrute{codemp}')): ?>
    <?php echo form_error('npvacdisfrute{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npvacdisfrute, 'getCodemp', array (
  'size' => 20,
  'control_name' => 'npvacdisfrute[codemp]',
  )); echo $value ? $value : '&nbsp;' ?> 
  &nbsp;
  <?php echo button_to('...','#'); ?>
  &nbsp;
  <?php $value = object_input_tag($npvacdisfrute, 'getNomemp', array (
  'size' => 50,
  'control_name' => 'npvacdisfrute[codemp]',
  'disabled' => 'true',
  )); echo $value ? $value : '&nbsp;' ?>

    </div>
</div>

<div class="form-row">
<strong>Dias a Disfrutar</strong>
&nbsp;
  <?php $value = object_input_tag($npvacdisfrute, 'getDiasdisfutar', array (
	'size' => 7,
	'control_name' => 'npvacdisfrute[diasdisfutar]',
	)); echo $value ? $value : '&nbsp;' ?> &nbsp; &nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>Dias Disfrutados</strong>
&nbsp;
	<?php $value = object_input_tag($npvacdisfrute, 'getDiasdisfrutados', array (
	'size' => 7,
	'control_name' => 'npvacdisfrute[diasdisfrutados]',
	)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>Dias por Disfrutrar</strong>
	<?php echo input_tag('pordisfrutar','','size=7,disabled=true') ?>
</div>
</fieldset>

<?php include_partial('edit_actions', array('npvacdisfrute' => $npvacdisfrute)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($npvacdisfrute->getId()): ?>
<?php echo button_to(__('delete'), 'vachistorico_lote/delete?id='.$npvacdisfrute->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
