<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/25 16:05:26
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Registro de Faltas y Permisos por Nomina en Lote', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('nomfalperlot/edit_header', array('npnomina' => $npnomina)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('nomfalperlot/edit_messages', array('npnomina' => $npnomina, 'labels' => $labels)) ?>
<?php include_partial('nomfalperlot/edit_form', array('npnomina' => $npnomina, 'detalles' => $detalles, 'nuevo' => $nuevo, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('nomfalperlot/edit_footer', array('npnomina' => $npnomina)) ?>
</div>

</div>
