<?php
// auto-generated by PropelCidesa
// date: 2010/09/28 11:50:42
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: listSuccess.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">
<?php if($sf_user->getAttribute('nomsalint','','presnomregsalint')=='S') { ?>
    <h1><?php echo __('Salario Base Por Contrato Individual',
    array()) ?></h1>
<?php } else{ ?>
    <h1><?php echo __('Salario Integral Por Contrato Individual',
array()) ?></h1>
<?php } ?>
<div id="sf_admin_header">
<?php include_partial('presnomregsalintind/list_header', array('pager' => $pager)) ?>
<?php include_partial('presnomregsalintind/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
<?php include_partial('filters', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_content">
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('presnomregsalintind/list', array('pager' => $pager)) ?>
<?php endif; ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('presnomregsalintind/list_footer', array('pager' => $pager)) ?>
</div>

</div>
