<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/26 19:04:45
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Modificar Cargos', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('nomdefespcar/edit_header', array('npcargos' => $npcargos)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('nomdefespcar/edit_messages', array('npcargos' => $npcargos, 'labels' => $labels)) ?>
<?php include_partial('nomdefespcar/edit_form', array('npcargos' => $npcargos, 'grid' => $grid ,
 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('nomdefespcar/edit_footer', array('npcargos' => $npcargos)) ?>
</div>

</div>
