<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/05 11:49:07
?>
<?php echo form_tag('oycdefret/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($octipret, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('octipret[codtip]', __($labels['octipret{codtip}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('octipret{codtip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('octipret{codtip}')): ?>
    <?php echo form_error('octipret{codtip}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($octipret, 'getCodtip', array (
  'size' => 20,
  'control_name' => 'octipret[codtip]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('octipret[destip]', __($labels['octipret{destip}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('octipret{destip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('octipret{destip}')): ?>
    <?php echo form_error('octipret{destip}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($octipret, 'getDestip', array (
  'size' => 80,
  'control_name' => 'octipret[destip]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
<strong>Maneja Sustraendo</strong>
<?php 
if($octipret->getPorret()<>0) 
{
	$val = true;
	$val1 = false;
}
elseif($octipret->getPorret()==0)
{
	$val1 = true;
	$val = false;
}
else
{
		$val1 = false;
		$val = false;
}?>
<?php echo "Si ".radiobutton_tag('octipret[porret]', 'S', $val) ?>
&nbsp; 
<?php echo "No ".radiobutton_tag('octipret[porret]', 'N', !$val1) ?>
</div>


<div class="form-row"><?php echo label_for('octipret[porret]', __($labels['octipret{porret}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('octipret{porret}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('octipret{porret}')): ?> <?php echo form_error('octipret{porret}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($octipret, 'getPorret', array (
  'size' => 7,
  'control_name' => 'octipret[porret]',
  )); echo $value ? $value : '&nbsp;' ?>&nbsp;<strong>%</strong></div>
<br>
<?php echo label_for('octipret[basimp]', __($labels['octipret{basimp}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('octipret{basimp}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('octipret{basimp}')): ?> <?php echo form_error('octipret{basimp}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($octipret, 'getBasimp', array (
  'size' => 7,
  'control_name' => 'octipret[basimp]',
)); echo $value ? $value : '&nbsp;' ?>&nbsp;<strong>%</strong></div>
<br>

<?php 
if($octipret->getStamon()=='N')
{
	$val = true;
	$val1 = false;
}
elseif($octipret->getStamon()=='S')
{
	$val1 = true;
	$val = false;
}
elseif($octipret->getStamon()=='')
{
	$val1 = false;
	$val = false;
}?> <?php echo "Monto Neto ".radiobutton_tag('octipret[stamon]', 'S', $val) ?>
&nbsp; <?php echo "Monto Total ".radiobutton_tag('octipret[stamon]', 'N', !$val1) ?>

</div>

<div class="form-row"><?php echo label_for('octipret[codcon]', __($labels['octipret{codcon}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('octipret{codcon}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('octipret{codcon}')): ?> <?php echo form_error('octipret{codcon}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($octipret, 'getCodcon', array (
  'size' => 32,
  'control_name' => 'octipret[codcon]',
  )); echo $value ? $value : '&nbsp;' ?> &nbsp; <?php echo button_to('...','#')?></div>
</div>

<div class="form-row"><?php echo label_for('octipret[descta]', __($labels['octipret{descta}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('octipret{descta}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('octipret{descta}')): ?> <?php echo form_error('octipret{descta}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($octipret, 'getDescta', array (
  'disabled' => true,
  'control_name' => 'octipret[descta]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>
</fieldset>

<?php include_partial('edit_actions', array('octipret' => $octipret)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($octipret->getId()): ?>
<?php echo button_to(__('delete'), 'oycdefret/delete?id='.$octipret->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
