<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/15 22:19:10
?>
<?php echo form_tag('almregrgo/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($carecarg, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<fieldset id="sf_fieldset_none" class="">
<legend> Datos del Recargo</legend>
<div class="form-row"><?php echo label_for('carecarg[codrgo]', __($labels['carecarg{codrgo}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('carecarg{codrgo}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('carecarg{codrgo}')): ?> <?php echo form_error('carecarg{codrgo}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($carecarg, 'getCodrgo', array (
'size' => 20,
'control_name' => 'carecarg[codrgo]',
)); echo $value ? $value : '&nbsp;' ?></div>


<?php echo label_for('carecarg[nomrgo]', __($labels['carecarg{nomrgo}']), 'class="required"') ?>
<div
	class="content<?php if ($sf_request->hasError('carecarg{nomrgo}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('carecarg{nomrgo}')): ?> <?php echo form_error('carecarg{nomrgo}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($carecarg, 'getNomrgo', array (
  'size' => 50,
  'control_name' => 'carecarg[nomrgo]',
)); echo $value ? $value : '&nbsp;' ?></div>

</div>
</fieldset>



<div class="form-row">
<fieldset id="sf_fieldset_none" class=""><legend> <? echo $labels['carecarg{tiprgo}']; ?></legend>
<?  if ($carecarg->getTiprgo()=='M'){
	echo radiobutton_tag('checkbox1','M', true) .'&nbsp;&nbsp;'. "Puntual"."<br>";
	echo radiobutton_tag('checkbox1','P', false) .'&nbsp;&nbsp;'. "Conceptual"."<br>";

}elseif ($carecarg->getTiprgo()=='P'){
	echo radiobutton_tag('checkbox1','M', false) .'&nbsp;&nbsp;'. "Puntual"."<br>";
	echo radiobutton_tag('checkbox1','P', true) .'&nbsp;&nbsp;'. "Conceptual"."<br>";

}else{
	echo radiobutton_tag('checkbox1','M', false) .'&nbsp;&nbsp;'. "Puntual"."<br>";
	echo radiobutton_tag('checkbox1','P', false) .'&nbsp;&nbsp;'. "Conceptual"."<br>";

}
?></fieldset>
</div>

<div class="form-row"><?php echo label_for('carecarg[monrgo]', __($labels['carecarg{monrgo}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('carecarg{monrgo}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('carecarg{monrgo}')): ?> <?php echo form_error('carecarg{monrgo}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($carecarg, 'getMonrgo', array (
'size' => 7,
'control_name' => 'carecarg[monrgo]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>



<fieldset id="sf_fieldset_none" class="">
<legend> Datos del Titulo Presupuestario</legend>
<div class="form-row"><?php echo label_for('carecarg[codpre]', __($labels['carecarg{codpre}']), 'class="required" ') ?>
<div
	class="content<?php if ($sf_request->hasError('carecarg{codpre}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('carecarg{codpre}')): ?> <?php echo form_error('carecarg{codpre}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($carecarg, 'getCodpre', array (
  'size' => 32,
  'control_name' => 'carecarg[codpre]',
  )); echo $value ? $value : '&nbsp;' ?>
  
  <?php echo button_to('...','#')?>
 </div>
<div>

<?php echo label_for('nombre', 'Nombre', 'class="required" ') ?>
<?php if (isset($nompre)): ?> 
<?php echo input_tag('nompre',$nompre,'size=50,disabled=true'); ?>
<?php endif; ?>

</div>
</div>
</fieldset>

<fieldset id="sf_fieldset_none" class="">
<legend> Datos de la Cuenta Contable</legend>
<div class="form-row"><?php echo label_for('carecarg[codcta]', __($labels['carecarg{codcta}']), 'class="required"') ?>
<div
	class="content<?php if ($sf_request->hasError('carecarg{codcta}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('carecarg{codcta}')): ?> <?php echo form_error('carecarg{codcta}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($carecarg, 'getCodcta', array (
  'size' => 32,
  'control_name' => 'carecarg[codcta]',
)); echo $value ? $value : '&nbsp;' ?>

<?php echo button_to('...','#')?>
</div>

<?php echo label_for('nombre', 'Nombre', 'class="required" ') ?>
<?php if (isset($descta)): ?>
	 <?php echo input_tag('descta',$descta,'size=50,disabled=true'); ?>
<?php endif; ?>

</div>
</fieldset>
</fieldset>

<?php include_partial('edit_actions', array('carecarg' => $carecarg)) ?>

</form>

<ul class="sf_admin_actions">
	<li class="float-left">
	<?php if ($carecarg->getId()): ?> 
	<?php echo button_to(__('delete'), 'almregrgo/delete?id='.$carecarg->getId(), array (
	'post' => true,
	'confirm' => __('Are you sure?'),
	'class' => 'sf_admin_action_delete',
	)) ?>
	<?php endif; ?></li>
</ul>
