<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/09 17:27:37
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Grid', 'Javascript') ?>
<?
echo '<div id="grid">';
	echo grid_tag_v2($fcdprinm->getGrid());
echo '</div>';
?>

