<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/09 12:30:10
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'tabs', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Registro de Abonos a Estados de Cuenta', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('facabonos/edit_header', array('fcabonos' => $fcabonos)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('facabonos/edit_messages', array('fcabonos' => $fcabonos, 'labels' => $labels)) ?>
<?php include_partial('facabonos/edit_form', array('fcabonos' => $fcabonos, 'labels' => $labels, 'fuentes' => $fuentes)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('facabonos/edit_footer', array('fcabonos' => $fcabonos)) ?>
</div>

</div>
