<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/21 18:31:04
?>
<?php echo form_tag('presnomantpre/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($npantpre, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">
<legend>Datos de la Solicitud de Anticipo sobre Prestaciones</legend>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<fieldset id="sf_fieldset_none" class="">
<legend>Datos del Tabajador</legend>
<div class="form-row">
  <?php echo label_for('npantpre[codemp]', __($labels['npantpre{codemp}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npantpre{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npantpre{codemp}')): ?>
    <?php echo form_error('npantpre{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npantpre, 'getCodemp', array (
  'size' => 20,
  'control_name' => 'npantpre[codemp]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;
<?php echo button_to('...','#')?>
&nbsp;
<?php echo input_tag('codigo',$codigo,'size=50,disabled=true') ?>
    </div>
</div>
</fieldset>

<div class="form-row">
  <?php echo label_for('npantpre[monant]', __($labels['npantpre{monant}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npantpre{monant}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npantpre{monant}')): ?>
    <?php echo form_error('npantpre{monant}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npantpre, 'getMonant', array (
  'size' => 7,
  'control_name' => 'npantpre[monant]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npantpre[fecant]', __($labels['npantpre{fecant}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npantpre{fecant}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npantpre{fecant}')): ?>
    <?php echo form_error('npantpre{fecant}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($npantpre, 'getFecant', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'npantpre[fecant]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npantpre[monto]', __($labels['npantpre{monto}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npantpre{monto}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npantpre{monto}')): ?>
    <?php echo form_error('npantpre{monto}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npantpre, 'getMonto', array (
  'size' => 7,
  'control_name' => 'npantpre[monto]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('npantpre' => $npantpre)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($npantpre->getId()): ?>
<?php echo button_to(__('delete'), 'presnomantpre/delete?id='.$npantpre->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
