<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/16 09:43:43
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Proyectos', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('alminvfis/edit_header', array('cainvfis' => $cainvfis)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('alminvfis/edit_messages', array('cainvfis' => $cainvfis, 'labels' => $labels)) ?>
<?php include_partial('alminvfis/edit_form', array('cainvfis' => $cainvfis, 'labels' => $labels, 'rs' => $rs)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('alminvfis/edit_footer', array('cainvfis' => $cainvfis)) ?>
</div>

</div>
