<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/03 15:10:11
?>
<?php echo form_tag('oycval/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($ocregval, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('ocregval[codcon]', __($labels['ocregval{codcon}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{codcon}')): ?> form-error<?php endif; ?>"></div>
  <?php if ($sf_request->hasError('ocregval{codcon}')): ?>
    <?php echo form_error('ocregval{codcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getCodcon', array (
  'size' => 32,
  'control_name' => 'ocregval[codcon]',
)); echo $value ? $value : '&nbsp;' ?>&nbsp; <?php echo button_to('...','#')?>
    &nbsp;&nbsp;&nbsp;
    <strong>Tipo</strong>
   <?php echo select_tag('ocregval[codtipval]', options_for_select($tipos,$ocregval->getCodtipval())) ?>
    &nbsp;&nbsp;&nbsp;
    <strong>Nro</strong> 
    <?php $value = object_input_tag($ocregval, 'getNumval', array (
  'size' => 5,
  'control_name' => 'ocregval[numval]',
)); echo $value ? $value : '&nbsp;' ?>   
&nbsp;&nbsp;&nbsp;
    <strong>Fecha</strong> 
<?php $value = object_input_date_tag($ocregval, 'getFecreg', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'ocregval[fecreg]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?> 
</div>



<div class="form-row">
  <?php echo label_for('ocregval[desobr]', __($labels['ocregval{desobr}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{desobr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregval{desobr}')): ?>
    <?php echo form_error('ocregval{desobr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getDesobr', array (
  'size' => 60,
  'disabled' => true,
  'control_name' => 'ocregval[desobr]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>Del</strong>
<?php $value = object_input_date_tag($ocregval, 'getFecini', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'ocregval[fecini]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
    <br>
    <?php echo label_for('ocregval[nompro]', __($labels['ocregval{nompro}']), 'class="required" ') ?>
     <div class="content<?php if ($sf_request->hasError('ocregval{nompro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregval{nompro}')): ?>
    <?php echo form_error('ocregval{nompro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getNompro', array (
  'size' => 60,
  'disabled' => true,
  'control_name' => 'ocregval[nompro]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>Al</strong>
 <?php $value = object_input_date_tag($ocregval, 'getFecfin', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'ocregval[fecfin]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
<fieldset id="sf_fieldset_none" class="">
<legend>Resumen</legend>
<div class="form-row">
  <strong>Monto Original del Contrato</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getMoncon', array (
  'size' => 7,
  'disabled' => true,
  'control_name' => 'ocregval[moncon]',
)); echo $value ? $value : '&nbsp;' ?>  
</div>

<div class="form-row">
  <strong>Aumentos de Obra (+)</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getAumobr', array (
  'size' => 7,
  'control_name' => 'ocregval[aumobr]',
)); echo $value ? $value : '&nbsp;' ?>    
</div>

<div class="form-row">
  <strong>Disminución de Obra (-)</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getDisobr', array (
  'size' => 7,
  'control_name' => 'ocregval[disobr]',
)); echo $value ? $value : '&nbsp;' ?>  
  </div>   
<div class="form-row">
   <strong>Obras Extras (+)</strong>
   &nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getObrext', array (
  'size' => 7,
  'control_name' => 'ocregval[obrext]',
)); echo $value ? $value : '&nbsp;' ?>   
</div>

<div class="form-row">
  <strong>Monto Total del Contrato</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getMonful', array (
  'size' => 7,
  'control_name' => 'ocregval[monful]',
)); echo $value ? $value : '&nbsp;' ?> 
</div>    
</fieldset>
</div>

<div class="form-row">
<fieldset id="sf_fieldset_none" class="">
<legend>Ejecución de Partidas</legend>
&nbsp;&nbsp;&nbsp;
<form name="form1" id="form1">
<?
echo grid_tag($obj);
?>
</form>

<div class="form-row">
  <?php echo label_for('ocregval[gasree]', __($labels['ocregval{gasree}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{gasree}')): ?> form-error<?php endif; ?>"></div>
  <?php if ($sf_request->hasError('ocregval{gasree}')): ?>
    <?php echo form_error('ocregval{gasree}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getGasree', array (
  'size' => 7,
  'control_name' => 'ocregval[gasree]',
)); echo $value ? $value : '&nbsp;' ?>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <strong>SubTotal sin IVA</strong>
 <?php $value = object_input_tag($ocregval, 'getSubtot', array (
  'size' => 7,
  'control_name' => 'ocregval[subtot]',
)); echo $value ? $value : '&nbsp;' ?> </div>
<br>   
<div class="form-row" align="right">
  <strong>IVA</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getMoniva', array (
  'size' => 7,
  'control_name' => 'ocregval[moniva]',
)); echo $value ? $value : '&nbsp;' ?>    
</div>
<br>
<div class="form-row" align="right">
  <strong>Total con IVA</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('total', '', 'size=20') ?>    
</div>
</div>
</fieldset>
</div>

<div class="form-row">
<fieldset id="sf_fieldset_none" class="">
<legend>Retenciones</legend>
<div class="form-row">
  <strong>Total con IVA(1)</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('total1', '', 'size=20') ?>    
</div>

<div class="form-row">
  <strong>Amortización del Anticipo(2)</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('amortizacion', '', 'size=20') ?>    
</div>

<div class="form-row">
  <?php echo label_for('ocregval[monfia]', __($labels['ocregval{monfia}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{monfia}')): ?> form-error<?php endif; ?>"></div>
  <?php if ($sf_request->hasError('ocregval{monfia}')): ?>
    <?php echo form_error('ocregval{monfia}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getMonfia', array (
  'size' => 7,
  'control_name' => 'ocregval[monfia]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>SubTotal (1)-(2)-(3)</strong>
  <?php $value = object_input_tag($ocregval, 'getMonper', array (
  'size' => 7,
  'control_name' => 'ocregval[monper]',
)); echo $value ? $value : '&nbsp;' ?>    
</div>

&nbsp;&nbsp;&nbsp;
<fieldset id="sf_fieldset_none" class="">
<legend>Retenciones</legend>
<form name="form1" id="form1">
<?
echo grid_tag($obj2);
?>
</form>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<strong>Total Retenciones(Sin Fianza)</strong>
 <?php $value = object_input_tag($ocregval, 'getTotded', array (
  'size' => 7,
  'control_name' => 'ocregval[totded]',
)); echo $value ? $value : '&nbsp;' ?>
</fieldset>
<div class="form-row">
  <strong>Valuaciones Pagadas</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('valuaciones', '', 'size=20') ?> 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
<strong>Saldo Neto a Pagar</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <?php $value = object_input_tag($ocregval, 'getMonpag', array (
  'size' => 7,
  'control_name' => 'ocregval[monpag]',
)); echo $value ? $value : '&nbsp;' ?>   
</div>
</fieldset>
</div>

<div class="form-row">
<fieldset id="sf_fieldset_none" class="">
<legend>Estado de Cuenta</legend>
<fieldset id="sf_fieldset_none" class="">
<legend>Estado de cuenta del Contrato hasta la Fecha</legend>
<div class="form-row">
  <strong>Monto Total del Contrato</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('total', '', 'size=20') ?> 
  </div>
  
<div class="form-row">
  <strong>Monto Total Valuaciones Presentadas</strong>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getMonval', array (
  'size' => 7,
  'control_name' => 'ocregval[monval]',
)); echo $value ? $value : '&nbsp;' ?>   
</div>

<div class="form-row">
 <strong>Saldo a Liquidar</strong>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getSalliq', array (
  'size' => 7,
  'control_name' => 'ocregval[salliq]',
)); echo $value ? $value : '&nbsp;' ?>    
</div>

<div class="form-row">
 <strong>Retenciones Acumuladas</strong>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getRetacu', array (
  'size' => 7,
  'control_name' => 'ocregval[retacu]',
)); echo $value ? $value : '&nbsp;' ?>
   
</div>
</fieldset>
<fieldset id="sf_fieldset_none" class="">
<legend>Saldo del Anticipo</legend>

<div class="form-row">
 <strong>Monto del Anticipo</strong>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getMonant', array (
  'size' => 7,
  'control_name' => 'ocregval[monant]',
)); echo $value ? $value : '&nbsp;' ?>    
</div>

<div class="form-row">
  <strong>Amortización del Anticipo</strong>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php $value = object_input_tag($ocregval, 'getAmoant', array (
  'size' => 7,
  'control_name' => 'ocregval[amoant]',
)); echo $value ? $value : '&nbsp;' ?>   
</div>
<div class="form-row">
  <strong>Saldo del Anticipo</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <?php echo input_tag('total', '', 'size=20') ?> 
  </div>
</fieldset>
</fieldset>
</div>
<div class="form-row">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<form name="form1" id="form1">
<?
echo grid_tag($obj3);
?>
</form>
</div>

<div class="form-row">
<fieldset id="sf_fieldset_none" class="">
<legend>Porcentajes</legend>
<div class="form-row">
  <?php echo label_for('ocregval[poriva]', __($labels['ocregval{poriva}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{poriva}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregval{poriva}')): ?>
    <?php echo form_error('ocregval{poriva}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getPoriva', array (
  'size' => 7,
  'control_name' => 'ocregval[poriva]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('ocregval[porant]', __($labels['ocregval{porant}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('ocregval{porant}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('ocregval{porant}')): ?>
    <?php echo form_error('ocregval{porant}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($ocregval, 'getPorant', array (
  'size' => 7,
  'control_name' => 'ocregval[porant]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>
</div>

</fieldset>

<?php include_partial('edit_actions', array('ocregval' => $ocregval)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($ocregval->getId()): ?>
<?php echo button_to(__('delete'), 'oycval/delete?id='.$ocregval->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
