<?php
// auto-generated by PropelCidesa
// date: 2009/03/03 13:28:36
?>
    <td><?php echo link_to($fcvalinm->getCodzon() ? $fcvalinm->getCodzon() : __('-'), 'facranpaginm/edit?id='.$fcvalinm->getId().'&codzon='.$fcvalinm->getCodzon()) ?></td>
    <td><?php echo $fcvalinm->getDeszon() ?></td>
