<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/03 17:05:23
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Modificar Asignacion Inicial', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('ingasiini/edit_header', array('ciasiini' => $ciasiini)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('ingasiini/edit_messages', array('ciasiini' => $ciasiini, 'labels' => $labels)) ?>
<?php include_partial('ingasiini/edit_form', array('ciasiini' => $ciasiini,
 'labels' => $labels, 'per' => $per)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('ingasiini/edit_footer', array('ciasiini' => $ciasiini)) ?>
</div>

</div>
