<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/28 19:13:41
?>
<?php echo form_tag('fordefproyectoivss/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fordefpry, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('fordefpry[codpro]', __($labels['fordefpry{codpro}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{codpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{codpro}')): ?>
    <?php echo form_error('fordefpry{codpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCodpro', array (
  'size' => 20,
  'control_name' => 'fordefpry[codpro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
  <?php echo label_for('fordefpry[nompro]', __($labels['fordefpry{nompro}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{nompro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{nompro}')): ?>
    <?php echo form_error('fordefpry{nompro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getNompro', array (
  'size' => 80,
  'control_name' => 'fordefpry[nompro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[codsta]', __($labels['fordefpry{codsta}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{codsta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{codsta}')): ?>
    <?php echo form_error('fordefpry{codsta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCodsta', array (
  'size' => 20,
  'control_name' => 'fordefpry[codsta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[frepagcon]', __($labels['fordefpry{frepagcon}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{frepagcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{frepagcon}')): ?>
    <?php echo form_error('fordefpry{frepagcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getFrepagcon', array (
  'disabled' => true,
  'control_name' => 'fordefpry[frepagcon]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[coddir]', __($labels['fordefpry{coddir}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{coddir}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{coddir}')): ?>
    <?php echo form_error('fordefpry{coddir}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCoddir', array (
  'size' => 20,
  'control_name' => 'fordefpry[coddir]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[desdir]', __($labels['fordefpry{desdir}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{desdir}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{desdir}')): ?>
    <?php echo form_error('fordefpry{desdir}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getDesdir', array (
  'disabled' => true,
  'control_name' => 'fordefpry[desdir]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[fecini]', __($labels['fordefpry{fecini}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{fecini}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{fecini}')): ?>
    <?php echo form_error('fordefpry{fecini}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fordefpry, 'getFecini', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fordefpry[fecini]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[feccul]', __($labels['fordefpry{feccul}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{feccul}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{feccul}')): ?>
    <?php echo form_error('fordefpry{feccul}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fordefpry, 'getFeccul', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fordefpry[feccul]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[montotpry]', __($labels['fordefpry{montotpry}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{montotpry}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{montotpry}')): ?>
    <?php echo form_error('fordefpry{montotpry}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getMontotpry', array (
  'size' => 7,
  'control_name' => 'fordefpry[montotpry]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[ubigeo]', __($labels['fordefpry{ubigeo}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{ubigeo}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{ubigeo}')): ?>
    <?php echo form_error('fordefpry{ubigeo}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getUbigeo', array (
  'size' => 80,
  'control_name' => 'fordefpry[ubigeo]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[codemp]', __($labels['fordefpry{codemp}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{codemp}')): ?>
    <?php echo form_error('fordefpry{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCodemp', array (
  'size' => 20,
  'control_name' => 'fordefpry[codemp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[nomemp]', __($labels['fordefpry{nomemp}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{nomemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{nomemp}')): ?>
    <?php echo form_error('fordefpry{nomemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getNomemp', array (
  'size' => 80,
  'control_name' => 'fordefpry[nomemp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[uniejepri]', __($labels['fordefpry{uniejepri}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{uniejepri}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{uniejepri}')): ?>
    <?php echo form_error('fordefpry{uniejepri}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getUniejepri', array (
  'size' => 32,
  'control_name' => 'fordefpry[uniejepri]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
<br>
<?php echo label_for('fordefpry[uniejepri]', __($labels['fordefpry{uniejepri}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{uniejepri}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{uniejepri}')): ?>
    <?php echo form_error('fordefpry{uniejepri}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getUniejepri', array (
  'size' => 32,
  'control_name' => 'fordefpry[uniejepri]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row"><?php echo label_for('fordefpry[descat]', __($labels['fordefpry{descat}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fordefpry{descat}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fordefpry{descat}')): ?> <?php echo form_error('fordefpry{descat}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fordefpry, 'getDescat', array (
  'disabled' => true,
  'control_name' => 'fordefpry[descat]',
)); echo $value ? $value : '&nbsp;' ?></div>
<br>
<?php echo label_for('fordefpry[enupro]', __($labels['fordefpry{enupro}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fordefpry{enupro}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fordefpry{enupro}')): ?> <?php echo form_error('fordefpry{enupro}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fordefpry, 'getEnupro', array (
  'size' => 80,
  'control_name' => 'fordefpry[enupro]',
)); echo $value ? $value : '&nbsp;' ?></div>
<br>
<?php echo label_for('fordefpry[objestnueeta]', __($labels['fordefpry{objestnueeta}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fordefpry{objestnueeta}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fordefpry{objestnueeta}')): ?> <?php echo form_error('fordefpry{objestnueeta}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fordefpry, 'getObjestnueeta', array (
  'size' => 80,
  'control_name' => 'fordefpry[objestnueeta]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row">
<?php echo label_for('fordefpry[objestins]', __($labels['fordefpry{objestins}']), '') ?>
<div
	class="content<?php if ($sf_request->hasError('fordefpry{objestins}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('fordefpry{objestins}')): ?> <?php echo form_error('fordefpry{objestins}', array('class' => 'form-error-msg')) ?>
<?php endif; ?> <?php $value = object_input_tag($fordefpry, 'getObjestins', array (
  'size' => 80,
  'control_name' => 'fordefpry[objestins]',
)); echo $value ? $value : '&nbsp;' ?></div>
</div>

<div class="form-row"><?php echo label_for('fordefpry[objeesppro]', __($labels['fordefpry{objeesppro}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{objeesppro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{objeesppro}')): ?>
    <?php echo form_error('fordefpry{objeesppro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getObjeesppro', array (
  'size' => 80,
  'control_name' => 'fordefpry[objeesppro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[codequ]', __($labels['fordefpry{codequ}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{codequ}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{codequ}')): ?>
    <?php echo form_error('fordefpry{codequ}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCodequ', array (
  'size' => 20,
  'control_name' => 'fordefpry[codequ]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[desequ]', __($labels['fordefpry{desequ}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{desequ}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{desequ}')): ?>
    <?php echo form_error('fordefpry{desequ}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getDesequ', array (
  'disabled' => true,
  'control_name' => 'fordefpry[desequ]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[dessubobj]', __($labels['fordefpry{dessubobj}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{dessubobj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{dessubobj}')): ?>
    <?php echo form_error('fordefpry{dessubobj}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getDessubobj', array (
  'disabled' => true,
  'control_name' => 'fordefpry[dessubobj]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[dessubsubobj]', __($labels['fordefpry{dessubsubobj}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{dessubsubobj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{dessubsubobj}')): ?>
    <?php echo form_error('fordefpry{dessubsubobj}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getDessubsubobj', array (
  'disabled' => true,
  'control_name' => 'fordefpry[dessubsubobj]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[respro]', __($labels['fordefpry{respro}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{respro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{respro}')): ?>
    <?php echo form_error('fordefpry{respro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getRespro', array (
  'size' => 80,
  'control_name' => 'fordefpry[respro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[benpro]', __($labels['fordefpry{benpro}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{benpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{benpro}')): ?>
    <?php echo form_error('fordefpry{benpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getBenpro', array (
  'size' => 80,
  'control_name' => 'fordefpry[benpro]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[nroempdir]', __($labels['fordefpry{nroempdir}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{nroempdir}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{nroempdir}')): ?>
    <?php echo form_error('fordefpry{nroempdir}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getNroempdir', array (
  'size' => 7,
  'control_name' => 'fordefpry[nroempdir]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[nroempind]', __($labels['fordefpry{nroempind}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{nroempind}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{nroempind}')): ?>
    <?php echo form_error('fordefpry{nroempind}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getNroempind', array (
  'size' => 7,
  'control_name' => 'fordefpry[nroempind]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[codsta]', __($labels['fordefpry{codsta}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{codsta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{codsta}')): ?>
    <?php echo form_error('fordefpry{codsta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getCodsta', array (
  'size' => 20,
  'control_name' => 'fordefpry[codsta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefpry[dessta]', __($labels['fordefpry{dessta}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('fordefpry{dessta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefpry{dessta}')): ?>
    <?php echo form_error('fordefpry{dessta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefpry, 'getDessta', array (
  'disabled' => true,
  'control_name' => 'fordefpry[dessta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
<fieldset><legend>Organismos Publicos</legend>
<div class="form-row">
<div id="grid01" class="grid01">
<table border="0" class="sf_admin_list" whith="100%">
<?php $nombre=array(0 => 'Codigo:', 1 => 'Descripcion'); ?>
<? if ( count($rs)>0){
	$i=0;
	foreach ($rs as $k=>$fila) {
		$i++;
		if($i==1){?>
	<thead>
		<tr>
		<? foreach ($fila as $key => $value){?>
			<th><?=$nombre[$key]?></th>
			<? }?>
		</tr>
	</thead>
	<? }?>
	<tr>
	<? foreach ($fila as $key => $value){?>
		<td><?=$value?></td>
		<? }?>
	</tr>
	<? }
}
?>
</table>
</div>
</div>

</fieldset>

</fieldset>

<?php include_partial('edit_actions', array('fordefpry' => $fordefpry)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fordefpry->getId()): ?>
<?php echo button_to(__('delete'), 'fordefproyectoivss/delete?id='.$fordefpry->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
