<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/26 17:22:13
?>
<!-- 
<ul class="sf_admin_actions">
  <li><
  ?php echo button_to(__('create'), 'nomperprestamos/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
 -->