<?php
// auto-generated by PropelCidesa
// date: 2009/02/16 09:19:46
?>
    <td><?php echo link_to($npdefcpt->getCodcon() ? $npdefcpt->getCodcon() : __('-'), 'nomcodprenom/edit?id='.$npdefcpt->getId().'&codcon='.$npdefcpt->getCodcon()) ?></td>
    <td><?php echo $npdefcpt->getNomcon() ?></td>
