<?php
// auto-generated by sfPropelAdmin
// date: 2007/11/26 14:26:03
?>
    <td><?php echo link_to($caretser->getCodser() ? $caretser->getCodser() : __('-'), 'almretser/edit?id='.$caretser->getId().'&codser='.$caretser->getCodser()) ?></td>
