<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/30 16:49:45
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'nomnomcalnomind/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
 