<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/15 08:03:28
?>
<td colspan="4">
    <?php echo $opdefemp->getCodemp() ?>
     - 
    <?php echo $nomemp ?>
     -
    <?php echo $opdefemp->getCtapag() ?>
     - 
    <?php echo $opdefemp->getNumini() ?>
     - 
    <?php echo $opdefemp->getForubi() ?>
     - 
</td>