<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/09 17:27:37
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'Javascript', 'Grid', 'I18N', 'PopUp', 'Linktoapp') ?>
<?php echo javascript_include_tag('ajax') ?>
<?php echo javascript_include_tag('tools') ?>
<?php if ($div=='S')
{?>

<form name="form1" id="form1">
<?
  echo grid_tag($obj);
?>
</form>
<?php }