<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/19 10:24:51
?>
<?php echo form_tag('almforent/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($caforent, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('caforent[codforent]', __($labels['caforent{codforent}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('caforent{codforent}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caforent{codforent}')): ?>
    <?php echo form_error('caforent{codforent}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caforent, 'getCodforent', array (
  'size' => 20,
  'control_name' => 'caforent[codforent]',
  'maxlength' => 6,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('caforent[desforent]', __($labels['caforent{desforent}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('caforent{desforent}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('caforent{desforent}')): ?>
    <?php echo form_error('caforent{desforent}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($caforent, 'getDesforent', array (
  'size' => 80,
  'control_name' => 'caforent[desforent]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('caforent' => $caforent)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($caforent->getId()): ?>
<?php echo button_to(__('delete'), 'almforent/delete?id='.$caforent->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
