<?php
// auto-generated by PropelCidesa
// date: 2010/11/23 09:55:40
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Catalogo') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php
$manmodcontra=H::getConfAppGen('manmodcontra');
if ($manmodcontra=='S')
{
    echo __('EdiciÃ³n de Situaciones Posibles de la ContrataciÃ³n',
array());
}else {
echo __('EdiciÃ³n de Situaciones Posibles de la LicitaciÃ³n', 
array());
} ?></h1>


<div id="sf_admin_header">
<?php include_partial('licsicact/edit_header', array('lisicact' => $lisicact, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('licsicact/edit_messages', array('lisicact' => $lisicact, 'labels' => $labels, 'params' => $params)) ?>
<?php include_partial('licsicact/edit_form', array('lisicact' => $lisicact, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('licsicact/edit_footer', array('lisicact' => $lisicact, 'labels' => $labels, 'params' => $params)) ?>
</div>

</div>
