<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/27 13:12:48
?>
<?php echo form_tag('fordefsubsubobj/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fordefsubsubobj, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">
<legend>Datos del Sub Sub Objetivo</legend>
<div class="form-row">
  <?php echo label_for('fordefsubsubobj[codequ]', __($labels['fordefsubsubobj{codequ}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fordefsubsubobj{codequ}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefsubsubobj{codequ}')): ?>
    <?php echo form_error('fordefsubsubobj{codequ}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>
  
  <?php echo select_tag('fordefsubsubobj[codequ]', options_for_select($equilibrio,$fordefsubsubobj->getCodequ())); ?>
  </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefsubsubobj[codsubobj]', __($labels['fordefsubsubobj{codsubobj}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fordefsubsubobj{codsubobj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefsubsubobj{codsubobj}')): ?>
    <?php echo form_error('fordefsubsubobj{codsubobj}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo select_tag('fordefsubsubobj[codsubobj]', options_for_select($Subobjetivo,$fordefsubsubobj->getCodsubobj())); ?>
  </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefsubsubobj[codsubsubobj]', __($labels['fordefsubsubobj{codsubsubobj}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fordefsubsubobj{codsubsubobj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefsubsubobj{codsubsubobj}')): ?>
    <?php echo form_error('fordefsubsubobj{codsubsubobj}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefsubsubobj, 'getCodsubsubobj', array (
  'size' => 20,
  'control_name' => 'fordefsubsubobj[codsubsubobj]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fordefsubsubobj[dessubsubobj]', __($labels['fordefsubsubobj{dessubsubobj}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fordefsubsubobj{dessubsubobj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fordefsubsubobj{dessubsubobj}')): ?>
    <?php echo form_error('fordefsubsubobj{dessubsubobj}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fordefsubsubobj, 'getDessubsubobj', array (
  'size' => 80,
  'control_name' => 'fordefsubsubobj[dessubsubobj]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>

<?php include_partial('edit_actions', array('fordefsubsubobj' => $fordefsubsubobj)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fordefsubsubobj->getId()): ?>
<?php echo button_to(__('delete'), 'fordefsubsubobj/delete?id='.$fordefsubsubobj->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
