<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/27 13:12:48
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edicion Sub Sub Objetivos', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('fordefsubsubobj/edit_header', array('fordefsubsubobj' => $fordefsubsubobj)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('fordefsubsubobj/edit_messages', array('fordefsubsubobj' => $fordefsubsubobj, 'labels' => $labels)) ?>
<?php include_partial('fordefsubsubobj/edit_form', array('fordefsubsubobj' => $fordefsubsubobj, 'equilibrio' => $equilibrio, 'Subobjetivo' => $Subobjetivo, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('fordefsubsubobj/edit_footer', array('fordefsubsubobj' => $fordefsubsubobj)) ?>
</div>

</div>
