<?php
// auto-generated by sfPropelAdmin
// date: 2007/03/17 14:19:20
?>
<?php echo form_tag('pagmodret/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($opordpag, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">
<legend>Rentenciones por Orden</legend>
<div class="form-row">
  <?php echo label_for('opordpag[numord]', __($labels['opordpag{numord}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opordpag{numord}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opordpag{numord}')): ?>
    <?php echo form_error('opordpag{numord}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opordpag, 'getNumord', array (
  'size' => 20,
  'control_name' => 'opordpag[numord]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;
<strong>Fecha</strong>
<?php $value = object_input_date_tag($opordpag, 'getFecemi', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'opordpag[fecemi]',
  'date_format' => 'dd/MM/yy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('opordpag[desord]', __($labels['opordpag{desord}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opordpag{desord}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opordpag{desord}')): ?>
    <?php echo form_error('opordpag{desord}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opordpag, 'getDesord', array (
  'size' => 80,
  'control_name' => 'opordpag[desord]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('opordpag[tipcau]', __($labels['opordpag{tipcau}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opordpag{tipcau}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opordpag{tipcau}')): ?>
    <?php echo form_error('opordpag{tipcau}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opordpag, 'getTipcau', array (
  'size' => 20,
  'control_name' => 'opordpag[tipcau]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;
<?php echo input_tag('reten',$reten,'size=50,disabled=true') ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('opordpag[cedrif]', __($labels['opordpag{cedrif}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('opordpag{cedrif}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('opordpag{cedrif}')): ?>
    <?php echo form_error('opordpag{cedrif}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($opordpag, 'getCedrif', array (
  'size' => 20,
  'control_name' => 'opordpag[cedrif]',
)); echo $value ? $value : '&nbsp;' ?>
&nbsp;
<?php $value = object_input_tag($opordpag, 'getNomben', array (
  'size' => 80,
  'control_name' => 'opordpag[nomben]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>
<div class="grid01" id="grid01">
<fieldset>
<legend>Imputaciones Presupuestarias</legend>
<table border="0" class="sf_admin_list">
<? 
$titulo=array(0 => 'Codigo Presupuestario', 1 => 'Titulo', 2 => 'Tipo', 3 => 'Retencion', 4 => 'Monto', 5 => 'Referencia');

if ( count($rs)>0){
$i=0;
foreach ($rs as $k=>$fila) {
    $i++;
    if($i==1){?>
      <thead><tr>
    <? foreach ($fila as $key => $value){?>
        <th><?=$titulo[$key]?></th>
    <? }?>
      </tr> </thead>
    <? }?>
<tr>
<? foreach ($fila as $key => $value){?>
    <td><?=$value?></td>
<? }?>
</tr>
<? }
  }
?></table>
</fieldset>
</div> 


<?php include_partial('edit_actions', array('opordpag' => $opordpag)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($opordpag->getId()): ?>
<?php echo button_to(__('delete'), 'pagmodret/delete?id='.$opordpag->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
