<?php
// auto-generated by sfPropelAdmin
// date: 2007/04/03 16:24:37
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Edición de Tipos de Ingresos', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('ingajustenew/edit_header', array('ciajuste' => $ciajuste)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('ingajustenew/edit_messages', array('ciajuste' => $ciajuste, 'labels' => $labels)) ?>
<?php include_partial('ingajustenew/edit_form', array('ciajuste' => $ciajuste, 'labels' => $labels, 'pagercimovaju' => $pagercimovaju)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('ingajustenew/edit_footer', array('ciajuste' => $ciajuste)) ?>
</div>

</div>
