<?php
// auto-generated by sfPropelAdmin
// date: 2008/01/31 11:31:56
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'nomespconceptos/list?id='.$npnomespnomtip->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'form' => 'sf_admin_edit_form',
  'class' => 'sf_admin_action_save',
)) ?></li>
      <li><?php echo button_to(__('create'), 'nomespconceptos/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
