--CARLOS RAMIREZ
--SE AGREGO LA FRECUENCIA PARA LOS CORRELATIVOS DE LA FORMA DE INCAPACIDADES
CREATE SEQUENCE npincapa_correl
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 8
  CACHE 1;
ALTER TABLE npincapa_correl OWNER TO postgres;

--CARLOS RAMIREZ
alter table npcargos
  add column canmix numeric(6,0);
  
--CARLOS RAMIREZ
--PRESTACIONES REALIZADO EN NOVIEMBRE PERO NO SE HABIA SUBIDO AL REPOSITORIO
alter table npvacdefgen
  add column vacant varchar(1);  