--CARLOS RAMIREZ
--SE AGREGO LA FRECUENCIA PARA LOS CORRELATIVOS DE LA FORMA DE INCAPACIDADES
CREATE SEQUENCE npincapa_correl
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 8
  CACHE 1;
ALTER TABLE npincapa_correl OWNER TO postgres;