<?php
// auto-generated by PropelCidesa
// date: 2009/08/06 17:15:37
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1>
<?php if ($despnotent=="") {?>
<?php echo __('Despachos',
array()) ?>
<?php }else {?>
<?php echo __('Notas de Entrega',
array()) ?>
<?php }?>
</h1>

<div id="sf_admin_header">
<?php include_partial('fadesp/list_header', array('pager' => $pager)) ?>
<?php include_partial('fadesp/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
<?php include_partial('filters', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_content">
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('fadesp/list', array('pager' => $pager)) ?>
<?php endif; ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('fadesp/list_footer', array('pager' => $pager)) ?>
</div>

</div>
