<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/14 11:33:59
?>
<?php echo form_tag('facfueing/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($fcfuepre, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('fcfuepre[codfue]', __($labels['fcfuepre{codfue}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{codfue}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{codfue}')): ?>
    <?php echo form_error('fcfuepre{codfue}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getCodfue', array (
  'size' => 20,
  'control_name' => 'fcfuepre[codfue]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[nomfue]', __($labels['fcfuepre{nomfue}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{nomfue}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{nomfue}')): ?>
    <?php echo form_error('fcfuepre{nomfue}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getNomfue', array (
  'size' => 80,
  'control_name' => 'fcfuepre[nomfue]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[nomabr]', __($labels['fcfuepre{nomabr}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{nomabr}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{nomabr}')): ?>
    <?php echo form_error('fcfuepre{nomabr}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getNomabr', array (
  'size' => 20,
  'control_name' => 'fcfuepre[nomabr]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[frecob]', __($labels['fcfuepre{frecob}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{frecob}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{frecob}')): ?>
    <?php echo form_error('fcfuepre{frecob}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php /*$value = object_input_tag($fcfuepre, 'getFrecob', array (
  'size' => 7,
  'control_name' => 'fcfuepre[frecob]',
)); echo $value ? $value : '&nbsp;' */ ?>

	<?php echo select_tag('fcfuepre[frecob]', options_for_select($listafrecuencia,$fcfuepre->getFrecob(), 'include_custom=Seleccione uno')) ?>

    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[diavso]', __($labels['fcfuepre{diavso}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{diavso}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{diavso}')): ?>
    <?php echo form_error('fcfuepre{diavso}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getDiavso', array (
  'size' => 20,
  'control_name' => 'fcfuepre[diavso]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
<?php echo label_for('fcfuepre[deufra]', __($labels['fcfuepre{deufra}']), 'class="required" ') ?>
<?  if ($fcfuepre->getDeufra()=='S'){
	echo radiobutton_tag('fcfuepre[deufra]','S', true) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[deufra]','N', false) .'  '. "No"."<br>";

}elseif ($fcfuepre->getDeufra()=='N'){
	echo radiobutton_tag('fcfuepre[deufra]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[deufra]','N', true) .'  '. "No"."<br>";

}else{
	echo radiobutton_tag('fcfuepre[deufra]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[deufra]','N', false) .'  '. "No"."<br>";

}
?>
</div>

<div class="form-row">
<?php echo label_for('fcfuepre[autliq]', __($labels['fcfuepre{autliq}']), 'class="required" ') ?>
<?  if ($fcfuepre->getAutliq()=='S'){
	echo radiobutton_tag('fcfuepre[autliq]','S', true) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[autliq]','N', false) .'  '. "No"."<br>";

}elseif ($fcfuepre->getAutliq()=='N'){
	echo radiobutton_tag('fcfuepre[autliq]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[autliq]','N', true) .'  '. "No"."<br>";

}else{
	echo radiobutton_tag('fcfuepre[autliq]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[autliq]','N', false) .'  '. "No"."<br>";

}
?>
</div>


<div class="form-row">
<?php echo label_for('fcfuepre[simpre]', __($labels['fcfuepre{simpre}']), 'class="required" ') ?>
<?  if ($fcfuepre->getSimpre()=='P'){
	echo radiobutton_tag('fcfuepre[simpre]','P', true) .'  '. "Previa"."<br>";
	echo radiobutton_tag('fcfuepre[simpre]','S', false) .'  '. "Simultanea"."<br>";

}elseif ($fcfuepre->getSimpre()=='S'){
	echo radiobutton_tag('fcfuepre[simpre]','P', false) .'  '. "Previa"."<br>";
	echo radiobutton_tag('fcfuepre[simpre]','S', true) .'  '. "Simultanea"."<br>";

}else{
	echo radiobutton_tag('fcfuepre[simpre]','P', false) .'  '. "Previa"."<br>";
	echo radiobutton_tag('fcfuepre[simpre]','S', false) .'  '. "Simultanea"."<br>";

}
?>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[ingrec]', __($labels['fcfuepre{ingrec}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{ingrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{ingrec}')): ?>
    <?php echo form_error('fcfuepre{ingrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getIngrec', array (
  'size' => 20,
  'control_name' => 'fcfuepre[ingrec]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[descta]', __($labels['fcfuepre{descta}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{descta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{descta}')): ?>
    <?php echo form_error('fcfuepre{descta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getDescta', array (
  'disabled' => true,
  'control_name' => 'fcfuepre[descta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[fueing]', __($labels['fcfuepre{fueing}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{fueing}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{fueing}')): ?>
    <?php echo form_error('fcfuepre{fueing}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getFueing', array (
  'size' => 32,
  'control_name' => 'fcfuepre[fueing]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[descta1]', __($labels['fcfuepre{descta1}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{descta1}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{descta1}')): ?>
    <?php echo form_error('fcfuepre{descta1}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getDescta1', array (
  'disabled' => true,
  'control_name' => 'fcfuepre[descta1]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[codprei]', __($labels['fcfuepre{codprei}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{codprei}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{codprei}')): ?>
    <?php echo form_error('fcfuepre{codprei}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getCodprei', array (
  'size' => 20,
  'control_name' => 'fcfuepre[codprei]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[descta2]', __($labels['fcfuepre{descta2}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{descta2}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{descta2}')): ?>
    <?php echo form_error('fcfuepre{descta2}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getDescta2', array (
  'disabled' => true,
  'control_name' => 'fcfuepre[descta2]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>


<fieldset>
<legend>Porcentajes</legend>
<div class="form-row">
  <?php echo label_for('fcfuepre[monmor]', __($labels['fcfuepre{monmor}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{monmor}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{monmor}')): ?>
    <?php echo form_error('fcfuepre{monmor}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getMonmor', array (
  'size' => 7,
  'control_name' => 'fcfuepre[monmor]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[propag]', __($labels['fcfuepre{propag}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{propag}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{propag}')): ?>
    <?php echo form_error('fcfuepre{propag}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getPropag', array (
  'size' => 7,
  'control_name' => 'fcfuepre[propag]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>


<fieldset>
<legend>Periodo</legend>
<div class="form-row">
  <?php echo label_for('fcfuepre[permor]', __($labels['fcfuepre{permor}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{permor}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{permor}')): ?>
    <?php echo form_error('fcfuepre{permor}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getPermor', array (
  'size' => 7,
  'control_name' => 'fcfuepre[permor]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[perppg]', __($labels['fcfuepre{perppg}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{perppg}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{perppg}')): ?>
    <?php echo form_error('fcfuepre{perppg}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($fcfuepre, 'getPerppg', array (
  'size' => 7,
  'control_name' => 'fcfuepre[perppg]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>

<div class="form-row">
<?php echo label_for('fcfuepre[tipmul]', __($labels['fcfuepre{tipmul}']), 'class="required" ') ?>
<?  if ($fcfuepre->getTipmul()=='S'){
	echo radiobutton_tag('fcfuepre[tipmul]','S', true) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[tipmul]','N', false) .'  '. "No"."<br>";

}elseif ($fcfuepre->getTipmul()=='N'){
	echo radiobutton_tag('fcfuepre[tipmul]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[tipmul]','N', true) .'  '. "No"."<br>";

}else{
	echo radiobutton_tag('fcfuepre[tipmul]','S', false) .'  '. "Si"."<br>";
	echo radiobutton_tag('fcfuepre[tipmul]','N', false) .'  '. "No"."<br>";

}
?>
</div>

<fieldset>
<legend>Fechas</legend>
<div class="form-row">
  <?php echo label_for('fcfuepre[inieje]', __($labels['fcfuepre{inieje}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{inieje}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{inieje}')): ?>
    <?php echo form_error('fcfuepre{inieje}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fcfuepre, 'getInieje', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcfuepre[inieje]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[fineje]', __($labels['fcfuepre{fineje}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{fineje}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{fineje}')): ?>
    <?php echo form_error('fcfuepre{fineje}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fcfuepre, 'getFineje', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcfuepre[fineje]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[fecufa]', __($labels['fcfuepre{fecufa}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{fecufa}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{fecufa}')): ?>
    <?php echo form_error('fcfuepre{fecufa}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fcfuepre, 'getFecufa', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcfuepre[fecufa]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('fcfuepre[feccie]', __($labels['fcfuepre{feccie}']), 'class="required"') ?>
  <div class="content<?php if ($sf_request->hasError('fcfuepre{feccie}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fcfuepre{feccie}')): ?>
    <?php echo form_error('fcfuepre{feccie}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($fcfuepre, 'getFeccie', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fcfuepre[feccie]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>
</fieldset>

<?php echo input_hidden_tag('deufec', '0'); ?>
<?php echo input_hidden_tag('recfec', '0'); ?>

</fieldset>

<?php include_partial('edit_actions', array('fcfuepre' => $fcfuepre)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fcfuepre->getId()): ?>
<?php echo button_to(__('delete'), 'facfueing/delete?id='.$fcfuepre->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
