<?php
// auto-generated by sfPropelAdmin
// date: 2007/12/20 16:28:33
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Definición Contable de Muebles por Lotes',
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('biedefconlotm/edit_header', array('bndefcon' => $bndefcon)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('biedefconlotm/edit_messages', array('bndefcon' => $bndefcon, 'labels' => $labels)) ?>
<?php include_partial('biedefconlotm/edit_form', array('bndefcon' => $bndefcon, 'labels' => $labels, 'mascaracatalogo' => $mascaracatalogo, 'mascaraformatoubi' => $mascaraformatoubi, 'mascaralonformato' => $mascaralonformato, 'mascaralonubicacion' => $mascaralonubicacion)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('biedefconlotm/edit_footer', array('bndefcon' => $bndefcon)) ?>
</div>

</div>
